// Code generated by iacg; DO NOT EDIT.
package cynosdb

import (
	"context"
	"errors"
	"log"

	"github.com/hashicorp/terraform-plugin-sdk/v2/helper/resource"
	"github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema"
	cynosdbv20190107 "github.com/tencentcloud/tencentcloud-sdk-go/tencentcloud/cynosdb/v20190107"
	tccommon "github.com/tencentcloudstack/terraform-provider-tencentcloud/tencentcloud/common"
	"github.com/tencentcloudstack/terraform-provider-tencentcloud/tencentcloud/internal/helper"
)

func ResourceTencentCloudCynosdbBackupConfig() *schema.Resource {
	return &schema.Resource{
		Create: resourceTencentCloudCynosdbBackupConfigCreate,
		Read:   resourceTencentCloudCynosdbBackupConfigRead,
		Update: resourceTencentCloudCynosdbBackupConfigUpdate,
		Delete: resourceTencentCloudCynosdbBackupConfigDelete,
		Importer: &schema.ResourceImporter{
			State: schema.ImportStatePassthrough,
		},
		Schema: map[string]*schema.Schema{
			"cluster_id": {
				Type:        schema.TypeString,
				Required:    true,
				ForceNew:    true,
				Description: "集群 ID。",
			},

			"backup_time_beg": {
				Type:        schema.TypeInt,
				Required:    true,
				Description: "完整备份开始时间。取值范围：[0-24*3600]。例如，0:00 AM、1:00 AM 和 2:00 AM 分别表示为 0、3600 和 7200。",
			},

			"backup_time_end": {
				Type:        schema.TypeInt,
				Required:    true,
				Description: "完整备份结束时间。取值范围：[0-24*3600]。例如，0:00 AM、1:00 AM 和 2:00 AM 分别表示为 0、3600 和 7200。",
			},

			"reserve_duration": {
				Type:        schema.TypeInt,
				Required:    true,
				Description: "备份保留期（以秒为单位）。在此期限过后，备份将被清除。 7 天表示为 3600*24*7 = 604800。最大值：158112000。",
			},

			"backup_freq": {
				Type: schema.TypeList,
				// Optional:    true,
				Computed:    true,
				Description: "备份频率。它是一个包含 7 个元素的数组，对应于星期一到星期日。 full：完全备份；增量：增量备份。该参数目前无法修改，无需输入。",
				Elem: &schema.Schema{
					Type: schema.TypeString,
				},
			},

			"backup_type": {
				Type: schema.TypeString,
				// Optional:    true,
				Computed:    true,
				Description: "备份模式。逻辑：逻辑备份；快照：快照备份。该参数目前无法修改，无需输入。",
			},

			"logic_backup_config": {
				Type:        schema.TypeList,
				Optional:    true,
				Computed:    true,
				MaxItems:    1,
				Description: "逻辑备份配置。如果未启用，请勿设置该字段。示例值： [{\"LogicBackupEnable\": \"ON\",\"LogicBackupTimeBeg\": \"2023-04-24 15:06:04\",\"LogicBackupTimeEnd\": \"2024-04-24 15:06:04\",\"LogicReserveDuration\": \“60\”，\“LogicCrossRegionsEnable\”：\“ON\”，\“LogicCrossRegions\”：[\“ap-广州\”]}]。",
				Elem: &schema.Resource{
					Schema: map[string]*schema.Schema{
						"logic_backup_enable": {
							Type:        schema.TypeString,
							Optional:    true,
							Computed:    true,
							Description: "是否启用自动逻辑备份。值：“开”、“关”。",
						},
						"logic_backup_time_beg": {
							Type:        schema.TypeInt,
							Optional:    true,
							Description: "自动逻辑备份开始时间。当“logic_backup_enable”为“OFF”时，必须为“0”或不输入。示例值：2。",
						},
						"logic_backup_time_end": {
							Type:        schema.TypeInt,
							Optional:    true,
							Description: "自动逻辑备份结束时间。当“logic_backup_enable”为“OFF”时，必须为“0”或不输入。示例值：6。",
						},
						"logic_reserve_duration": {
							Type:        schema.TypeInt,
							Optional:    true,
							Description: "自动逻辑备份保留期限。当“logic_backup_enable”为“OFF”时，必须为“0”或不输入。值范围：[259200,158112000]。 `logic_backup_enable`为`OFF`，创建时不能设置`logic_reserve_duration`。",
						},
						"logic_cross_regions_enable": {
							Type:        schema.TypeString,
							Optional:    true,
							Description: "是否启用跨地域逻辑备份。当“logic_backup_enable”为“OFF”时无法输入。当“logic_backup_enable”为“ON”时，“logic_cross_regions_enable”设置“ON”才会生效。值：“开”、“关”。",
						},
						"logic_cross_regions": {
							Type:        schema.TypeSet,
							Optional:    true,
							Description: "跨区域逻辑备份。示例值：[\"ap-guangzhou\"]。当“logic_backup_enable”为“OFF”时，必须为“[]”或不输入。",
							Elem: &schema.Schema{
								Type: schema.TypeString,
							},
						},
					},
				},
			},

			"snapshot_secondary_backup_config": {
				Type:        schema.TypeList,
				Optional:    true,
				Computed:    true,
				MaxItems:    1,
				Description: "辅助快照备份配置。",
				Elem: &schema.Resource{
					Schema: map[string]*schema.Schema{
						"backup_custom_auto_time": {
							Type:        schema.TypeBool,
							Optional:    true,
							Computed:    true,
							Description: "是否使用系统自动时间。",
						},
						"backup_time_beg": {
							Type:        schema.TypeInt,
							Optional:    true,
							Computed:    true,
							Description: "备份开始时间。范围：[0-24*3600]。例如。 0:00、1:00、2:00 分别为 0、3600、7200。",
						},
						"backup_time_end": {
							Type:        schema.TypeInt,
							Optional:    true,
							Computed:    true,
							Description: "备份结束时间。范围：[0-24*3600]。例如。 0:00、1:00、2:00 分别为 0、3600、7200。",
						},
						"backup_week_days": {
							Type:        schema.TypeList,
							Optional:    true,
							Computed:    true,
							Description: "备份工作日数组（长度7，周日到周六）。值：完整、增量、无。",
							Elem: &schema.Schema{
								Type: schema.TypeString,
							},
						},
						"backup_interval_time": {
							Type:        schema.TypeInt,
							Optional:    true,
							Computed:    true,
							Description: "备份间隔时间。",
						},
						"reserve_duration": {
							Type:        schema.TypeInt,
							Optional:    true,
							Computed:    true,
							Description: "备份保留期（以秒为单位）。 7 天 = 604800。最大值：158112000。",
						},
						"backup_trigger_strategy": {
							Type:        schema.TypeString,
							Optional:    true,
							Computed:    true,
							Description: "备份触发策略。值：“periodically”（定期自动备份）、“frequent”（高频备份）。",
						},
						"cross_regions_enable": {
							Type:        schema.TypeString,
							Computed:    true,
							Description: "是否启用跨区域备份。值：“是”、“否”。",
						},
						"cross_regions": {
							Type:        schema.TypeList,
							Computed:    true,
							Description: "跨区域备份目标区域。",
							Elem: &schema.Schema{
								Type: schema.TypeString,
							},
						},
						"auto_copy_vaults": {
							Type:        schema.TypeList,
							Optional:    true,
							Computed:    true,
							Description: "自动复制保管库配置列表。",
							Elem: &schema.Resource{
								Schema: map[string]*schema.Schema{
									"vault_id": {
										Type:        schema.TypeString,
										Optional:    true,
										Computed:    true,
										Description: "保险库 ID。",
									},
									"vault_region": {
										Type:        schema.TypeString,
										Optional:    true,
										Computed:    true,
										Description: "避难所区域。",
									},
								},
							},
						},
					},
				},
			},
		},
	}
}

func resourceTencentCloudCynosdbBackupConfigCreate(d *schema.ResourceData, meta interface{}) error {
	defer tccommon.LogElapsed("resource.tencentcloud_cynosdb_backup_config.create")()
	defer tccommon.InconsistentCheck(d, meta)()

	var (
		clusterId string
	)
	if v, ok := d.GetOk("cluster_id"); ok {
		clusterId = v.(string)
	}
	if logicBackupConfigMap, ok := helper.InterfacesHeadMap(d, "logic_backup_config"); ok {
		if v, ok := logicBackupConfigMap["logic_backup_enable"].(string); ok && v != "" {
			if v == "OFF" {
				return errors.New("`logic_backup_enable` is `OFF`, `logic_backup_config` cannot be set when creating.")
			}
		}
	}

	d.SetId(clusterId)

	return resourceTencentCloudCynosdbBackupConfigUpdate(d, meta)
}

func resourceTencentCloudCynosdbBackupConfigRead(d *schema.ResourceData, meta interface{}) error {
	defer tccommon.LogElapsed("resource.tencentcloud_cynosdb_backup_config.read")()
	defer tccommon.InconsistentCheck(d, meta)()

	logId := tccommon.GetLogId(tccommon.ContextNil)

	ctx := tccommon.NewResourceLifeCycleHandleFuncContext(context.Background(), logId, d, meta)

	service := CynosdbService{client: meta.(tccommon.ProviderMeta).GetAPIV3Conn()}

	clusterId := d.Id()

	respData, err := service.DescribeCynosdbBackupConfigById(ctx, clusterId)
	if err != nil {
		return err
	}

	if respData == nil {
		d.SetId("")
		log.Printf("[WARN]%s resource `cynosdb_backup_config` [%s] not found, please check if it has been deleted.\n", logId, d.Id())
		return nil
	}

	_ = d.Set("cluster_id", clusterId)

	if respData.BackupTimeBeg != nil {
		_ = d.Set("backup_time_beg", respData.BackupTimeBeg)
	}

	if respData.BackupTimeEnd != nil {
		_ = d.Set("backup_time_end", respData.BackupTimeEnd)
	}

	if respData.ReserveDuration != nil {
		_ = d.Set("reserve_duration", respData.ReserveDuration)
	}

	if respData.BackupFreq != nil {
		_ = d.Set("backup_freq", respData.BackupFreq)
	}

	if respData.BackupType != nil {
		_ = d.Set("backup_type", respData.BackupType)
	}

	logicBackupConfigMap := map[string]interface{}{}

	if respData.LogicBackupConfig != nil {
		if respData.LogicBackupConfig.LogicBackupEnable != nil {
			logicBackupConfigMap["logic_backup_enable"] = respData.LogicBackupConfig.LogicBackupEnable
		}

		if respData.LogicBackupConfig.LogicBackupTimeBeg != nil {
			logicBackupConfigMap["logic_backup_time_beg"] = respData.LogicBackupConfig.LogicBackupTimeBeg
		}

		if respData.LogicBackupConfig.LogicBackupTimeEnd != nil {
			logicBackupConfigMap["logic_backup_time_end"] = respData.LogicBackupConfig.LogicBackupTimeEnd
		}

		if respData.LogicBackupConfig.LogicReserveDuration != nil {
			logicBackupConfigMap["logic_reserve_duration"] = respData.LogicBackupConfig.LogicReserveDuration
		}

		if respData.LogicBackupConfig.LogicCrossRegionsEnable != nil {
			logicBackupConfigMap["logic_cross_regions_enable"] = respData.LogicBackupConfig.LogicCrossRegionsEnable
		}

		if respData.LogicBackupConfig.LogicCrossRegions != nil {
			logicBackupConfigMap["logic_cross_regions"] = respData.LogicBackupConfig.LogicCrossRegions
		}

		_ = d.Set("logic_backup_config", []interface{}{logicBackupConfigMap})
	}

	if respData.SnapshotSecondaryBackupConfig != nil {
		snapshotSecondaryBackupConfigMap := map[string]interface{}{}
		cfg := respData.SnapshotSecondaryBackupConfig

		if cfg.BackupCustomAutoTime != nil {
			snapshotSecondaryBackupConfigMap["backup_custom_auto_time"] = cfg.BackupCustomAutoTime
		}

		if cfg.BackupTimeBeg != nil {
			snapshotSecondaryBackupConfigMap["backup_time_beg"] = cfg.BackupTimeBeg
		}

		if cfg.BackupTimeEnd != nil {
			snapshotSecondaryBackupConfigMap["backup_time_end"] = cfg.BackupTimeEnd
		}

		if cfg.BackupWeekDays != nil {
			weekDays := make([]string, 0, len(cfg.BackupWeekDays))
			for _, v := range cfg.BackupWeekDays {
				weekDays = append(weekDays, *v)
			}
			snapshotSecondaryBackupConfigMap["backup_week_days"] = weekDays
		}

		if cfg.BackupIntervalTime != nil {
			snapshotSecondaryBackupConfigMap["backup_interval_time"] = cfg.BackupIntervalTime
		}

		if cfg.ReserveDuration != nil {
			snapshotSecondaryBackupConfigMap["reserve_duration"] = cfg.ReserveDuration
		}

		if cfg.BackupTriggerStrategy != nil {
			snapshotSecondaryBackupConfigMap["backup_trigger_strategy"] = cfg.BackupTriggerStrategy
		}

		if cfg.CrossRegionsEnable != nil {
			snapshotSecondaryBackupConfigMap["cross_regions_enable"] = cfg.CrossRegionsEnable
		}

		if cfg.CrossRegions != nil {
			regions := make([]string, 0, len(cfg.CrossRegions))
			for _, v := range cfg.CrossRegions {
				regions = append(regions, *v)
			}
			snapshotSecondaryBackupConfigMap["cross_regions"] = regions
		}

		if cfg.AutoCopyVaults != nil {
			vaults := make([]interface{}, 0, len(cfg.AutoCopyVaults))
			for _, v := range cfg.AutoCopyVaults {
				vaultMap := map[string]interface{}{}
				if v.VaultId != nil {
					vaultMap["vault_id"] = v.VaultId
				}
				if v.VaultRegion != nil {
					vaultMap["vault_region"] = v.VaultRegion
				}
				vaults = append(vaults, vaultMap)
			}
			snapshotSecondaryBackupConfigMap["auto_copy_vaults"] = vaults
		}

		_ = d.Set("snapshot_secondary_backup_config", []interface{}{snapshotSecondaryBackupConfigMap})
	}

	_ = clusterId
	return nil
}

func resourceTencentCloudCynosdbBackupConfigUpdate(d *schema.ResourceData, meta interface{}) error {
	defer tccommon.LogElapsed("resource.tencentcloud_cynosdb_backup_config.update")()
	defer tccommon.InconsistentCheck(d, meta)()

	logId := tccommon.GetLogId(tccommon.ContextNil)

	ctx := tccommon.NewResourceLifeCycleHandleFuncContext(context.Background(), logId, d, meta)

	clusterId := d.Id()

	needChange := false
	mutableArgs := []string{"backup_time_beg", "backup_time_end", "reserve_duration", "backup_freq", "backup_type", "logic_backup_config", "snapshot_secondary_backup_config"}
	for _, v := range mutableArgs {
		if d.HasChange(v) {
			needChange = true
			break
		}
	}

	if needChange {
		request := cynosdbv20190107.NewModifyBackupConfigRequest()

		request.ClusterId = helper.String(clusterId)

		if v, ok := d.GetOkExists("backup_time_beg"); ok {
			request.BackupTimeBeg = helper.IntUint64(v.(int))
		}

		if v, ok := d.GetOkExists("backup_time_end"); ok {
			request.BackupTimeEnd = helper.IntUint64(v.(int))
		}

		if v, ok := d.GetOkExists("reserve_duration"); ok {
			request.ReserveDuration = helper.IntUint64(v.(int))
		}

		// if v, ok := d.GetOk("backup_freq"); ok {
		// 	backupFreqSet := v.([]interface{})
		// 	for i := range backupFreqSet {
		// 		backupFreq := backupFreqSet[i].(string)
		// 		request.BackupFreq = append(request.BackupFreq, helper.String(backupFreq))
		// 	}
		// }

		// if v, ok := d.GetOk("backup_type"); ok {
		// 	request.BackupType = helper.String(v.(string))
		// }

		if logicBackupConfigMap, ok := helper.InterfacesHeadMap(d, "logic_backup_config"); ok {
			logicBackupConfigInfo := cynosdbv20190107.LogicBackupConfigInfo{}
			if v, ok := logicBackupConfigMap["logic_backup_enable"].(string); ok && v != "" {
				logicBackupConfigInfo.LogicBackupEnable = helper.String(v)
			}
			if *logicBackupConfigInfo.LogicBackupEnable != "OFF" {
				if v, ok := logicBackupConfigMap["logic_backup_time_beg"].(int); ok {
					logicBackupConfigInfo.LogicBackupTimeBeg = helper.IntUint64(v)
				}
				if v, ok := logicBackupConfigMap["logic_backup_time_end"].(int); ok {
					logicBackupConfigInfo.LogicBackupTimeEnd = helper.IntUint64(v)
				}
				if v, ok := logicBackupConfigMap["logic_reserve_duration"].(int); ok {
					logicBackupConfigInfo.LogicReserveDuration = helper.IntUint64(v)
				}
				if v, ok := logicBackupConfigMap["logic_cross_regions_enable"].(string); ok && v != "" {
					logicBackupConfigInfo.LogicCrossRegionsEnable = helper.String(v)
				}
				if v, ok := logicBackupConfigMap["logic_cross_regions"]; ok {
					logicCrossRegionsSet := v.(*schema.Set).List()
					for i := range logicCrossRegionsSet {
						logicCrossRegions := logicCrossRegionsSet[i].(string)
						logicBackupConfigInfo.LogicCrossRegions = append(logicBackupConfigInfo.LogicCrossRegions, helper.String(logicCrossRegions))
					}
				}
			}

			request.LogicBackupConfig = &logicBackupConfigInfo
		}

		if snapshotSecondaryList, ok := d.GetOk("snapshot_secondary_backup_config"); ok {
			snapshotSecondaryArr := snapshotSecondaryList.([]interface{})
			if len(snapshotSecondaryArr) > 0 && snapshotSecondaryArr[0] != nil {
				cfgMap := snapshotSecondaryArr[0].(map[string]interface{})
				snapshotCfg := &cynosdbv20190107.SnapshotBackupConfig{}

				if v, ok := cfgMap["backup_custom_auto_time"].(bool); ok {
					snapshotCfg.BackupCustomAutoTime = helper.Bool(v)
				}

				if v, ok := cfgMap["backup_time_beg"].(int); ok {
					snapshotCfg.BackupTimeBeg = helper.IntUint64(v)
				}

				if v, ok := cfgMap["backup_time_end"].(int); ok {
					snapshotCfg.BackupTimeEnd = helper.IntUint64(v)
				}

				if v, ok := cfgMap["backup_week_days"].([]interface{}); ok && len(v) > 0 {
					for _, day := range v {
						snapshotCfg.BackupWeekDays = append(snapshotCfg.BackupWeekDays, helper.String(day.(string)))
					}
				}

				if v, ok := cfgMap["backup_interval_time"].(int); ok {
					snapshotCfg.BackupIntervalTime = helper.Int64(int64(v))
				}

				if v, ok := cfgMap["reserve_duration"].(int); ok {
					snapshotCfg.ReserveDuration = helper.IntUint64(v)
				}

				if v, ok := cfgMap["backup_trigger_strategy"].(string); ok && v != "" {
					snapshotCfg.BackupTriggerStrategy = helper.String(v)
				}

				if v, ok := cfgMap["auto_copy_vaults"].([]interface{}); ok && len(v) > 0 {
					for _, vaultItem := range v {
						vaultMap := vaultItem.(map[string]interface{})
						vault := &cynosdbv20190107.CreateBackupVaultItem{}
						if vaultId, ok := vaultMap["vault_id"].(string); ok && vaultId != "" {
							vault.VaultId = helper.String(vaultId)
						}
						if vaultRegion, ok := vaultMap["vault_region"].(string); ok && vaultRegion != "" {
							vault.VaultRegion = helper.String(vaultRegion)
						}
						snapshotCfg.AutoCopyVaults = append(snapshotCfg.AutoCopyVaults, vault)
					}
				}

				request.SnapshotSecondaryBackupConfig = snapshotCfg
			}
		}

		reqErr := resource.Retry(tccommon.WriteRetryTimeout, func() *resource.RetryError {
			result, e := meta.(tccommon.ProviderMeta).GetAPIV3Conn().UseCynosdbClient().ModifyBackupConfigWithContext(ctx, request)
			if e != nil {
				return tccommon.RetryError(e)
			} else {
				log.Printf("[DEBUG]%s api[%s] success, request body [%s], response body [%s]\n", logId, request.GetAction(), request.ToJsonString(), result.ToJsonString())
			}
			return nil
		})
		if reqErr != nil {
			log.Printf("[CRITAL]%s update cynosdb backup config failed, reason:%+v", logId, reqErr)
			return reqErr
		}
	}

	return resourceTencentCloudCynosdbBackupConfigRead(d, meta)
}

func resourceTencentCloudCynosdbBackupConfigDelete(d *schema.ResourceData, meta interface{}) error {
	defer tccommon.LogElapsed("resource.tencentcloud_cynosdb_backup_config.delete")()
	defer tccommon.InconsistentCheck(d, meta)()

	return nil
}
