/*
Provides a resource to create a CLS SearchView.

# Example Usage

```hcl

	resource "tencentcloud_cls_search_view_v2" "example" {
	  logset_id     = "xxxxxxxx-xxxx-xxxx-xxxx"
	  logset_region = "ap-guangzhou"
	  view_name     = "my-search-view"
	  view_type     = "log"

	  topics {
	    region    = "ap-guangzhou"
	    logset_id = "xxxxxxxx-xxxx-xxxx-xxxx"
	    topic_id  = "xxxxxxxx-xxxx-xxxx-xxxx"
	  }

	  description    = "example search view"
	  view_id_prefix = "my-prefix"
	}

```

# Import

CLS search view can be imported using the id, e.g.

```
$ terraform import tencentcloud_cls_search_view_v2.example my-prefix-view
```
*/
package cls

import (
	"context"
	"fmt"
	"log"

	"github.com/hashicorp/terraform-plugin-sdk/v2/helper/resource"
	"github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema"
	cls "github.com/tencentcloud/tencentcloud-sdk-go/tencentcloud/cls/v20201016"

	tccommon "github.com/tencentcloudstack/terraform-provider-tencentcloud/tencentcloud/common"
	"github.com/tencentcloudstack/terraform-provider-tencentcloud/tencentcloud/internal/helper"
)

func ResourceTencentCloudClsSearchViewV2() *schema.Resource {
	return &schema.Resource{
		Create: resourceTencentCloudClsSearchViewV2Create,
		Read:   resourceTencentCloudClsSearchViewV2Read,
		Update: resourceTencentCloudClsSearchViewV2Update,
		Delete: resourceTencentCloudClsSearchViewV2Delete,
		Importer: &schema.ResourceImporter{
			State: schema.ImportStatePassthrough,
		},
		Schema: map[string]*schema.Schema{
			"logset_id": {
				Type:        schema.TypeString,
				Required:    true,
				ForceNew:    true,
				Description: "Logset ID that the search view belongs to.",
			},

			"logset_region": {
				Type:        schema.TypeString,
				Required:    true,
				ForceNew:    true,
				Description: "Region of the logset, e.g., ap-guangzhou.",
			},

			"view_name": {
				Type:        schema.TypeString,
				Required:    true,
				Description: "View name, max 255 characters, cannot contain `|` character.",
			},

			"view_type": {
				Type:        schema.TypeString,
				Required:    true,
				Description: "View type. Valid values: `log` (log topic), `metric` (metric topic).",
			},

			"topics": {
				Type:        schema.TypeList,
				Required:    true,
				MaxItems:    10,
				Description: "List of topics included in the search view, max 10 topics.",
				Elem: &schema.Resource{
					Schema: map[string]*schema.Schema{
						"region": {
							Type:        schema.TypeString,
							Required:    true,
							Description: "Region of the topic, e.g., ap-guangzhou.",
						},
						"logset_id": {
							Type:        schema.TypeString,
							Required:    true,
							Description: "Logset ID of the topic.",
						},
						"topic_id": {
							Type:        schema.TypeString,
							Required:    true,
							Description: "Topic ID.",
						},
					},
				},
			},

			"description": {
				Type:        schema.TypeString,
				Optional:    true,
				Description: "Description of the search view.",
			},

			"view_id_prefix": {
				Type:        schema.TypeString,
				Optional:    true,
				ForceNew:    true,
				Description: "Custom view ID prefix. The format is: ^[a-z0-9][a-z0-9_-]{1,61}[a-z0-9]$. The created view ID format is ${ViewIdPrefix}-view.",
			},

			"view_id": {
				Type:        schema.TypeString,
				Computed:    true,
				Description: "View ID, generated by cloud API.",
			},
		},
	}
}

func resourceTencentCloudClsSearchViewV2Create(d *schema.ResourceData, meta interface{}) error {
	defer tccommon.LogElapsed("resource.tencentcloud_cls_search_view_v2.create")()
	defer tccommon.InconsistentCheck(d, meta)()

	var (
		logId    = tccommon.GetLogId(tccommon.ContextNil)
		ctx      = tccommon.NewResourceLifeCycleHandleFuncContext(context.Background(), logId, d, meta)
		request  = cls.NewCreateSearchViewRequest()
		response = cls.NewCreateSearchViewResponse()
		viewId   string
	)

	if v, ok := d.GetOk("logset_id"); ok {
		request.LogsetId = helper.String(v.(string))
	}

	if v, ok := d.GetOk("logset_region"); ok {
		request.LogsetRegion = helper.String(v.(string))
	}

	if v, ok := d.GetOk("view_name"); ok {
		request.ViewName = helper.String(v.(string))
	}

	if v, ok := d.GetOk("view_type"); ok {
		request.ViewType = helper.String(v.(string))
	}

	if v, ok := d.GetOk("topics"); ok {
		for _, item := range v.([]interface{}) {
			topicsMap := item.(map[string]interface{})
			viewSearchTopic := cls.ViewSearchTopic{}
			if v, ok := topicsMap["region"].(string); ok && v != "" {
				viewSearchTopic.Region = helper.String(v)
			}
			if v, ok := topicsMap["logset_id"].(string); ok && v != "" {
				viewSearchTopic.LogsetId = helper.String(v)
			}
			if v, ok := topicsMap["topic_id"].(string); ok && v != "" {
				viewSearchTopic.TopicId = helper.String(v)
			}
			request.Topics = append(request.Topics, &viewSearchTopic)
		}
	}

	if v, ok := d.GetOk("description"); ok {
		request.Description = helper.String(v.(string))
	}

	if v, ok := d.GetOk("view_id_prefix"); ok {
		request.ViewIdPrefix = helper.String(v.(string))
	}

	err := resource.Retry(tccommon.WriteRetryTimeout, func() *resource.RetryError {
		result, e := meta.(tccommon.ProviderMeta).GetAPIV3Conn().UseClsClient().CreateSearchViewWithContext(ctx, request)
		if e != nil {
			return tccommon.RetryError(e)
		} else {
			log.Printf("[DEBUG]%s api[%s] success, request body [%s], response body [%s]\n", logId, request.GetAction(), request.ToJsonString(), result.ToJsonString())
		}

		if result == nil || result.Response == nil {
			return resource.NonRetryableError(fmt.Errorf("Create cls search view failed, Response is nil."))
		}

		response = result
		return nil
	})

	if err != nil {
		log.Printf("[CRITAL]%s create cls search view failed, reason:%+v", logId, err)
		return err
	}

	if response.Response.ViewId == nil {
		return fmt.Errorf("ViewId is nil.")
	}

	viewId = *response.Response.ViewId
	d.SetId(viewId)

	return resourceTencentCloudClsSearchViewV2Read(d, meta)
}

func resourceTencentCloudClsSearchViewV2Read(d *schema.ResourceData, meta interface{}) error {
	defer tccommon.LogElapsed("resource.tencentcloud_cls_search_view_v2.read")()
	defer tccommon.InconsistentCheck(d, meta)()

	var (
		logId   = tccommon.GetLogId(tccommon.ContextNil)
		ctx     = tccommon.NewResourceLifeCycleHandleFuncContext(context.Background(), logId, d, meta)
		service = ClsService{client: meta.(tccommon.ProviderMeta).GetAPIV3Conn()}
		viewId  = d.Id()
	)

	searchView, err := service.DescribeClsSearchViewById(ctx, viewId)
	if err != nil {
		return err
	}

	if searchView == nil {
		d.SetId("")
		log.Printf("[WARN]%s resource `ClsSearchViewV2` [%s] not found, please check if it has been deleted.\n", logId, d.Id())
		return nil
	}

	if searchView.LogsetId != nil {
		_ = d.Set("logset_id", searchView.LogsetId)
	}

	if searchView.LogsetRegion != nil {
		_ = d.Set("logset_region", searchView.LogsetRegion)
	}

	if searchView.ViewName != nil {
		_ = d.Set("view_name", searchView.ViewName)
	}

	if searchView.ViewType != nil {
		_ = d.Set("view_type", searchView.ViewType)
	}

	if searchView.Topics != nil {
		topicsList := make([]map[string]interface{}, 0, len(searchView.Topics))
		for _, topic := range searchView.Topics {
			topicMap := map[string]interface{}{}
			if topic.Region != nil {
				topicMap["region"] = topic.Region
			}
			if topic.LogsetId != nil {
				topicMap["logset_id"] = topic.LogsetId
			}
			if topic.TopicId != nil {
				topicMap["topic_id"] = topic.TopicId
			}
			topicsList = append(topicsList, topicMap)
		}
		_ = d.Set("topics", topicsList)
	}

	if searchView.Description != nil {
		_ = d.Set("description", searchView.Description)
	}

	if searchView.ViewId != nil {
		_ = d.Set("view_id", searchView.ViewId)
	}

	return nil
}

func resourceTencentCloudClsSearchViewV2Update(d *schema.ResourceData, meta interface{}) error {
	defer tccommon.LogElapsed("resource.tencentcloud_cls_search_view_v2.update")()
	defer tccommon.InconsistentCheck(d, meta)()

	var (
		logId = tccommon.GetLogId(tccommon.ContextNil)
		ctx   = tccommon.NewResourceLifeCycleHandleFuncContext(context.Background(), logId, d, meta)
	)

	needChange := false
	mutableArgs := []string{"view_name", "view_type", "topics", "description"}
	for _, v := range mutableArgs {
		if d.HasChange(v) {
			needChange = true
			break
		}
	}

	if needChange {
		request := cls.NewModifySearchViewRequest()

		viewId := d.Id()
		request.ViewId = helper.String(viewId)

		if v, ok := d.GetOk("view_name"); ok {
			request.ViewName = helper.String(v.(string))
		}

		if v, ok := d.GetOk("view_type"); ok {
			request.ViewType = helper.String(v.(string))
		}

		if v, ok := d.GetOk("topics"); ok {
			for _, item := range v.([]interface{}) {
				topicsMap := item.(map[string]interface{})
				viewSearchTopic := cls.ViewSearchTopic{}
				if v, ok := topicsMap["region"].(string); ok && v != "" {
					viewSearchTopic.Region = helper.String(v)
				}
				if v, ok := topicsMap["logset_id"].(string); ok && v != "" {
					viewSearchTopic.LogsetId = helper.String(v)
				}
				if v, ok := topicsMap["topic_id"].(string); ok && v != "" {
					viewSearchTopic.TopicId = helper.String(v)
				}
				request.Topics = append(request.Topics, &viewSearchTopic)
			}
		}

		if v, ok := d.GetOk("description"); ok {
			request.Description = helper.String(v.(string))
		}

		err := resource.Retry(tccommon.WriteRetryTimeout, func() *resource.RetryError {
			result, e := meta.(tccommon.ProviderMeta).GetAPIV3Conn().UseClsClient().ModifySearchViewWithContext(ctx, request)
			if e != nil {
				return tccommon.RetryError(e)
			} else {
				log.Printf("[DEBUG]%s api[%s] success, request body [%s], response body [%s]\n", logId, request.GetAction(), request.ToJsonString(), result.ToJsonString())
			}

			if result == nil || result.Response == nil {
				return resource.NonRetryableError(fmt.Errorf("Modify cls search view failed, Response is nil."))
			}

			return nil
		})

		if err != nil {
			log.Printf("[CRITAL]%s update cls search view failed, reason:%+v", logId, err)
			return err
		}
	}

	return resourceTencentCloudClsSearchViewV2Read(d, meta)
}

func resourceTencentCloudClsSearchViewV2Delete(d *schema.ResourceData, meta interface{}) error {
	defer tccommon.LogElapsed("resource.tencentcloud_cls_search_view_v2.delete")()
	defer tccommon.InconsistentCheck(d, meta)()

	var (
		logId   = tccommon.GetLogId(tccommon.ContextNil)
		ctx     = tccommon.NewResourceLifeCycleHandleFuncContext(context.Background(), logId, d, meta)
		service = ClsService{client: meta.(tccommon.ProviderMeta).GetAPIV3Conn()}
		viewId  = d.Id()
	)

	err := service.DeleteClsSearchViewById(ctx, viewId)
	if err != nil {
		return err
	}

	return nil
}
