// Code generated by iacg; DO NOT EDIT.
package wedata

import (
	"context"

	"github.com/hashicorp/terraform-plugin-sdk/v2/helper/resource"
	"github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema"
	wedatav20250806 "github.com/tencentcloud/tencentcloud-sdk-go/tencentcloud/wedata/v20250806"
	tccommon "github.com/tencentcloudstack/terraform-provider-tencentcloud/tencentcloud/common"
	"github.com/tencentcloudstack/terraform-provider-tencentcloud/tencentcloud/internal/helper"
)

func DataSourceTencentCloudWedataTriggerTaskVersions() *schema.Resource {
	return &schema.Resource{
		Read: dataSourceTencentCloudWedataTriggerTaskVersionsRead,
		Schema: map[string]*schema.Schema{
			"project_id": {
				Type:        schema.TypeString,
				Required:    true,
				Description: "项目 ID",
			},

			"task_id": {
				Type:        schema.TypeString,
				Required:    true,
				Description: "任务 ID",
			},

			"task_version_type": {
				Type:        schema.TypeString,
				Optional:    true,
				Description: "Saved 版本: SAVE; Submitted 版本: SUBMIT. 默认为 SAVE。",
			},

			"data": {
				Type:        schema.TypeList,
				Computed:    true,
				Description: "版本 列表。",
				Elem: &schema.Resource{
					Schema: map[string]*schema.Schema{
						"items": {
							Type:        schema.TypeList,
							Required:    true,
							Description: "Record 列表。",
							Elem: &schema.Resource{
								Schema: map[string]*schema.Schema{
									"create_time": {
										Type:        schema.TypeString,
										Required:    true,
										Description: "Save 时间。",
									},
									"version_num": {
										Type:        schema.TypeString,
										Required:    true,
										Description: "版本 数量。",
									},
									"create_user_uin": {
										Type:        schema.TypeString,
										Required:    true,
										Description: "创建者",
									},
									"version_id": {
										Type:        schema.TypeString,
										Required:    true,
										Description: "Saved 版本 ID。",
									},
									"version_remark": {
										Type:        schema.TypeString,
										Required:    true,
										Description: "版本 描述",
									},
									"approve_status": {
										Type:        schema.TypeString,
										Required:    true,
										Description: "Approval 状态 (仅 对于 submitted versions)。",
									},
									"status": {
										Type:        schema.TypeString,
										Required:    true,
										Description: "Production 状态 (仅 对于 submitted versions)。",
									},
									"approve_user_uin": {
										Type:        schema.TypeString,
										Required:    true,
										Description: "Approver (仅 对于 submitted versions)。",
									},
								},
							},
						},
					},
				},
			},

			"result_output_file": {
				Type:        schema.TypeString,
				Optional:    true,
				Description: "用于保存结果。",
			},
		},
	}
}

func dataSourceTencentCloudWedataTriggerTaskVersionsRead(d *schema.ResourceData, meta interface{}) error {
	defer tccommon.LogElapsed("data_source.tencentcloud_wedata_trigger_task_versions.read")()
	defer tccommon.InconsistentCheck(d, meta)()

	logId := tccommon.GetLogId(nil)
	ctx := tccommon.NewResourceLifeCycleHandleFuncContext(context.Background(), logId, d, meta)

	service := WedataService{client: meta.(tccommon.ProviderMeta).GetAPIV3Conn()}

	paramMap := make(map[string]interface{})
	var projectId string
	var taskId string
	if v, ok := d.GetOk("project_id"); ok {
		paramMap["ProjectId"] = helper.String(v.(string))
		projectId = v.(string)
	}

	if v, ok := d.GetOk("task_id"); ok {
		paramMap["TaskId"] = helper.String(v.(string))
		taskId = v.(string)
	}

	if v, ok := d.GetOk("task_version_type"); ok {
		paramMap["TaskVersionType"] = helper.String(v.(string))
	}

	var respData []*wedatav20250806.TriggerTaskVersion
	reqErr := resource.Retry(tccommon.ReadRetryTimeout, func() *resource.RetryError {
		result, e := service.DescribeWedataTriggerTaskVersionsByFilter(ctx, paramMap)
		if e != nil {
			return tccommon.RetryError(e)
		}
		respData = result
		return nil
	})
	if reqErr != nil {
		return reqErr
	}

	ids := []string{projectId, taskId}
	dataMap := map[string]interface{}{}

	if respData != nil {
		itemsList := make([]map[string]interface{}, 0, len(respData))
		for _, items := range respData {
			itemsMap := map[string]interface{}{}

			if items.CreateTime != nil {
				itemsMap["create_time"] = items.CreateTime
			}

			if items.VersionNum != nil {
				itemsMap["version_num"] = items.VersionNum
			}

			if items.CreateUserUin != nil {
				itemsMap["create_user_uin"] = items.CreateUserUin
			}

			if items.VersionId != nil {
				itemsMap["version_id"] = items.VersionId
			}

			if items.VersionRemark != nil {
				itemsMap["version_remark"] = items.VersionRemark
			}

			if items.ApproveStatus != nil {
				itemsMap["approve_status"] = items.ApproveStatus
			}

			if items.Status != nil {
				itemsMap["status"] = items.Status
			}

			if items.ApproveUserUin != nil {
				itemsMap["approve_user_uin"] = items.ApproveUserUin
			}

			itemsList = append(itemsList, itemsMap)
			if items.VersionId != nil {
				ids = append(ids, *items.VersionId)
			}
		}

		dataMap["items"] = itemsList

		_ = d.Set("data", []interface{}{dataMap})
	}

	d.SetId(helper.DataResourceIdsHash(ids))

	output, ok := d.GetOk("result_output_file")
	if ok && output.(string) != "" {
		if e := tccommon.WriteToFile(output.(string), dataMap); e != nil {
			return e
		}
	}

	return nil
}
