// Code generated by iacg; DO NOT EDIT.
package wedata

import (
	"context"
	"strconv"

	"github.com/hashicorp/terraform-plugin-sdk/v2/helper/resource"
	"github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema"
	wedatav20250806 "github.com/tencentcloud/tencentcloud-sdk-go/tencentcloud/wedata/v20250806"
	tccommon "github.com/tencentcloudstack/terraform-provider-tencentcloud/tencentcloud/common"
	"github.com/tencentcloudstack/terraform-provider-tencentcloud/tencentcloud/internal/helper"
)

func DataSourceTencentCloudWedataQualityRuleTemplates() *schema.Resource {
	return &schema.Resource{
		Read: dataSourceTencentCloudWedataQualityRuleTemplatesRead,
		Schema: map[string]*schema.Schema{
			"project_id": {
				Type:        schema.TypeString,
				Required:    true,
				Description: "Workspace ID。",
			},

			"order_fields": {
				Type:        schema.TypeList,
				Optional:    true,
				Description: "General sorting，支持 sorting 字段: `CitationCount` - 排序方式 citation count; `UpdateTime` - 排序方式 更新时间. Sort direction: `1` - Ascending (ASC); `2` - Descending (DESC)。",
				Elem: &schema.Resource{
					Schema: map[string]*schema.Schema{
						"name": {
							Type:        schema.TypeString,
							Required:    true,
							Description: "排序字段 名称",
						},
						"direction": {
							Type:        schema.TypeString,
							Required:    true,
							Description: "Sort direction: ASC|DESC。",
						},
					},
				},
			},

			"filters": {
				Type:        schema.TypeList,
				Optional:    true,
				Description: "General 过滤器 conditions 1. `ID` 描述: 模板 ID，值: Unique identifier 的 template; 2. `Keyword` 描述: Keyword search，支持 fuzzy search 的 template names，值: String; 3. `类型` 描述: 模板 类型，值: `1` - System template; `2` - Custom template; 支持 多个 值 (OR relationship); 4. `QualityDim` 描述: Quality detection dimension，值: `1` - Accuracy; `2` - Uniqueness; `3` - Completeness; `4` - Consistency; `5` - Timeliness; `6` - Validity; 支持 多个 值 (OR relationship); 5. `SourceObjectType` 描述: 来源 数据 对象 类型 applicable 到 规则，值: `1` - Constant; `2` - Offline 表 级别; `3` - Offline 字段 级别; `4` - Database 级别; 支持 多个 值 (OR relationship); 6. `SourceEngineTypes` 描述: 来源 数据 引擎 类型 applicable 到 template，值: `1` - MySQL; `2` - Hive; `4` - Spark; `8` - Livy; `16` - DLC; `32` - Gbase; `64` - TCHouse-P; `128` - Doris; `256` - TCHouse-D; `512` - EMR_StarRocks; `1024` - TCHouse-X; 支持 多个 值 (OR relationship)。",
				Elem: &schema.Resource{
					Schema: map[string]*schema.Schema{
						"name": {
							Type:        schema.TypeString,
							Optional:    true,
							Description: "过滤字段名称",
						},
						"values": {
							Type:        schema.TypeSet,
							Optional:    true,
							Description: "过滤值 列表。",
							Elem: &schema.Schema{
								Type: schema.TypeString,
							},
						},
					},
				},
			},

			"data": {
				Type:        schema.TypeList,
				Computed:    true,
				Description: "结果",
				Elem: &schema.Resource{
					Schema: map[string]*schema.Schema{
						"total_count": {
							Type:        schema.TypeInt,
							Required:    true,
							Description: "总数",
						},
						"items": {
							Type:        schema.TypeList,
							Required:    true,
							Description: "模板 列表。",
							Elem: &schema.Resource{
								Schema: map[string]*schema.Schema{
									"rule_template_id": {
										Type:        schema.TypeInt,
										Required:    true,
										Description: "Rule 模板 ID",
									},
									"name": {
										Type:        schema.TypeString,
										Required:    true,
										Description: "Rule 模板名称",
									},
									"description": {
										Type:        schema.TypeString,
										Required:    true,
										Description: "Rule 模板描述",
									},
									"type": {
										Type:        schema.TypeInt,
										Required:    true,
										Description: "模板 类型 (1: System template，2: Custom template)。",
									},
									"source_object_type": {
										Type:        schema.TypeInt,
										Required:    true,
										Description: "来源 数据 对象 类型 applicable 到 规则 (1: Constant，2: Offline 表 级别，3: Offline 字段 级别)。",
									},
									"source_object_data_type": {
										Type:        schema.TypeInt,
										Required:    true,
										Description: "来源 数据 对象 数据 类型 applicable 到 规则 (1: Numeric，2: String)。",
									},
									"source_content": {
										Type:        schema.TypeString,
										Required:    true,
										Description: "Rule template 来源 内容，differentiated 通过 引擎，JSON structure。",
									},
									"source_engine_types": {
										Type:        schema.TypeSet,
										Required:    true,
										Description: "来源 数据 applicable types。",
										Elem: &schema.Schema{
											Type: schema.TypeInt,
										},
									},
									"quality_dim": {
										Type:        schema.TypeInt,
										Required:    true,
										Description: "Quality dimension 的 规则 (1: Accuracy，2: Uniqueness，3: Completeness，4: Consistency，5: Timeliness，6: Validity)。",
									},
									"compare_type": {
										Type:        schema.TypeInt,
										Required:    true,
										Description: "比较类型 支持 通过 规则 (1: Fixed 值 comparison，greater 比，less 比，greater 比 或 equal 到，etc. 2: Fluctuation 值 comparison，absolute 值，increase，decrease)。",
									},
									"citation_count": {
										Type:        schema.TypeInt,
										Required:    true,
										Description: "Citation count。",
									},
									"user_id": {
										Type:        schema.TypeInt,
										Required:    true,
										Description: "创建者 用户 ID。",
									},
									"user_name": {
										Type:        schema.TypeString,
										Required:    true,
										Description: "创建者 用户名",
									},
									"update_time": {
										Type:        schema.TypeString,
										Required:    true,
										Description: "更新时间 yyyy-MM-dd HH:mm:ss。",
									},
									"where_flag": {
										Type:        schema.TypeBool,
										Required:    true,
										Description: "是否add 其中 参数。",
									},
									"multi_source_flag": {
										Type:        schema.TypeBool,
										Required:    true,
										Description: "是否associate 多个 数据库 tables。",
									},
									"sql_expression": {
										Type:        schema.TypeString,
										Required:    true,
										Description: "Custom template SQL expression。",
									},
									"sub_quality_dim": {
										Type:        schema.TypeInt,
										Required:    true,
										Description: "模板 sub-dimension，0. Parent dimension 类型，1. Consistency: Enumeration 范围 consistency，2. Consistency: Numeric 范围 consistency，3. Consistency: Field 数据 correlation。",
									},
									"resolved_sql_expression": {
										Type:        schema.TypeList,
										Required:    true,
										MaxItems:    1,
										Description: "SQL expression parsing 对象。",
										Elem: &schema.Resource{
											Schema: map[string]*schema.Schema{
												"table_expressions": {
													Type:        schema.TypeList,
													Required:    true,
													Description: "SQL expression 表 names。",
													Elem: &schema.Resource{
														Schema: map[string]*schema.Schema{
															"table_expression": {
																Type:        schema.TypeString,
																Required:    true,
																Description: "SQL expression 表 名称",
															},
															"column_expression": {
																Type:        schema.TypeSet,
																Required:    true,
																Description: "SQL expression 字段 names。",
																Elem: &schema.Schema{
																	Type: schema.TypeString,
																},
															},
														},
													},
												},
												"param_expressions": {
													Type:        schema.TypeSet,
													Required:    true,
													Description: "SQL expression 字段 names。",
													Elem: &schema.Schema{
														Type: schema.TypeString,
													},
												},
												"system_template_expressions": {
													Type:        schema.TypeSet,
													Required:    true,
													Description: "Placeholder collection 在 系统 template SQL 对于 new model detection。",
													Elem: &schema.Schema{
														Type: schema.TypeString,
													},
												},
											},
										},
									},
									"datasource_types": {
										Type:        schema.TypeSet,
										Required:    true,
										Description: "Supported 数据 来源 types。",
										Elem: &schema.Schema{
											Type: schema.TypeInt,
										},
									},
									"user_id_str": {
										Type:        schema.TypeString,
										Required:    true,
										Description: "创建者 用户 ID 字符串。",
									},
								},
							},
						},
					},
				},
			},

			"result_output_file": {
				Type:        schema.TypeString,
				Optional:    true,
				Description: "用于保存结果。",
			},
		},
	}
}

func dataSourceTencentCloudWedataQualityRuleTemplatesRead(d *schema.ResourceData, meta interface{}) error {
	defer tccommon.LogElapsed("data_source.tencentcloud_wedata_quality_rule_templates.read")()
	defer tccommon.InconsistentCheck(d, meta)()

	logId := tccommon.GetLogId(nil)
	ctx := tccommon.NewResourceLifeCycleHandleFuncContext(context.Background(), logId, d, meta)

	service := WedataService{client: meta.(tccommon.ProviderMeta).GetAPIV3Conn()}

	paramMap := make(map[string]interface{})
	if v, ok := d.GetOk("project_id"); ok {
		paramMap["ProjectId"] = helper.String(v.(string))
	}

	if v, ok := d.GetOk("order_fields"); ok {
		orderFieldsSet := v.([]interface{})
		tmpSet := make([]*wedatav20250806.OrderField, 0, len(orderFieldsSet))
		for _, item := range orderFieldsSet {
			orderFieldsMap := item.(map[string]interface{})
			orderField := wedatav20250806.OrderField{}
			if v, ok := orderFieldsMap["name"].(string); ok && v != "" {
				orderField.Name = helper.String(v)
			}
			if v, ok := orderFieldsMap["direction"].(string); ok && v != "" {
				orderField.Direction = helper.String(v)
			}
			tmpSet = append(tmpSet, &orderField)
		}
		paramMap["OrderFields"] = tmpSet
	}

	if v, ok := d.GetOk("filters"); ok {
		filtersSet := v.([]interface{})
		tmpSet := make([]*wedatav20250806.Filter, 0, len(filtersSet))
		for _, item := range filtersSet {
			filtersMap := item.(map[string]interface{})
			filter := wedatav20250806.Filter{}
			if v, ok := filtersMap["name"].(string); ok && v != "" {
				filter.Name = helper.String(v)
			}
			if v, ok := filtersMap["values"]; ok {
				valuesSet := v.(*schema.Set).List()
				for i := range valuesSet {
					values := valuesSet[i].(string)
					filter.Values = append(filter.Values, helper.String(values))
				}
			}
			tmpSet = append(tmpSet, &filter)
		}
		paramMap["Filters"] = tmpSet
	}

	var respData *wedatav20250806.ListQualityRuleTemplatesResponseParams
	reqErr := resource.Retry(tccommon.ReadRetryTimeout, func() *resource.RetryError {
		result, e := service.DescribeWedataQualityRuleTemplatesByFilter(ctx, paramMap)
		if e != nil {
			return tccommon.RetryError(e)
		}
		respData = result
		return nil
	})
	if reqErr != nil {
		return reqErr
	}

	dataMap := map[string]interface{}{}
	ids := []string{}

	if respData.Data != nil {
		if respData.Data.TotalCount != nil {
			dataMap["total_count"] = respData.Data.TotalCount
		}

		itemsList := make([]map[string]interface{}, 0, len(respData.Data.Items))
		if respData.Data.Items != nil {
			for _, items := range respData.Data.Items {
				itemsMap := map[string]interface{}{}

				if items.RuleTemplateId != nil {
					itemsMap["rule_template_id"] = items.RuleTemplateId
					ids = append(ids, strconv.FormatUint(*items.RuleTemplateId, 10))
				}

				if items.Name != nil {
					itemsMap["name"] = items.Name
				}

				if items.Description != nil {
					itemsMap["description"] = items.Description
				}

				if items.Type != nil {
					itemsMap["type"] = items.Type
				}

				if items.SourceObjectType != nil {
					itemsMap["source_object_type"] = items.SourceObjectType
				}

				if items.SourceObjectDataType != nil {
					itemsMap["source_object_data_type"] = items.SourceObjectDataType
				}

				if items.SourceContent != nil {
					itemsMap["source_content"] = items.SourceContent
				}

				if items.SourceEngineTypes != nil {
					itemsMap["source_engine_types"] = items.SourceEngineTypes
				}

				if items.QualityDim != nil {
					itemsMap["quality_dim"] = items.QualityDim
				}

				if items.CompareType != nil {
					itemsMap["compare_type"] = items.CompareType
				}

				if items.CitationCount != nil {
					itemsMap["citation_count"] = items.CitationCount
				}

				if items.UserId != nil {
					itemsMap["user_id"] = items.UserId
				}

				if items.UserName != nil {
					itemsMap["user_name"] = items.UserName
				}

				if items.UpdateTime != nil {
					itemsMap["update_time"] = items.UpdateTime
				}

				if items.WhereFlag != nil {
					itemsMap["where_flag"] = items.WhereFlag
				}

				if items.MultiSourceFlag != nil {
					itemsMap["multi_source_flag"] = items.MultiSourceFlag
				}

				if items.SqlExpression != nil {
					itemsMap["sql_expression"] = items.SqlExpression
				}

				if items.SubQualityDim != nil {
					itemsMap["sub_quality_dim"] = items.SubQualityDim
				}

				resolvedSqlExpressionMap := map[string]interface{}{}

				if items.ResolvedSqlExpression != nil {
					tableExpressionsList := make([]map[string]interface{}, 0, len(items.ResolvedSqlExpression.TableExpressions))
					if items.ResolvedSqlExpression.TableExpressions != nil {
						for _, tableExpressions := range items.ResolvedSqlExpression.TableExpressions {
							tableExpressionsMap := map[string]interface{}{}

							if tableExpressions.TableExpression != nil {
								tableExpressionsMap["table_expression"] = tableExpressions.TableExpression
							}

							if tableExpressions.ColumnExpression != nil {
								tableExpressionsMap["column_expression"] = tableExpressions.ColumnExpression
							}

							tableExpressionsList = append(tableExpressionsList, tableExpressionsMap)
						}

						resolvedSqlExpressionMap["table_expressions"] = tableExpressionsList
					}
					if items.ResolvedSqlExpression.ParamExpressions != nil {
						resolvedSqlExpressionMap["param_expressions"] = items.ResolvedSqlExpression.ParamExpressions
					}

					if items.ResolvedSqlExpression.SystemTemplateExpressions != nil {
						resolvedSqlExpressionMap["system_template_expressions"] = items.ResolvedSqlExpression.SystemTemplateExpressions
					}

					itemsMap["resolved_sql_expression"] = []interface{}{resolvedSqlExpressionMap}
				}

				if items.DatasourceTypes != nil {
					itemsMap["datasource_types"] = items.DatasourceTypes
				}

				if items.UserIdStr != nil {
					itemsMap["user_id_str"] = items.UserIdStr
				}

				itemsList = append(itemsList, itemsMap)
			}

			dataMap["items"] = itemsList
		}
		_ = d.Set("data", []interface{}{dataMap})
	}

	d.SetId(helper.DataResourceIdsHash(ids))

	output, ok := d.GetOk("result_output_file")
	if ok && output.(string) != "" {
		if e := tccommon.WriteToFile(output.(string), dataMap); e != nil {
			return e
		}
	}

	return nil
}
