// Code generated by iacg; DO NOT EDIT.
package wedata

import (
	"context"

	"github.com/hashicorp/terraform-plugin-sdk/v2/helper/resource"
	"github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema"
	wedatav20250806 "github.com/tencentcloud/tencentcloud-sdk-go/tencentcloud/wedata/v20250806"
	tccommon "github.com/tencentcloudstack/terraform-provider-tencentcloud/tencentcloud/common"
	"github.com/tencentcloudstack/terraform-provider-tencentcloud/tencentcloud/internal/helper"
)

func DataSourceTencentCloudWedataTriggerTaskRun() *schema.Resource {
	return &schema.Resource{
		Read: dataSourceTencentCloudWedataTriggerTaskRunRead,
		Schema: map[string]*schema.Schema{
			"project_id": {
				Type:        schema.TypeString,
				Required:    true,
				Description: "Workspace ID。",
			},

			"task_execution_id": {
				Type:        schema.TypeString,
				Required:    true,
				Description: "Task execution ID。",
			},

			"data": {
				Type:        schema.TypeList,
				Computed:    true,
				Description: "Workflow task execution list pagination 结果",
				Elem: &schema.Resource{
					Schema: map[string]*schema.Schema{
						"execution_id": {
							Type:        schema.TypeString,
							Required:    true,
							Description: "Task execution ID。",
						},
						"execution_state": {
							Type:        schema.TypeString,
							Required:    true,
							Description: "Execution state. 有效值：`FAILED` (execution failed)，`SUCCESS` (execution successful)，`PENDING` (waiting)，`SKIP` (skipped execution)，`RUNNING` (executing)。",
						},
						"project_id": {
							Type:        schema.TypeString,
							Required:    true,
							Description: "项目 ID",
						},
						"workflow_id": {
							Type:        schema.TypeString,
							Required:    true,
							Description: "Workflow ID。",
						},
						"workflow_execution_id": {
							Type:        schema.TypeString,
							Required:    true,
							Description: "Workflow execution ID。",
						},
						"task_id": {
							Type:        schema.TypeString,
							Required:    true,
							Description: "任务 ID",
						},
						"task_type": {
							Type:        schema.TypeString,
							Required:    true,
							Description: "Task 类型",
						},
						"task_version_id": {
							Type:        schema.TypeString,
							Required:    true,
							Description: "Task 版本 ID。",
						},
						"trigger_type": {
							Type:        schema.TypeString,
							Required:    true,
							Description: "Trigger 类型",
						},
						"wait_time": {
							Type:        schema.TypeString,
							Required:    true,
							Description: "Wait time （秒）。",
						},
						"resource_group": {
							Type:        schema.TypeString,
							Required:    true,
							Description: "Resource group。",
						},
						"error_code": {
							Type:        schema.TypeString,
							Required:    true,
							Description: "错误码",
						},
						"execute_user_uin": {
							Type:        schema.TypeString,
							Required:    true,
							Description: "Execute 用户 UIN。",
						},
						"creater_uin": {
							Type:        schema.TypeString,
							Required:    true,
							Description: "创建者 UIN。",
						},
						"job_id": {
							Type:        schema.TypeString,
							Required:    true,
							Description: "Execution platform job ID。",
						},
						"create_time": {
							Type:        schema.TypeString,
							Required:    true,
							Description: "Create 时间戳。",
						},
						"update_time": {
							Type:        schema.TypeString,
							Required:    true,
							Description: "Update 时间戳。",
						},
						"dependence_finished_time": {
							Type:        schema.TypeString,
							Required:    true,
							Description: "Dependency task completion time。",
						},
						"queue_start_time": {
							Type:        schema.TypeString,
							Required:    true,
							Description: "Task queue 开始时间。",
						},
						"pending_start_time": {
							Type:        schema.TypeString,
							Required:    true,
							Description: "Pending 开始时间。",
						},
						"execution_start_time": {
							Type:        schema.TypeString,
							Required:    true,
							Description: "Execution 开始时间。",
						},
						"execution_end_time": {
							Type:        schema.TypeString,
							Required:    true,
							Description: "Execution 结束时间。",
						},
						"queue_cost_time": {
							Type:        schema.TypeString,
							Required:    true,
							Description: "Queue cost time。",
						},
						"execution_time": {
							Type:        schema.TypeString,
							Required:    true,
							Description: "执行时间。",
						},
						"all_cost_time": {
							Type:        schema.TypeString,
							Required:    true,
							Description: "Total cost time。",
						},
						"time_zone": {
							Type:        schema.TypeString,
							Required:    true,
							Description: "时区。",
						},
						"depend_on_list": {
							Type:        schema.TypeSet,
							Required:    true,
							Description: "Dependent upstream task ID list。",
							Elem: &schema.Schema{
								Type: schema.TypeString,
							},
						},
						"run_params": {
							Type:        schema.TypeString,
							Required:    true,
							Description: "Run parameters。",
						},
						"task_type_extensions": {
							Type:        schema.TypeString,
							Required:    true,
							Description: "Task 类型 extensions including script 路径",
						},
						"retry_times": {
							Type:        schema.TypeInt,
							Required:    true,
							Description: "重试次数 0 means first execution。",
						},
						"left_coordinate": {
							Type:        schema.TypeFloat,
							Required:    true,
							Description: "Left coordinate。",
						},
						"top_coordinate": {
							Type:        schema.TypeFloat,
							Required:    true,
							Description: "Top coordinate。",
						},
						"resource_group_id": {
							Type:        schema.TypeString,
							Required:    true,
							Description: "Resource 组 ID",
						},
						"error_code_str": {
							Type:        schema.TypeString,
							Required:    true,
							Description: "错误码 描述",
						},
						"create_uin": {
							Type:        schema.TypeString,
							Required:    true,
							Description: "创建者 UIN。",
						},
						"issue_time": {
							Type:        schema.TypeString,
							Required:    true,
							Description: "Issue time to execution platform。",
						},
						"task_name": {
							Type:        schema.TypeString,
							Required:    true,
							Description: "Task 名称",
						},
						"workflow_name": {
							Type:        schema.TypeString,
							Required:    true,
							Description: "Workflow 名称",
						},
						"execute_user_name": {
							Type:        schema.TypeString,
							Required:    true,
							Description: "Execute 用户 名称",
						},
						"rerun_times": {
							Type:        schema.TypeInt,
							Required:    true,
							Description: "Rerun times。",
						},
						"is_latest_execution": {
							Type:        schema.TypeBool,
							Required:    true,
							Description: "是否为the latest execution。",
						},
						"task_execution_state": {
							Type:        schema.TypeString,
							Required:    true,
							Description: "Task execution state。",
						},
						"cycle_type": {
							Type:        schema.TypeString,
							Required:    true,
							Description: "Cycle 类型",
						},
						"user_name_in_charge": {
							Type:        schema.TypeString,
							Required:    true,
							Description: "用户 名称 in charge。",
						},
						"user_uin_in_charge": {
							Type:        schema.TypeString,
							Required:    true,
							Description: "用户 UIN in charge。",
						},
						"resource_group_name": {
							Type:        schema.TypeString,
							Required:    true,
							Description: "Resource 组名称",
						},
						"timezone": {
							Type:        schema.TypeString,
							Required:    true,
							Description: "Timezone。",
						},
						"folder_id": {
							Type:        schema.TypeString,
							Required:    true,
							Description: "Folder ID。",
						},
						"folder_name": {
							Type:        schema.TypeString,
							Required:    true,
							Description: "Folder 名称",
						},
						"project_name": {
							Type:        schema.TypeString,
							Required:    true,
							Description: "项目名称",
						},
						"task_type_id": {
							Type:        schema.TypeInt,
							Required:    true,
							Description: "Task 类型 ID。",
						},
						"workflow_params": {
							Type:        schema.TypeString,
							Required:    true,
							Description: "Workflow parameters。",
						},
						"support_rerun": {
							Type:        schema.TypeBool,
							Required:    true,
							Description: "Whether support rerun。",
						},
						"workflow_execution_state": {
							Type:        schema.TypeString,
							Required:    true,
							Description: "Workflow execution state。",
						},
						"execution_result": {
							Type:        schema.TypeString,
							Required:    true,
							Description: "Task execution 结果",
						},
					},
				},
			},

			"result_output_file": {
				Type:        schema.TypeString,
				Optional:    true,
				Description: "用于保存结果。",
			},
		},
	}
}

func dataSourceTencentCloudWedataTriggerTaskRunRead(d *schema.ResourceData, meta interface{}) error {
	defer tccommon.LogElapsed("data_source.tencentcloud_wedata_trigger_task_run.read")()
	defer tccommon.InconsistentCheck(d, meta)()

	logId := tccommon.GetLogId(nil)
	ctx := tccommon.NewResourceLifeCycleHandleFuncContext(context.Background(), logId, d, meta)

	service := WedataService{client: meta.(tccommon.ProviderMeta).GetAPIV3Conn()}

	var projectId, taskExecutionId string
	paramMap := make(map[string]interface{})
	if v, ok := d.GetOk("project_id"); ok {
		projectId = v.(string)
		paramMap["ProjectId"] = helper.String(v.(string))
	}

	if v, ok := d.GetOk("task_execution_id"); ok {
		taskExecutionId = v.(string)
		paramMap["TaskExecutionId"] = helper.String(v.(string))
	}

	var respData *wedatav20250806.GetTriggerTaskRunResponseParams
	reqErr := resource.Retry(tccommon.ReadRetryTimeout, func() *resource.RetryError {
		result, e := service.DescribeWedataTriggerTaskRunByFilter(ctx, paramMap)
		if e != nil {
			return tccommon.RetryError(e)
		}
		respData = result
		return nil
	})
	if reqErr != nil {
		return reqErr
	}

	dataMap := map[string]interface{}{}

	if respData.Data != nil {
		if respData.Data.ExecutionId != nil {
			dataMap["execution_id"] = respData.Data.ExecutionId
		}

		if respData.Data.ExecutionState != nil {
			dataMap["execution_state"] = respData.Data.ExecutionState
		}

		if respData.Data.ProjectId != nil {
			dataMap["project_id"] = respData.Data.ProjectId
		}

		if respData.Data.WorkflowId != nil {
			dataMap["workflow_id"] = respData.Data.WorkflowId
		}

		if respData.Data.WorkflowExecutionId != nil {
			dataMap["workflow_execution_id"] = respData.Data.WorkflowExecutionId
		}

		if respData.Data.TaskId != nil {
			dataMap["task_id"] = respData.Data.TaskId
		}

		if respData.Data.TaskType != nil {
			dataMap["task_type"] = respData.Data.TaskType
		}

		if respData.Data.TaskVersionId != nil {
			dataMap["task_version_id"] = respData.Data.TaskVersionId
		}

		if respData.Data.TriggerType != nil {
			dataMap["trigger_type"] = respData.Data.TriggerType
		}

		if respData.Data.WaitTime != nil {
			dataMap["wait_time"] = respData.Data.WaitTime
		}

		if respData.Data.ResourceGroup != nil {
			dataMap["resource_group"] = respData.Data.ResourceGroup
		}

		if respData.Data.ErrorCode != nil {
			dataMap["error_code"] = respData.Data.ErrorCode
		}

		if respData.Data.ExecuteUserUin != nil {
			dataMap["execute_user_uin"] = respData.Data.ExecuteUserUin
		}

		if respData.Data.CreaterUin != nil {
			dataMap["creater_uin"] = respData.Data.CreaterUin
		}

		if respData.Data.JobId != nil {
			dataMap["job_id"] = respData.Data.JobId
		}

		if respData.Data.CreateTime != nil {
			dataMap["create_time"] = respData.Data.CreateTime
		}

		if respData.Data.UpdateTime != nil {
			dataMap["update_time"] = respData.Data.UpdateTime
		}

		if respData.Data.DependenceFinishedTime != nil {
			dataMap["dependence_finished_time"] = respData.Data.DependenceFinishedTime
		}

		if respData.Data.QueueStartTime != nil {
			dataMap["queue_start_time"] = respData.Data.QueueStartTime
		}

		if respData.Data.PendingStartTime != nil {
			dataMap["pending_start_time"] = respData.Data.PendingStartTime
		}

		if respData.Data.ExecutionStartTime != nil {
			dataMap["execution_start_time"] = respData.Data.ExecutionStartTime
		}

		if respData.Data.ExecutionEndTime != nil {
			dataMap["execution_end_time"] = respData.Data.ExecutionEndTime
		}

		if respData.Data.QueueCostTime != nil {
			dataMap["queue_cost_time"] = respData.Data.QueueCostTime
		}

		if respData.Data.ExecutionTime != nil {
			dataMap["execution_time"] = respData.Data.ExecutionTime
		}

		if respData.Data.AllCostTime != nil {
			dataMap["all_cost_time"] = respData.Data.AllCostTime
		}

		if respData.Data.TimeZone != nil {
			dataMap["time_zone"] = respData.Data.TimeZone
		}

		if respData.Data.DependOnList != nil {
			dataMap["depend_on_list"] = respData.Data.DependOnList
		}

		if respData.Data.RunParams != nil {
			dataMap["run_params"] = respData.Data.RunParams
		}

		if respData.Data.TaskTypeExtensions != nil {
			dataMap["task_type_extensions"] = respData.Data.TaskTypeExtensions
		}

		if respData.Data.RetryTimes != nil {
			dataMap["retry_times"] = respData.Data.RetryTimes
		}

		if respData.Data.LeftCoordinate != nil {
			dataMap["left_coordinate"] = respData.Data.LeftCoordinate
		}

		if respData.Data.TopCoordinate != nil {
			dataMap["top_coordinate"] = respData.Data.TopCoordinate
		}

		if respData.Data.ResourceGroupId != nil {
			dataMap["resource_group_id"] = respData.Data.ResourceGroupId
		}

		if respData.Data.ErrorCodeStr != nil {
			dataMap["error_code_str"] = respData.Data.ErrorCodeStr
		}

		if respData.Data.CreateUin != nil {
			dataMap["create_uin"] = respData.Data.CreateUin
		}

		if respData.Data.IssueTime != nil {
			dataMap["issue_time"] = respData.Data.IssueTime
		}

		if respData.Data.TaskName != nil {
			dataMap["task_name"] = respData.Data.TaskName
		}

		if respData.Data.WorkflowName != nil {
			dataMap["workflow_name"] = respData.Data.WorkflowName
		}

		if respData.Data.ExecuteUserName != nil {
			dataMap["execute_user_name"] = respData.Data.ExecuteUserName
		}

		if respData.Data.RerunTimes != nil {
			dataMap["rerun_times"] = respData.Data.RerunTimes
		}

		if respData.Data.IsLatestExecution != nil {
			dataMap["is_latest_execution"] = respData.Data.IsLatestExecution
		}

		if respData.Data.TaskExecutionState != nil {
			dataMap["task_execution_state"] = respData.Data.TaskExecutionState
		}

		if respData.Data.CycleType != nil {
			dataMap["cycle_type"] = respData.Data.CycleType
		}

		if respData.Data.UserNameInCharge != nil {
			dataMap["user_name_in_charge"] = respData.Data.UserNameInCharge
		}

		if respData.Data.UserUinInCharge != nil {
			dataMap["user_uin_in_charge"] = respData.Data.UserUinInCharge
		}

		if respData.Data.ResourceGroupName != nil {
			dataMap["resource_group_name"] = respData.Data.ResourceGroupName
		}

		if respData.Data.Timezone != nil {
			dataMap["timezone"] = respData.Data.Timezone
		}

		if respData.Data.FolderId != nil {
			dataMap["folder_id"] = respData.Data.FolderId
		}

		if respData.Data.FolderName != nil {
			dataMap["folder_name"] = respData.Data.FolderName
		}

		if respData.Data.ProjectName != nil {
			dataMap["project_name"] = respData.Data.ProjectName
		}

		if respData.Data.TaskTypeId != nil {
			dataMap["task_type_id"] = respData.Data.TaskTypeId
		}

		if respData.Data.WorkflowParams != nil {
			dataMap["workflow_params"] = respData.Data.WorkflowParams
		}

		if respData.Data.SupportRerun != nil {
			dataMap["support_rerun"] = respData.Data.SupportRerun
		}

		if respData.Data.WorkflowExecutionState != nil {
			dataMap["workflow_execution_state"] = respData.Data.WorkflowExecutionState
		}

		if respData.Data.ExecutionResult != nil {
			dataMap["execution_result"] = respData.Data.ExecutionResult
		}

		_ = d.Set("data", []interface{}{dataMap})
	}

	// Set resource ID using project_id and task_execution_id
	d.SetId(helper.DataResourceIdsHash([]string{projectId, taskExecutionId}))

	output, ok := d.GetOk("result_output_file")
	if ok && output.(string) != "" {
		if e := tccommon.WriteToFile(output.(string), dataMap); e != nil {
			return e
		}
	}

	return nil
}
