// Code generated by iacg; DO NOT EDIT.
package teo

import (
	"context"

	"github.com/hashicorp/terraform-plugin-sdk/v2/helper/resource"
	"github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema"
	teo "github.com/tencentcloud/tencentcloud-sdk-go/tencentcloud/teo/v20220901"

	tccommon "github.com/tencentcloudstack/terraform-provider-tencentcloud/tencentcloud/common"
	"github.com/tencentcloudstack/terraform-provider-tencentcloud/tencentcloud/internal/helper"
)

func DataSourceTencentCloudTeoZoneAvailablePlans() *schema.Resource {
	return &schema.Resource{
		Read: dataSourceTencentCloudTeoZoneAvailablePlansRead,
		Schema: map[string]*schema.Schema{
			"plan_info_list": {
				Type:        schema.TypeList,
				Computed:    true,
				Description: "可用区 plans 其中 当前 账号 可以 使用。",
				Elem: &schema.Resource{
					Schema: map[string]*schema.Schema{
						"plan_type": {
							Type:        schema.TypeString,
							Computed:    true,
							Description: "Plan 类型",
						},
						"currency": {
							Type:        schema.TypeString,
							Computed:    true,
							Description: "Settlement Currency 类型 有效值：`CNY`，`USD`。",
						},
						"flux": {
							Type:        schema.TypeInt,
							Computed:    true,
							Description: "数量 fluxes included 在 可用区 plan. 单位：Byte。",
						},
						"frequency": {
							Type:        schema.TypeString,
							Computed:    true,
							Description: "Billing cycle. 有效 值:\n- `y`: Billed 通过 year.\n- `m`: Billed 通过 month.\n- `h`: Billed 通过 hour.\n- `M`: Billed 通过 minute.\n- `s`: Billed 通过 second。",
						},
						"price": {
							Type:        schema.TypeFloat,
							Computed:    true,
							Description: "Price 的 plan. 单位：cent。",
						},
						"request": {
							Type:        schema.TypeInt,
							Computed:    true,
							Description: "数量 requests included 在 可用区 plan。",
						},
						"site_number": {
							Type:        schema.TypeInt,
							Computed:    true,
							Description: "数量 zones 此 可用区 plan 可以 bind。",
						},
						"area": {
							Type:        schema.TypeString,
							Computed:    true,
							Description: "Acceleration area 的 plan. 有效 值: `mainland`，`overseas`。",
						},
					},
				},
			},

			"result_output_file": {
				Type:        schema.TypeString,
				Optional:    true,
				Description: "用于保存结果。",
			},
		},
	}
}

func dataSourceTencentCloudTeoZoneAvailablePlansRead(d *schema.ResourceData, meta interface{}) error {
	defer tccommon.LogElapsed("data_source.tencentcloud_teo_zone_available_plans.read")()
	defer tccommon.InconsistentCheck(d, meta)()

	logId := tccommon.GetLogId(nil)
	ctx := tccommon.NewResourceLifeCycleHandleFuncContext(context.Background(), logId, d, meta)

	service := TeoService{client: meta.(tccommon.ProviderMeta).GetAPIV3Conn()}

	paramMap := make(map[string]interface{})
	var respData []*teo.PlanInfo
	err := resource.Retry(tccommon.ReadRetryTimeout, func() *resource.RetryError {
		result, e := service.DescribeTeoZoneAvailablePlansByFilter(ctx, paramMap)
		if e != nil {
			return tccommon.RetryError(e)
		}
		respData = result
		return nil
	})
	if err != nil {
		return err
	}

	planInfoId := make([]string, 0, len(respData))
	planInfoList := make([]map[string]interface{}, 0, len(respData))
	if respData != nil {
		for _, planInfo := range respData {
			planInfoMap := map[string]interface{}{}

			var planType string
			if planInfo.PlanType != nil {
				planInfoMap["plan_type"] = planInfo.PlanType
				planType = *planInfo.PlanType
			}

			if planInfo.Currency != nil {
				planInfoMap["currency"] = planInfo.Currency
			}

			if planInfo.Flux != nil {
				planInfoMap["flux"] = planInfo.Flux
			}

			if planInfo.Frequency != nil {
				planInfoMap["frequency"] = planInfo.Frequency
			}

			if planInfo.Price != nil {
				planInfoMap["price"] = planInfo.Price
			}

			if planInfo.Request != nil {
				planInfoMap["request"] = planInfo.Request
			}

			if planInfo.SiteNumber != nil {
				planInfoMap["site_number"] = planInfo.SiteNumber
			}

			if planInfo.Area != nil {
				planInfoMap["area"] = planInfo.Area
			}

			planInfoId = append(planInfoId, planType)
			planInfoList = append(planInfoList, planInfoMap)
		}

		_ = d.Set("plan_info_list", planInfoList)
	}

	d.SetId(helper.DataResourceIdsHash(planInfoId))

	output, ok := d.GetOk("result_output_file")
	if ok && output.(string) != "" {
		if e := tccommon.WriteToFile(output.(string), planInfoList); e != nil {
			return e
		}
	}

	return nil
}
