// Code generated by iacg; DO NOT EDIT.
package teo

import (
	"context"

	"github.com/hashicorp/terraform-plugin-sdk/v2/helper/resource"
	"github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema"
	teov20220901 "github.com/tencentcloud/tencentcloud-sdk-go/tencentcloud/teo/v20220901"
	tccommon "github.com/tencentcloudstack/terraform-provider-tencentcloud/tencentcloud/common"
	"github.com/tencentcloudstack/terraform-provider-tencentcloud/tencentcloud/internal/helper"
)

func DataSourceTencentCloudTeoConfigGroupVersions() *schema.Resource {
	return &schema.Resource{
		Read: dataSourceTencentCloudTeoConfigGroupVersionsRead,
		Schema: map[string]*schema.Schema{
			"zone_id": {
				Type:        schema.TypeString,
				Required:    true,
				Description: "可用区 ID",
			},

			"group_id": {
				Type:        schema.TypeString,
				Required:    true,
				Description: "Configuraration 组 ID",
			},

			"filters": {
				Type:        schema.TypeList,
				Optional:    true,
				Description: "Filtering condition. 最大 值 的 Filters.Values 是 20. 如果 此 参数 是 不 指定，all 版本 信息 对于 selected 配置 组 是 返回. Detailed filtering conditions: 版本-ID (过滤器 通过 版本 ID)。",
				Elem: &schema.Resource{
					Schema: map[string]*schema.Schema{
						"name": {
							Type:        schema.TypeString,
							Required:    true,
							Description: "待过滤字段",
						},
						"values": {
							Type:        schema.TypeSet,
							Required:    true,
							Description: "值 的 filtered 字段。",
							Elem: &schema.Schema{
								Type: schema.TypeString,
							},
						},
						"fuzzy": {
							Type:        schema.TypeBool,
							Optional:    true,
							Description: "是否enable fuzzy 查询。",
						},
					},
				},
			},

			"config_group_version_infos": {
				Type:        schema.TypeList,
				Computed:    true,
				Description: "版本 信息 列表。",
				Elem: &schema.Resource{
					Schema: map[string]*schema.Schema{
						"version_id": {
							Type:        schema.TypeString,
							Required:    true,
							Description: "版本 ID。",
						},
						"version_number": {
							Type:        schema.TypeString,
							Optional:    true,
							Description: "版本 No。",
						},
						"group_id": {
							Type:        schema.TypeString,
							Optional:    true,
							Description: "Configuraration 组 ID",
						},
						"group_type": {
							Type:        schema.TypeString,
							Optional:    true,
							Description: "Configuration 组 类型 有效值：l7_acceleration (L7 acceleration 配置 组)，edge_functions (Edge 函数 配置 组)。",
						},
						"description": {
							Type:        schema.TypeString,
							Optional:    true,
							Description: "版本 描述",
						},
						"status": {
							Type:        schema.TypeString,
							Optional:    true,
							Description: "版本 状态 有效值：creating (Being 创建)，inactive (Not effective)，活跃 (Effective)。",
						},
						"create_time": {
							Type:        schema.TypeString,
							Optional:    true,
							Description: "版本 创建时间. 时间格式 follows ISO 8601 standard 和 是 represented 在 Coordinated Universal Time (UTC)。",
						},
					},
				},
			},

			"result_output_file": {
				Type:        schema.TypeString,
				Optional:    true,
				Description: "用于保存结果。",
			},
		},
	}
}

func dataSourceTencentCloudTeoConfigGroupVersionsRead(d *schema.ResourceData, meta interface{}) error {
	defer tccommon.LogElapsed("data_source.tencentcloud_teo_config_group_versions.read")()
	defer tccommon.InconsistentCheck(d, meta)()

	logId := tccommon.GetLogId(nil)
	ctx := tccommon.NewResourceLifeCycleHandleFuncContext(context.Background(), logId, d, meta)

	service := TeoService{client: meta.(tccommon.ProviderMeta).GetAPIV3Conn()}

	paramMap := make(map[string]interface{})
	if v, ok := d.GetOk("zone_id"); ok {
		paramMap["ZoneId"] = helper.String(v.(string))
	}

	if v, ok := d.GetOk("group_id"); ok {
		paramMap["GroupId"] = helper.String(v.(string))
	}

	if v, ok := d.GetOk("filters"); ok {
		filtersSet := v.([]interface{})
		tmpSet := make([]*teov20220901.AdvancedFilter, 0, len(filtersSet))
		for _, item := range filtersSet {
			filtersMap := item.(map[string]interface{})
			advancedFilter := teov20220901.AdvancedFilter{}
			if v, ok := filtersMap["name"].(string); ok && v != "" {
				advancedFilter.Name = helper.String(v)
			}
			if v, ok := filtersMap["values"]; ok {
				valuesSet := v.(*schema.Set).List()
				for i := range valuesSet {
					values := valuesSet[i].(string)
					advancedFilter.Values = append(advancedFilter.Values, helper.String(values))
				}
			}
			if v, ok := filtersMap["fuzzy"].(bool); ok {
				advancedFilter.Fuzzy = helper.Bool(v)
			}
			tmpSet = append(tmpSet, &advancedFilter)
		}
		paramMap["Filters"] = tmpSet
	}

	var respData []*teov20220901.ConfigGroupVersionInfo
	reqErr := resource.Retry(tccommon.ReadRetryTimeout, func() *resource.RetryError {
		result, e := service.DescribeTeoConfigGroupVersionsByFilter(ctx, paramMap)
		if e != nil {
			return tccommon.RetryError(e)
		}
		respData = result
		return nil
	})
	if reqErr != nil {
		return reqErr
	}

	ids := make([]string, 0, len(respData))
	configGroupVersionInfosList := make([]map[string]interface{}, 0, len(respData))
	if respData != nil {
		for _, configGroupVersionInfos := range respData {
			configGroupVersionInfosMap := map[string]interface{}{}

			if configGroupVersionInfos.VersionId != nil {
				configGroupVersionInfosMap["version_id"] = configGroupVersionInfos.VersionId
				ids = append(ids, *configGroupVersionInfos.VersionId)
			}

			if configGroupVersionInfos.VersionNumber != nil {
				configGroupVersionInfosMap["version_number"] = configGroupVersionInfos.VersionNumber
			}

			if configGroupVersionInfos.GroupId != nil {
				configGroupVersionInfosMap["group_id"] = configGroupVersionInfos.GroupId
			}

			if configGroupVersionInfos.GroupType != nil {
				configGroupVersionInfosMap["group_type"] = configGroupVersionInfos.GroupType
			}

			if configGroupVersionInfos.Description != nil {
				configGroupVersionInfosMap["description"] = configGroupVersionInfos.Description
			}

			if configGroupVersionInfos.Status != nil {
				configGroupVersionInfosMap["status"] = configGroupVersionInfos.Status
			}

			if configGroupVersionInfos.CreateTime != nil {
				configGroupVersionInfosMap["create_time"] = configGroupVersionInfos.CreateTime
			}

			configGroupVersionInfosList = append(configGroupVersionInfosList, configGroupVersionInfosMap)
		}

		_ = d.Set("config_group_version_infos", configGroupVersionInfosList)
	}

	d.SetId(helper.DataResourceIdsHash(ids))
	output, ok := d.GetOk("result_output_file")
	if ok && output.(string) != "" {
		if e := tccommon.WriteToFile(output.(string), configGroupVersionInfosList); e != nil {
			return e
		}
	}

	return nil
}
