// Code generated by iacg; DO NOT EDIT.
package teo

import (
	"context"

	"github.com/hashicorp/terraform-plugin-sdk/v2/helper/resource"
	"github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema"
	teov20220901 "github.com/tencentcloud/tencentcloud-sdk-go/tencentcloud/teo/v20220901"
	tccommon "github.com/tencentcloudstack/terraform-provider-tencentcloud/tencentcloud/common"
	"github.com/tencentcloudstack/terraform-provider-tencentcloud/tencentcloud/internal/helper"
)

func DataSourceTencentCloudTeoEnvironments() *schema.Resource {
	return &schema.Resource{
		Read: dataSourceTencentCloudTeoEnvironmentsRead,
		Schema: map[string]*schema.Schema{
			"zone_id": {
				Type:        schema.TypeString,
				Required:    true,
				Description: "可用区 ID",
			},

			"env_infos": {
				Type:        schema.TypeList,
				Computed:    true,
				Description: "Environment 列表。",
				Elem: &schema.Resource{
					Schema: map[string]*schema.Schema{
						"env_id": {
							Type:        schema.TypeString,
							Required:    true,
							Description: "Environment ID。",
						},
						"env_type": {
							Type:        schema.TypeString,
							Required:    true,
							Description: "Environment 类型 有效值：production (Production 环境)，staging (Test 环境)。",
						},
						"status": {
							Type:        schema.TypeString,
							Required:    true,
							Description: "Environment 状态 有效值：creating (Being 创建)，running ( 环境 是 stable，使用 版本 changes allowed)，version_deploying ( 版本 是 currently being deployed，使用 无 more changes allowed)。",
						},
						"scope": {
							Type:        schema.TypeSet,
							Required:    true,
							Description: "Effective 范围 的 配置 在 当前 环境. 有效值：ALL (It takes effect 在 entire 网络 当 EnvType 是 集合 到 production)，It 返回IP 地址 的 测试 节点 对于 主机 binding during testing 当 EnvType 是 集合 到 staging。",
							Elem: &schema.Schema{
								Type: schema.TypeString,
							},
						},
						"current_config_group_version_infos": {
							Type:        schema.TypeList,
							Required:    true,
							Description: "For effective versions 的 each 配置 组 在 当前 环境，there 是 two possible scenarios based 在 值 的 状态: 当 状态 是 集合 到 version_deploying， 返回 值 的 此 字段 表示 previously effective 版本 In other words，during 部署 的 new 版本， effective 版本 是 一个 该 是 在 effect before any changes 是 made. 当 状态 是 集合 到 running， 值 返回 通过 此 字段 是 currently effective 版本",
							Elem: &schema.Resource{
								Schema: map[string]*schema.Schema{
									"version_id": {
										Type:        schema.TypeString,
										Required:    true,
										Description: "版本 ID。",
									},
									"version_number": {
										Type:        schema.TypeString,
										Optional:    true,
										Description: "版本 No。",
									},
									"group_id": {
										Type:        schema.TypeString,
										Optional:    true,
										Description: "Configuraration 组 ID",
									},
									"group_type": {
										Type:        schema.TypeString,
										Optional:    true,
										Description: "Configuration 组 类型 有效值：l7_acceleration (L7 acceleration 配置 组)，edge_functions (Edge 函数 配置 组)。",
									},
									"description": {
										Type:        schema.TypeString,
										Optional:    true,
										Description: "版本 描述",
									},
									"status": {
										Type:        schema.TypeString,
										Optional:    true,
										Description: "版本 状态 有效值：creating (Being 创建)，inactive (Not effective)，活跃 (Effective)。",
									},
									"create_time": {
										Type:        schema.TypeString,
										Optional:    true,
										Description: "版本 创建时间. 时间格式 follows ISO 8601 standard 和 是 represented 在 Coordinated Universal Time (UTC)。",
									},
								},
							},
						},
						"create_time": {
							Type:        schema.TypeString,
							Required:    true,
							Description: "创建时间. 时间格式 follows ISO 8601 standard 和 是 represented 在 Coordinated Universal Time (UTC)。",
						},
						"update_time": {
							Type:        schema.TypeString,
							Required:    true,
							Description: "更新时间. 时间格式 follows ISO 8601 standard 和 是 represented 在 Coordinated Universal Time (UTC)。",
						},
					},
				},
			},

			"result_output_file": {
				Type:        schema.TypeString,
				Optional:    true,
				Description: "用于保存结果。",
			},
		},
	}
}

func dataSourceTencentCloudTeoEnvironmentsRead(d *schema.ResourceData, meta interface{}) error {
	defer tccommon.LogElapsed("data_source.tencentcloud_teo_environments.read")()
	defer tccommon.InconsistentCheck(d, meta)()

	logId := tccommon.GetLogId(nil)
	ctx := tccommon.NewResourceLifeCycleHandleFuncContext(context.Background(), logId, d, meta)

	service := TeoService{client: meta.(tccommon.ProviderMeta).GetAPIV3Conn()}

	paramMap := make(map[string]interface{})
	if v, ok := d.GetOk("zone_id"); ok {
		paramMap["ZoneId"] = helper.String(v.(string))
	}

	var respData []*teov20220901.EnvInfo
	reqErr := resource.Retry(tccommon.ReadRetryTimeout, func() *resource.RetryError {
		result, e := service.DescribeTeoEnvironmentsByFilter(ctx, paramMap)
		if e != nil {
			return tccommon.RetryError(e)
		}
		respData = result
		return nil
	})
	if reqErr != nil {
		return reqErr
	}

	ids := make([]string, 0, len(respData))
	envInfosList := make([]map[string]interface{}, 0, len(respData))
	if respData != nil {
		for _, envInfos := range respData {
			envInfosMap := map[string]interface{}{}

			if envInfos.EnvId != nil {
				envInfosMap["env_id"] = envInfos.EnvId
				ids = append(ids, *envInfos.EnvId)
			}

			if envInfos.EnvType != nil {
				envInfosMap["env_type"] = envInfos.EnvType
			}

			if envInfos.Status != nil {
				envInfosMap["status"] = envInfos.Status
			}

			if envInfos.Scope != nil {
				envInfosMap["scope"] = envInfos.Scope
			}

			currentConfigGroupVersionInfosList := make([]map[string]interface{}, 0, len(envInfos.CurrentConfigGroupVersionInfos))
			if envInfos.CurrentConfigGroupVersionInfos != nil {
				for _, currentConfigGroupVersionInfos := range envInfos.CurrentConfigGroupVersionInfos {
					currentConfigGroupVersionInfosMap := map[string]interface{}{}

					if currentConfigGroupVersionInfos.VersionId != nil {
						currentConfigGroupVersionInfosMap["version_id"] = currentConfigGroupVersionInfos.VersionId
					}

					if currentConfigGroupVersionInfos.VersionNumber != nil {
						currentConfigGroupVersionInfosMap["version_number"] = currentConfigGroupVersionInfos.VersionNumber
					}

					if currentConfigGroupVersionInfos.GroupId != nil {
						currentConfigGroupVersionInfosMap["group_id"] = currentConfigGroupVersionInfos.GroupId
					}

					if currentConfigGroupVersionInfos.GroupType != nil {
						currentConfigGroupVersionInfosMap["group_type"] = currentConfigGroupVersionInfos.GroupType
					}

					if currentConfigGroupVersionInfos.Description != nil {
						currentConfigGroupVersionInfosMap["description"] = currentConfigGroupVersionInfos.Description
					}

					if currentConfigGroupVersionInfos.Status != nil {
						currentConfigGroupVersionInfosMap["status"] = currentConfigGroupVersionInfos.Status
					}

					if currentConfigGroupVersionInfos.CreateTime != nil {
						currentConfigGroupVersionInfosMap["create_time"] = currentConfigGroupVersionInfos.CreateTime
					}

					currentConfigGroupVersionInfosList = append(currentConfigGroupVersionInfosList, currentConfigGroupVersionInfosMap)
				}

				envInfosMap["current_config_group_version_infos"] = currentConfigGroupVersionInfosList
			}
			if envInfos.CreateTime != nil {
				envInfosMap["create_time"] = envInfos.CreateTime
			}

			if envInfos.UpdateTime != nil {
				envInfosMap["update_time"] = envInfos.UpdateTime
			}

			envInfosList = append(envInfosList, envInfosMap)
		}

		_ = d.Set("env_infos", envInfosList)
	}

	d.SetId(helper.DataResourceIdsHash(ids))

	output, ok := d.GetOk("result_output_file")
	if ok && output.(string) != "" {
		if e := tccommon.WriteToFile(output.(string), envInfosList); e != nil {
			return e
		}
	}

	return nil
}
