// Code generated by iacg; DO NOT EDIT.
package teo

import (
	"context"

	"github.com/hashicorp/terraform-plugin-sdk/v2/helper/resource"
	"github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema"
	teov20220901 "github.com/tencentcloud/tencentcloud-sdk-go/tencentcloud/teo/v20220901"
	tccommon "github.com/tencentcloudstack/terraform-provider-tencentcloud/tencentcloud/common"
	"github.com/tencentcloudstack/terraform-provider-tencentcloud/tencentcloud/internal/helper"
)

func DataSourceTencentCloudTeoZones() *schema.Resource {
	return &schema.Resource{
		Read: dataSourceTencentCloudTeoZonesRead,
		Schema: map[string]*schema.Schema{
			"filters": {
				Type:        schema.TypeList,
				Optional:    true,
				Description: "Filter criteria. the maximum 值 of Filters.Values is 20. 如果此参数为空，all site information authorized under the current appid will be returned. detailed filter criteria are as follows: 可用区-名称: filter by 站点名称; 可用区-id: filter by 站点 ID the 站点 ID is in the 格式 of 可用区-2noz78a8ev6k; 状态: filter by site 状态; 标签-键: filter by 标签键; 标签-值: filter by 标签值; alias-可用区-名称: filter by identical site identifier. when performing a fuzzy query，the fields that support filtering are named 可用区-名称 or alias-可用区-名称",
				Elem: &schema.Resource{
					Schema: map[string]*schema.Schema{
						"name": {
							Type:        schema.TypeString,
							Required:    true,
							Description: "待过滤字段",
						},
						"values": {
							Type:        schema.TypeSet,
							Required:    true,
							Description: "值 of the filtered field。",
							Elem: &schema.Schema{
								Type: schema.TypeString,
							},
						},
						"fuzzy": {
							Type:        schema.TypeBool,
							Optional:    true,
							Description: "是否enable fuzzy query。",
						},
					},
				},
			},

			"order": {
				Type:        schema.TypeString,
				Optional:    true,
				Description: "Sort the returned results according to this field. Values include: `类型`: Connection 模式; `area`: Acceleration 地域; `create-time`: 创建时间; `可用区-名称`: 站点名称; `use-time`: Last used time; `活跃-状态` Effective 状态 默认值：`create-time`。",
			},

			"direction": {
				Type:        schema.TypeString,
				Optional:    true,
				Description: "Sort direction. If the field 值 is a number，排序方式 the numeric 值 If the field 值 is text，排序方式 the ascill 代码 Values include: `asc`: From the smallest to largest; `desc`: From the largest to smallest. 默认值：`desc`。",
			},

			"zones": {
				Type:        schema.TypeList,
				Computed:    true,
				Description: "Details of sites。",
				Elem: &schema.Resource{
					Schema: map[string]*schema.Schema{
						"zone_id": {
							Type:        schema.TypeString,
							Required:    true,
							Description: "站点 ID",
						},
						"zone_name": {
							Type:        schema.TypeString,
							Required:    true,
							Description: "The 站点名称",
						},
						"original_name_servers": {
							Type:        schema.TypeSet,
							Required:    true,
							Description: "列表 名称 servers used by the site。",
							Elem: &schema.Schema{
								Type: schema.TypeString,
							},
						},
						"name_servers": {
							Type:        schema.TypeSet,
							Required:    true,
							Description: "The 列表 名称 servers assigned by Tencent Cloud。",
							Elem: &schema.Schema{
								Type: schema.TypeString,
							},
						},
						"status": {
							Type:        schema.TypeString,
							Required:    true,
							Description: "The site 状态 Values: `活跃`: The 名称 server is switched to EdgeOne. `pending`: The 名称 server is not switched. `moved`: The 名称 server is changed to other service providers. `deactivated`: The site is blocked. `initializing`: The site is not bound with any plan。",
						},
						"type": {
							Type:        schema.TypeString,
							Required:    true,
							Description: "Site access method. 有效值：full: NS access; partial: CNAME access; noDomainAccess: access with no 域名 名称",
						},
						"paused": {
							Type:        schema.TypeBool,
							Required:    true,
							Description: "是否site is 已禁用",
						},
						"cname_speed_up": {
							Type:        schema.TypeString,
							Required:    true,
							Description: "Whether CNAME acceleration is 已启用 Values: `已启用`: 已启用; `已禁用`: 已禁用",
						},
						"cname_status": {
							Type:        schema.TypeString,
							Required:    true,
							Description: "CNAME record access 状态 Values: `finished`: The site is verified.`pending`: The site is being verified。",
						},
						"tags": {
							Type:        schema.TypeList,
							Required:    true,
							Description: "The 列表 resource 标签",
							Elem: &schema.Resource{
								Schema: map[string]*schema.Schema{
									"tag_key": {
										Type:        schema.TypeString,
										Required:    true,
										Description: "The 标签键 注意：此字段可能返回 null，表示无法获取有效值。",
									},
									"tag_value": {
										Type:        schema.TypeString,
										Required:    true,
										Description: "The 标签值 注意：此字段可能返回 null，表示无法获取有效值。",
									},
								},
							},
						},
						"resources": {
							Type:        schema.TypeList,
							Required:    true,
							Description: "The 列表 billable resources。",
							Elem: &schema.Resource{
								Schema: map[string]*schema.Schema{
									"id": {
										Type:        schema.TypeString,
										Required:    true,
										Description: "The resource ID。",
									},
									"pay_mode": {
										Type:        schema.TypeInt,
										Required:    true,
										Description: "Billing 模式，`0`: Pay-as-you-go",
									},
									"create_time": {
										Type:        schema.TypeString,
										Required:    true,
										Description: "The 创建时间。",
									},
									"enable_time": {
										Type:        schema.TypeString,
										Required:    true,
										Description: "The effective time。",
									},
									"expire_time": {
										Type:        schema.TypeString,
										Required:    true,
										Description: "The 过期时间。",
									},
									"status": {
										Type:        schema.TypeString,
										Required:    true,
										Description: "The plan 状态 Values: `normal`: Normal; `isolated`: Isolated; `destroyed`: Terminated。",
									},
									"sv": {
										Type:        schema.TypeList,
										Required:    true,
										Description: "Pricing query parameter",
										Elem: &schema.Resource{
											Schema: map[string]*schema.Schema{
												"key": {
													Type:        schema.TypeString,
													Required:    true,
													Description: "The parameter 键",
												},
												"value": {
													Type:        schema.TypeString,
													Required:    true,
													Description: "The parameter 值",
												},
												"pack": {
													Type:        schema.TypeString,
													Optional:    true,
													Description: "Quota for a resource. Values: `可用区`: Quota for sites; `custom-rule`: Quota for custom rules; `rate-limiting-rule`: Quota for rate limiting rules; `l4-proxy-instance`: Quota for L4 proxy instances. 注意：此字段可能返回 null，表示无法获取有效值。",
												},
												"instance_id": {
													Type:        schema.TypeString,
													Optional:    true,
													Description: "ID L4 proxy instance. 注意：此字段可能返回 null，表示无法获取有效值。",
												},
												"protection_specs": {
													Type:        schema.TypeString,
													Optional:    true,
													Description: "The protection specification. Values: `cm_30G`: 30 Gbps base protection bandwidth in **Chinese mainland** service area; `cm_60G`: 60 Gbps base protection bandwidth in **Chinese mainland** service area; `cm_100G`: 100 Gbps base protection bandwidth in **Chinese mainland** service area; `anycast_300G`: 300 Gbps Anycast-based protection in **Global (MLC)** service area; `anycast_unlimited`: Unlimited Anycast-based protection bandwidth in **Global (MLC)** service area; `cm_30G_anycast_300G`: 30 Gbps base protection bandwidth in **Chinese mainland** service area and 300 Gbps Anycast-based protection bandwidth in **Global (MLC)** service area; `cm_30G_anycast_unlimited`: 30 Gbps base protection bandwidth in **Chinese mainland** service area and unlimited Anycast-based protection bandwidth in **Global (MLC)** service area; cm_60G_anycast_300G`: 60 Gbps base protection bandwidth in **Chinese mainland** service area and 300 Gbps Anycast-based protection bandwidth in **Global (MLC)** service area; cm_60G_anycast_unlimited`: 60 Gbps base protection bandwidth in **Chinese mainland** service area and unlimited Anycast-based protection bandwidth in **Global (MLC)** service area</li><li> `cm_100G_anycast_300G`: 100 Gbps base protection bandwidth in **Chinese mainland** service area and 300 Gbps Anycast-based protection bandwidth in **Global (MLC)** service area，cm_100G_anycast_unlimited`: 100 Gbps base protection bandwidth in **Chinese mainland** service area and unlimited Anycast-based protection bandwidth in **Global (MLC)** service area. 注意：此字段可能返回 null，表示无法获取有效值。",
												},
											},
										},
									},
									"auto_renew_flag": {
										Type:        schema.TypeInt,
										Required:    true,
										Description: "是否enable auto-renewal. Values: `0`: Default 状态 `1`: Enable auto-renewal. `2`: Disable auto-renewal。",
									},
									"plan_id": {
										Type:        schema.TypeString,
										Required:    true,
										Description: "ID resource associated with the plan。",
									},
									"area": {
										Type:        schema.TypeString,
										Required:    true,
										Description: "Applicable area. Values: `mainland`: Chinese mainland; `overseas`: Regions outside the Chinese mainland; `global`: Global。",
									},
									"group": {
										Type:        schema.TypeString,
										Required:    true,
										Description: "The 资源类型 Values: `plan`: Plan resources; `pay-as-you-go`: Pay-as-you-go resources; `值-added`: 值-added resources. 注意：此字段可能返回 null，表示无法获取有效值。",
									},
									"zone_number": {
										Type:        schema.TypeInt,
										Required:    true,
										Description: "The sites that are associated with the current resources. 注意：此字段可能返回 null，表示无法获取有效值。",
									},
									"type": {
										Type:        schema.TypeString,
										Required:    true,
										Description: "Resource 标签 类型 有效值：vodeo: vodeo resource。",
									},
								},
							},
						},
						"created_on": {
							Type:        schema.TypeString,
							Required:    true,
							Description: "The 创建时间 of the site。",
						},
						"modified_on": {
							Type:        schema.TypeString,
							Required:    true,
							Description: "The modification date of the site。",
						},
						"area": {
							Type:        schema.TypeString,
							Required:    true,
							Description: "The site access 地域 Values: `global`: Global. `mainland`: Chinese mainland. `overseas`: Outside the Chinese mainland。",
						},
						"vanity_name_servers": {
							Type:        schema.TypeList,
							Required:    true,
							MaxItems:    1,
							Description: "The custom 名称 server information.\n注意：此字段可能返回 null，表示无法获取有效值。",
							Elem: &schema.Resource{
								Schema: map[string]*schema.Schema{
									"switch": {
										Type:        schema.TypeString,
										Required:    true,
										Description: "是否enable custom 名称 servers. Values: `on`: Enable; `off`: Disable。",
									},
									"servers": {
										Type:        schema.TypeSet,
										Optional:    true,
										Description: "列表 custom 名称 servers",
										Elem: &schema.Schema{
											Type: schema.TypeString,
										},
									},
								},
							},
						},
						"vanity_name_servers_ips": {
							Type:        schema.TypeList,
							Required:    true,
							Description: "The custom 名称 server IP information. 注意：此字段可能返回 null，表示无法获取有效值。",
							Elem: &schema.Resource{
								Schema: map[string]*schema.Schema{
									"name": {
										Type:        schema.TypeString,
										Required:    true,
										Description: "Custom 名称 名称 server",
									},
									"i_pv4": {
										Type:        schema.TypeString,
										Required:    true,
										Description: "IPv4 地址 of the custom 名称 server",
									},
								},
							},
						},
						"active_status": {
							Type:        schema.TypeString,
							Required:    true,
							Description: "状态 proxy. Values: `活跃`: 已启用; `inactive`: Not activated; `paused`: 已禁用",
						},
						"alias_zone_name": {
							Type:        schema.TypeString,
							Required:    true,
							Description: "The site alias. It can be up to 20 characters consisting of digits，letters，hyphens (-) and underscores (_). 注意：此字段可能返回 null，表示无法获取有效值。",
						},
						"is_fake": {
							Type:        schema.TypeInt,
							Required:    true,
							Description: "是否为a fake site. 有效值：`0`: Non-fake site; `1`: Fake site。",
						},
						"lock_status": {
							Type:        schema.TypeString,
							Required:    true,
							Description: "Lock 状态 Values: `enable`: Normal. Modification is allowed. `disable`: Locked. Modification is not allowed. `plan_migrate`: Adjusting the plan. Modification is not allowed。",
						},
						"ownership_verification": {
							Type:        schema.TypeList,
							Required:    true,
							MaxItems:    1,
							Description: "Ownership verification information. 注意：此字段可能返回 null，表示无法获取有效值。",
							Elem: &schema.Resource{
								Schema: map[string]*schema.Schema{
									"dns_verification": {
										Type:        schema.TypeList,
										Required:    true,
										MaxItems:    1,
										Description: "CNAME，when there is no 域名 名称 access，the information 必填 for DNS resolution verification is used. For details，refer to [Site/域名 Ownership Verification\n](https://intl.cloud.tencent.com/document/product/1552/70789?from_cn_redirect=1#7af6ecf8-afca-4e35-8811-b5797ed1bde5). Note: This field may return null，which 表示a failure to obtain a valid 值",
										Elem: &schema.Resource{
											Schema: map[string]*schema.Schema{
												"subdomain": {
													Type:        schema.TypeString,
													Required:    true,
													Description: "The 主机 record。",
												},
												"record_type": {
													Type:        schema.TypeString,
													Required:    true,
													Description: "The record 类型",
												},
												"record_value": {
													Type:        schema.TypeString,
													Required:    true,
													Description: "The record 值",
												},
											},
										},
									},
									"file_verification": {
										Type:        schema.TypeList,
										Required:    true,
										MaxItems:    1,
										Description: "CNAME，when there is no 域名 名称 access，the information 必填 for file verification is used. For details，refer to [Site/域名 Ownership Verification\n](https://intl.cloud.tencent.com/document/product/1552/70789?from_cn_redirect=1#7af6ecf8-afca-4e35-8811-b5797ed1bde5). Note: This field may return null，which 表示a failure to obtain a valid 值",
										Elem: &schema.Resource{
											Schema: map[string]*schema.Schema{
												"path": {
													Type:        schema.TypeString,
													Required:    true,
													Description: "EdgeOne obtains the file verification information in the format of \"Scheme + Host + URL Path\", (e.g. https://www.example.com/.well-known/teo-verification/z12h416twn.txt). This field is the URL path section of the URL you need to create.",
												},
												"content": {
													Type:        schema.TypeString,
													Required:    true,
													Description: "内容 of the verification file. The contents of this field need to be filled into the text file returned by `路径`。",
												},
											},
										},
									},
									"ns_verification": {
										Type:        schema.TypeList,
										Required:    true,
										MaxItems:    1,
										Description: "u200cInformation 必填 for switching DNS servers. It's applicable to sites connected via NSs. For details，see [Modifying DNS Server](https://intl.cloud.tencent.com/document/product/1552/90452?from_cn_redirect=1).\nNote: This field may return·null，indicating that no valid values can be obtained。",
										Elem: &schema.Resource{
											Schema: map[string]*schema.Schema{
												"name_servers": {
													Type:        schema.TypeSet,
													Required:    true,
													Description: "The DNS server 地址 assigned to the 用户 when connecting a site to EO via NS. You need to switch the NameServer of the 域名 名称 to this 地址",
													Elem: &schema.Schema{
														Type: schema.TypeString,
													},
												},
											},
										},
									},
								},
							},
						},
					},
				},
			},

			"result_output_file": {
				Type:        schema.TypeString,
				Optional:    true,
				Description: "用于保存结果。",
			},
		},
	}
}

func dataSourceTencentCloudTeoZonesRead(d *schema.ResourceData, meta interface{}) error {
	defer tccommon.LogElapsed("data_source.tencentcloud_teo_zones.read")()
	defer tccommon.InconsistentCheck(d, meta)()

	logId := tccommon.GetLogId(nil)
	ctx := tccommon.NewResourceLifeCycleHandleFuncContext(context.Background(), logId, d, meta)

	service := TeoService{client: meta.(tccommon.ProviderMeta).GetAPIV3Conn()}

	paramMap := make(map[string]interface{})
	if v, ok := d.GetOk("filters"); ok {
		filtersSet := v.([]interface{})
		tmpSet := make([]*teov20220901.AdvancedFilter, 0, len(filtersSet))
		for _, item := range filtersSet {
			filtersMap := item.(map[string]interface{})
			advancedFilter := teov20220901.AdvancedFilter{}
			if v, ok := filtersMap["name"].(string); ok && v != "" {
				advancedFilter.Name = helper.String(v)
			}
			if v, ok := filtersMap["values"]; ok {
				valuesSet := v.(*schema.Set).List()
				for i := range valuesSet {
					values := valuesSet[i].(string)
					advancedFilter.Values = append(advancedFilter.Values, helper.String(values))
				}
			}
			if v, ok := filtersMap["fuzzy"].(bool); ok {
				advancedFilter.Fuzzy = helper.Bool(v)
			}
			tmpSet = append(tmpSet, &advancedFilter)
		}
		paramMap["Filters"] = tmpSet
	}

	if v, ok := d.GetOk("order"); ok {
		paramMap["Order"] = helper.String(v.(string))
	}

	if v, ok := d.GetOk("direction"); ok {
		paramMap["Direction"] = helper.String(v.(string))
	}

	var respData []*teov20220901.Zone
	reqErr := resource.Retry(tccommon.ReadRetryTimeout, func() *resource.RetryError {
		result, e := service.DescribeTeoZonesByFilter(ctx, paramMap)
		if e != nil {
			return tccommon.RetryError(e)
		}
		respData = result
		return nil
	})
	if reqErr != nil {
		return reqErr
	}

	var zoneIds []string
	zonesList := make([]map[string]interface{}, 0, len(respData))
	if respData != nil {
		for _, zones := range respData {
			zonesMap := map[string]interface{}{}

			var zoneId string
			if zones.ZoneId != nil {
				zonesMap["zone_id"] = zones.ZoneId
				zoneId = *zones.ZoneId
			}

			if zones.ZoneName != nil {
				zonesMap["zone_name"] = zones.ZoneName
			}

			if zones.OriginalNameServers != nil {
				zonesMap["original_name_servers"] = zones.OriginalNameServers
			}

			if zones.NameServers != nil {
				zonesMap["name_servers"] = zones.NameServers
			}

			if zones.Status != nil {
				zonesMap["status"] = zones.Status
			}

			if zones.Type != nil {
				zonesMap["type"] = zones.Type
			}

			if zones.Paused != nil {
				zonesMap["paused"] = zones.Paused
			}

			if zones.CnameSpeedUp != nil {
				zonesMap["cname_speed_up"] = zones.CnameSpeedUp
			}

			if zones.CnameStatus != nil {
				zonesMap["cname_status"] = zones.CnameStatus
			}

			tagsList := make([]map[string]interface{}, 0, len(zones.Tags))
			if zones.Tags != nil {
				for _, tags := range zones.Tags {
					tagsMap := map[string]interface{}{}

					if tags.TagKey != nil {
						tagsMap["tag_key"] = tags.TagKey
					}

					if tags.TagValue != nil {
						tagsMap["tag_value"] = tags.TagValue
					}

					tagsList = append(tagsList, tagsMap)
				}

				zonesMap["tags"] = tagsList
			}
			resourcesList := make([]map[string]interface{}, 0, len(zones.Resources))
			if zones.Resources != nil {
				for _, resources := range zones.Resources {
					resourcesMap := map[string]interface{}{}

					if resources.Id != nil {
						resourcesMap["id"] = resources.Id
					}

					if resources.PayMode != nil {
						resourcesMap["pay_mode"] = resources.PayMode
					}

					if resources.CreateTime != nil {
						resourcesMap["create_time"] = resources.CreateTime
					}

					if resources.EnableTime != nil {
						resourcesMap["enable_time"] = resources.EnableTime
					}

					if resources.ExpireTime != nil {
						resourcesMap["expire_time"] = resources.ExpireTime
					}

					if resources.Status != nil {
						resourcesMap["status"] = resources.Status
					}

					svList := make([]map[string]interface{}, 0, len(resources.Sv))
					if resources.Sv != nil {
						for _, sv := range resources.Sv {
							svMap := map[string]interface{}{}

							if sv.Key != nil {
								svMap["key"] = sv.Key
							}

							if sv.Value != nil {
								svMap["value"] = sv.Value
							}

							if sv.Pack != nil {
								svMap["pack"] = sv.Pack
							}

							if sv.InstanceId != nil {
								svMap["instance_id"] = sv.InstanceId
							}

							if sv.ProtectionSpecs != nil {
								svMap["protection_specs"] = sv.ProtectionSpecs
							}

							svList = append(svList, svMap)
						}

						resourcesMap["sv"] = svList
					}
					if resources.AutoRenewFlag != nil {
						resourcesMap["auto_renew_flag"] = resources.AutoRenewFlag
					}

					if resources.PlanId != nil {
						resourcesMap["plan_id"] = resources.PlanId
					}

					if resources.Area != nil {
						resourcesMap["area"] = resources.Area
					}

					if resources.Group != nil {
						resourcesMap["group"] = resources.Group
					}

					if resources.ZoneNumber != nil {
						resourcesMap["zone_number"] = resources.ZoneNumber
					}

					if resources.Type != nil {
						resourcesMap["type"] = resources.Type
					}

					resourcesList = append(resourcesList, resourcesMap)
				}

				zonesMap["resources"] = resourcesList
			}
			if zones.CreatedOn != nil {
				zonesMap["created_on"] = zones.CreatedOn
			}

			if zones.ModifiedOn != nil {
				zonesMap["modified_on"] = zones.ModifiedOn
			}

			if zones.Area != nil {
				zonesMap["area"] = zones.Area
			}

			vanityNameServersMap := map[string]interface{}{}

			if zones.VanityNameServers != nil {
				if zones.VanityNameServers.Switch != nil {
					vanityNameServersMap["switch"] = zones.VanityNameServers.Switch
				}

				if zones.VanityNameServers.Servers != nil {
					vanityNameServersMap["servers"] = zones.VanityNameServers.Servers
				}

				zonesMap["vanity_name_servers"] = []interface{}{vanityNameServersMap}
			}

			vanityNameServersIpsList := make([]map[string]interface{}, 0, len(zones.VanityNameServersIps))
			if zones.VanityNameServersIps != nil {
				for _, vanityNameServersIps := range zones.VanityNameServersIps {
					vanityNameServersIpsMap := map[string]interface{}{}

					if vanityNameServersIps.Name != nil {
						vanityNameServersIpsMap["name"] = vanityNameServersIps.Name
					}

					if vanityNameServersIps.IPv4 != nil {
						vanityNameServersIpsMap["i_pv4"] = vanityNameServersIps.IPv4
					}

					vanityNameServersIpsList = append(vanityNameServersIpsList, vanityNameServersIpsMap)
				}

				zonesMap["vanity_name_servers_ips"] = vanityNameServersIpsList
			}
			if zones.ActiveStatus != nil {
				zonesMap["active_status"] = zones.ActiveStatus
			}

			if zones.AliasZoneName != nil {
				zonesMap["alias_zone_name"] = zones.AliasZoneName
			}

			if zones.IsFake != nil {
				zonesMap["is_fake"] = zones.IsFake
			}

			if zones.LockStatus != nil {
				zonesMap["lock_status"] = zones.LockStatus
			}

			ownershipVerificationMap := map[string]interface{}{}

			if zones.OwnershipVerification != nil {
				dnsVerificationMap := map[string]interface{}{}

				if zones.OwnershipVerification.DnsVerification != nil {
					if zones.OwnershipVerification.DnsVerification.Subdomain != nil {
						dnsVerificationMap["subdomain"] = zones.OwnershipVerification.DnsVerification.Subdomain
					}

					if zones.OwnershipVerification.DnsVerification.RecordType != nil {
						dnsVerificationMap["record_type"] = zones.OwnershipVerification.DnsVerification.RecordType
					}

					if zones.OwnershipVerification.DnsVerification.RecordValue != nil {
						dnsVerificationMap["record_value"] = zones.OwnershipVerification.DnsVerification.RecordValue
					}

					ownershipVerificationMap["dns_verification"] = []interface{}{dnsVerificationMap}
				}

				fileVerificationMap := map[string]interface{}{}

				if zones.OwnershipVerification.FileVerification != nil {
					if zones.OwnershipVerification.FileVerification.Path != nil {
						fileVerificationMap["path"] = zones.OwnershipVerification.FileVerification.Path
					}

					if zones.OwnershipVerification.FileVerification.Content != nil {
						fileVerificationMap["content"] = zones.OwnershipVerification.FileVerification.Content
					}

					ownershipVerificationMap["file_verification"] = []interface{}{fileVerificationMap}
				}

				nsVerificationMap := map[string]interface{}{}

				if zones.OwnershipVerification.NsVerification != nil {
					if zones.OwnershipVerification.NsVerification.NameServers != nil {
						nsVerificationMap["name_servers"] = zones.OwnershipVerification.NsVerification.NameServers
					}

					ownershipVerificationMap["ns_verification"] = []interface{}{nsVerificationMap}
				}

				zonesMap["ownership_verification"] = []interface{}{ownershipVerificationMap}
			}

			zoneIds = append(zoneIds, zoneId)
			zonesList = append(zonesList, zonesMap)
		}

		_ = d.Set("zones", zonesList)
	}

	d.SetId(helper.DataResourceIdsHash(zoneIds))

	output, ok := d.GetOk("result_output_file")
	if ok && output.(string) != "" {
		if e := tccommon.WriteToFile(output.(string), zonesList); e != nil {
			return e
		}
	}

	return nil
}
