// Code generated by iacg; DO NOT EDIT.
package teo

import (
	"context"

	"github.com/hashicorp/terraform-plugin-sdk/v2/helper/resource"
	"github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema"
	teov20220901 "github.com/tencentcloud/tencentcloud-sdk-go/tencentcloud/teo/v20220901"
	tccommon "github.com/tencentcloudstack/terraform-provider-tencentcloud/tencentcloud/common"
	"github.com/tencentcloudstack/terraform-provider-tencentcloud/tencentcloud/internal/helper"
)

func DataSourceTencentCloudTeoZones() *schema.Resource {
	return &schema.Resource{
		Read: dataSourceTencentCloudTeoZonesRead,
		Schema: map[string]*schema.Schema{
			"filters": {
				Type:        schema.TypeList,
				Optional:    true,
				Description: "过滤器 criteria. 最大 值 的 Filters.Values 是 20. 如果此参数为空，all site 信息 authorized under 当前 appid 将 是 返回. detailed 过滤器 criteria 是 作为 follows: 可用区-名称: 过滤器 通过 站点名称; 可用区-ID: 过滤器 通过 站点 ID 站点 ID 是 在 格式 的 可用区-2noz78a8ev6k; 状态: 过滤器 通过 site 状态; 标签-键: 过滤器 通过 标签键; 标签-值: 过滤器 通过 标签值; alias-可用区-名称: 过滤器 通过 identical site identifier. 当 performing fuzzy 查询， 字段 该 support filtering 是 named 可用区-名称 或 alias-可用区-名称",
				Elem: &schema.Resource{
					Schema: map[string]*schema.Schema{
						"name": {
							Type:        schema.TypeString,
							Required:    true,
							Description: "待过滤字段",
						},
						"values": {
							Type:        schema.TypeSet,
							Required:    true,
							Description: "值 的 filtered 字段。",
							Elem: &schema.Schema{
								Type: schema.TypeString,
							},
						},
						"fuzzy": {
							Type:        schema.TypeBool,
							Optional:    true,
							Description: "是否enable fuzzy 查询。",
						},
					},
				},
			},

			"order": {
				Type:        schema.TypeString,
				Optional:    true,
				Description: "Sort 返回 results according 到 此 字段. Values include: `类型`: Connection 模式; `area`: Acceleration 地域; `create-时间`: 创建时间; `可用区-名称`: 站点名称; `使用-时间`: Last 使用 时间; `活跃-状态` Effective 状态 默认值：`create-时间`。",
			},

			"direction": {
				Type:        schema.TypeString,
				Optional:    true,
				Description: "Sort direction. 如果 字段 值 是 数量，排序方式 numeric 值 如果 字段 值 是 text，排序方式 ascill 代码 Values include: `asc`: From smallest 到 largest; `desc`: From largest 到 smallest. 默认值：`desc`。",
			},

			"zones": {
				Type:        schema.TypeList,
				Computed:    true,
				Description: "Details 的 sites。",
				Elem: &schema.Resource{
					Schema: map[string]*schema.Schema{
						"zone_id": {
							Type:        schema.TypeString,
							Required:    true,
							Description: "站点 ID",
						},
						"zone_name": {
							Type:        schema.TypeString,
							Required:    true,
							Description: "站点名称",
						},
						"original_name_servers": {
							Type:        schema.TypeSet,
							Required:    true,
							Description: "列表 名称 servers 使用 通过 site。",
							Elem: &schema.Schema{
								Type: schema.TypeString,
							},
						},
						"name_servers": {
							Type:        schema.TypeSet,
							Required:    true,
							Description: "列表 名称 servers assigned 通过 Tencent Cloud。",
							Elem: &schema.Schema{
								Type: schema.TypeString,
							},
						},
						"status": {
							Type:        schema.TypeString,
							Required:    true,
							Description: "site 状态 Values: `活跃`: 名称 服务器 是 switched 到 EdgeOne. `pending`: 名称 服务器 是 不 switched. `moved`: 名称 服务器 是 changed 到 other 服务 providers. `deactivated`: site 是 blocked. `initializing`: site 是 不 bound 使用 any plan。",
						},
						"type": {
							Type:        schema.TypeString,
							Required:    true,
							Description: "Site 访问 方法. 有效值：full: NS 访问; partial: CNAME 访问; noDomainAccess: 访问 使用 无 域名 名称",
						},
						"paused": {
							Type:        schema.TypeBool,
							Required:    true,
							Description: "是否site 是 已禁用",
						},
						"cname_speed_up": {
							Type:        schema.TypeString,
							Required:    true,
							Description: "Whether CNAME acceleration 是 已启用 Values: `已启用`: 已启用; `已禁用`: 已禁用",
						},
						"cname_status": {
							Type:        schema.TypeString,
							Required:    true,
							Description: "CNAME 记录 访问 状态 Values: `finished`: site 是 verified.`pending`: site 是 being verified。",
						},
						"tags": {
							Type:        schema.TypeList,
							Required:    true,
							Description: "列表 资源 标签",
							Elem: &schema.Resource{
								Schema: map[string]*schema.Schema{
									"tag_key": {
										Type:        schema.TypeString,
										Required:    true,
										Description: "标签键 注意：此字段可能返回 null，表示无法获取有效值。",
									},
									"tag_value": {
										Type:        schema.TypeString,
										Required:    true,
										Description: "标签值 注意：此字段可能返回 null，表示无法获取有效值。",
									},
								},
							},
						},
						"resources": {
							Type:        schema.TypeList,
							Required:    true,
							Description: "列表 billable resources。",
							Elem: &schema.Resource{
								Schema: map[string]*schema.Schema{
									"id": {
										Type:        schema.TypeString,
										Required:    true,
										Description: "资源 ID。",
									},
									"pay_mode": {
										Type:        schema.TypeInt,
										Required:    true,
										Description: "Billing 模式，`0`: Pay-作为-您-go",
									},
									"create_time": {
										Type:        schema.TypeString,
										Required:    true,
										Description: "创建时间。",
									},
									"enable_time": {
										Type:        schema.TypeString,
										Required:    true,
										Description: "effective 时间。",
									},
									"expire_time": {
										Type:        schema.TypeString,
										Required:    true,
										Description: "过期时间。",
									},
									"status": {
										Type:        schema.TypeString,
										Required:    true,
										Description: "plan 状态 Values: `normal`: Normal; `isolated`: Isolated; `destroyed`: Terminated。",
									},
									"sv": {
										Type:        schema.TypeList,
										Required:    true,
										Description: "Pricing 查询 参数",
										Elem: &schema.Resource{
											Schema: map[string]*schema.Schema{
												"key": {
													Type:        schema.TypeString,
													Required:    true,
													Description: "参数 键",
												},
												"value": {
													Type:        schema.TypeString,
													Required:    true,
													Description: "参数 值",
												},
												"pack": {
													Type:        schema.TypeString,
													Optional:    true,
													Description: "Quota 对于 资源. Values: `可用区`: Quota 对于 sites; `自定义-规则`: Quota 对于 自定义 规则; `速率-limiting-规则`: Quota 对于 速率 limiting 规则; `l4-proxy-实例`: Quota 对于 L4 proxy 实例. 注意：此字段可能返回 null，表示无法获取有效值。",
												},
												"instance_id": {
													Type:        schema.TypeString,
													Optional:    true,
													Description: "ID L4 proxy 实例. 注意：此字段可能返回 null，表示无法获取有效值。",
												},
												"protection_specs": {
													Type:        schema.TypeString,
													Optional:    true,
													Description: "protection 规格. Values: `cm_30G`: 30 Gbps base protection 带宽 在 **Chinese mainland** 服务 area; `cm_60G`: 60 Gbps base protection 带宽 在 **Chinese mainland** 服务 area; `cm_100G`: 100 Gbps base protection 带宽 在 **Chinese mainland** 服务 area; `anycast_300G`: 300 Gbps Anycast-based protection 在 **Global (MLC)** 服务 area; `anycast_unlimited`: Unlimited Anycast-based protection 带宽 在 **Global (MLC)** 服务 area; `cm_30G_anycast_300G`: 30 Gbps base protection 带宽 在 **Chinese mainland** 服务 area 和 300 Gbps Anycast-based protection 带宽 在 **Global (MLC)** 服务 area; `cm_30G_anycast_unlimited`: 30 Gbps base protection 带宽 在 **Chinese mainland** 服务 area 和 unlimited Anycast-based protection 带宽 在 **Global (MLC)** 服务 area; cm_60G_anycast_300G`: 60 Gbps base protection 带宽 在 **Chinese mainland** 服务 area 和 300 Gbps Anycast-based protection 带宽 在 **Global (MLC)** 服务 area; cm_60G_anycast_unlimited`: 60 Gbps base protection 带宽 在 **Chinese mainland** 服务 area 和 unlimited Anycast-based protection 带宽 在 **Global (MLC)** 服务 area</li><li> `cm_100G_anycast_300G`: 100 Gbps base protection 带宽 在 **Chinese mainland** 服务 area 和 300 Gbps Anycast-based protection 带宽 在 **Global (MLC)** 服务 area，cm_100G_anycast_unlimited`: 100 Gbps base protection 带宽 在 **Chinese mainland** 服务 area 和 unlimited Anycast-based protection 带宽 在 **Global (MLC)** 服务 area. 注意：此字段可能返回 null，表示无法获取有效值。",
												},
											},
										},
									},
									"auto_renew_flag": {
										Type:        schema.TypeInt,
										Required:    true,
										Description: "是否enable auto-renewal. Values: `0`: Default 状态 `1`: Enable auto-renewal. `2`: Disable auto-renewal。",
									},
									"plan_id": {
										Type:        schema.TypeString,
										Required:    true,
										Description: "ID 资源 associated 使用 plan。",
									},
									"area": {
										Type:        schema.TypeString,
										Required:    true,
										Description: "Applicable area. Values: `mainland`: Chinese mainland; `overseas`: Regions outside Chinese mainland; `全局`: Global。",
									},
									"group": {
										Type:        schema.TypeString,
										Required:    true,
										Description: "资源类型 Values: `plan`: Plan resources; `pay-作为-您-go`: Pay-作为-您-go resources; `值-added`: 值-added resources. 注意：此字段可能返回 null，表示无法获取有效值。",
									},
									"zone_number": {
										Type:        schema.TypeInt,
										Required:    true,
										Description: "sites 该 是 associated 使用 当前 resources. 注意：此字段可能返回 null，表示无法获取有效值。",
									},
									"type": {
										Type:        schema.TypeString,
										Required:    true,
										Description: "Resource 标签 类型 有效值：vodeo: vodeo 资源。",
									},
								},
							},
						},
						"created_on": {
							Type:        schema.TypeString,
							Required:    true,
							Description: "创建时间 的 site。",
						},
						"modified_on": {
							Type:        schema.TypeString,
							Required:    true,
							Description: "modification date 的 site。",
						},
						"area": {
							Type:        schema.TypeString,
							Required:    true,
							Description: "site 访问 地域 Values: `全局`: Global. `mainland`: Chinese mainland. `overseas`: Outside Chinese mainland。",
						},
						"vanity_name_servers": {
							Type:        schema.TypeList,
							Required:    true,
							MaxItems:    1,
							Description: "自定义 名称 服务器 信息.\n注意：此字段可能返回 null，表示无法获取有效值。",
							Elem: &schema.Resource{
								Schema: map[string]*schema.Schema{
									"switch": {
										Type:        schema.TypeString,
										Required:    true,
										Description: "是否enable 自定义 名称 servers. Values: `在`: Enable; `关闭`: Disable。",
									},
									"servers": {
										Type:        schema.TypeSet,
										Optional:    true,
										Description: "列表 自定义 名称 servers",
										Elem: &schema.Schema{
											Type: schema.TypeString,
										},
									},
								},
							},
						},
						"vanity_name_servers_ips": {
							Type:        schema.TypeList,
							Required:    true,
							Description: "自定义 名称 服务器 IP 信息. 注意：此字段可能返回 null，表示无法获取有效值。",
							Elem: &schema.Resource{
								Schema: map[string]*schema.Schema{
									"name": {
										Type:        schema.TypeString,
										Required:    true,
										Description: "Custom 名称 名称 服务器",
									},
									"i_pv4": {
										Type:        schema.TypeString,
										Required:    true,
										Description: "IPv4 地址 的 自定义 名称 服务器",
									},
								},
							},
						},
						"active_status": {
							Type:        schema.TypeString,
							Required:    true,
							Description: "状态 proxy. Values: `活跃`: 已启用; `inactive`: Not activated; `paused`: 已禁用",
						},
						"alias_zone_name": {
							Type:        schema.TypeString,
							Required:    true,
							Description: "site alias. It 可以 是 up 到 20 字符 consisting 的 digits，letters，hyphens (-) 和 underscores (_). 注意：此字段可能返回 null，表示无法获取有效值。",
						},
						"is_fake": {
							Type:        schema.TypeInt,
							Required:    true,
							Description: "是否为a fake site. 有效值：`0`: Non-fake site; `1`: Fake site。",
						},
						"lock_status": {
							Type:        schema.TypeString,
							Required:    true,
							Description: "Lock 状态 Values: `启用`: Normal. Modification 是 allowed. `disable`: Locked. Modification 是 不 allowed. `plan_migrate`: Adjusting plan. Modification 是 不 allowed。",
						},
						"ownership_verification": {
							Type:        schema.TypeList,
							Required:    true,
							MaxItems:    1,
							Description: "Ownership verification 信息. 注意：此字段可能返回 null，表示无法获取有效值。",
							Elem: &schema.Resource{
								Schema: map[string]*schema.Schema{
									"dns_verification": {
										Type:        schema.TypeList,
										Required:    true,
										MaxItems:    1,
										Description: "CNAME，当 there 是 无 域名 名称 访问， 信息 必填 对于 DNS resolution verification 是 使用. For details，refer 到 [Site/域名 Ownership Verification\n](https://intl.云.tencent.com/document/product/1552/70789?from_cn_redirect=1#7af6ecf8-afca-4e35-8811-b5797ed1bde5). 注意: 此 字段 可能 返回 null，其中 表示a failure 到 obtain 有效 值",
										Elem: &schema.Resource{
											Schema: map[string]*schema.Schema{
												"subdomain": {
													Type:        schema.TypeString,
													Required:    true,
													Description: "主机 记录。",
												},
												"record_type": {
													Type:        schema.TypeString,
													Required:    true,
													Description: "记录 类型",
												},
												"record_value": {
													Type:        schema.TypeString,
													Required:    true,
													Description: "记录 值",
												},
											},
										},
									},
									"file_verification": {
										Type:        schema.TypeList,
										Required:    true,
										MaxItems:    1,
										Description: "CNAME，当 there 是 无 域名 名称 访问， 信息 必填 对于 文件 verification 是 使用. For details，refer 到 [Site/域名 Ownership Verification\n](https://intl.云.tencent.com/document/product/1552/70789?from_cn_redirect=1#7af6ecf8-afca-4e35-8811-b5797ed1bde5). 注意: 此 字段 可能 返回 null，其中 表示a failure 到 obtain 有效 值",
										Elem: &schema.Resource{
											Schema: map[string]*schema.Schema{
												"path": {
													Type:        schema.TypeString,
													Required:    true,
													Description: "EdgeOne obtains 文件 verification 信息 在 格式 的 \"Scheme + Host + URL Path\", (e.g. https://www.示例.com/.well-known/teo-verification/z12h416twn.txt). 此 字段 是 URL 路径 section 的 URL 您 need 到 create.",
												},
												"content": {
													Type:        schema.TypeString,
													Required:    true,
													Description: "内容 的 verification 文件. contents 的 此 字段 need 到 是 filled into text 文件 返回 通过 `路径`。",
												},
											},
										},
									},
									"ns_verification": {
										Type:        schema.TypeList,
										Required:    true,
										MaxItems:    1,
										Description: "u200cInformation 必填 对于 switching DNS servers. It's applicable 到 sites connected via NSs. For details，see [Modifying DNS Server](https://intl.云.tencent.com/document/product/1552/90452?from_cn_redirect=1).\nNote: 此 字段 可能 返回·null，indicating 该 无 有效 值 可以 是 获取。",
										Elem: &schema.Resource{
											Schema: map[string]*schema.Schema{
												"name_servers": {
													Type:        schema.TypeSet,
													Required:    true,
													Description: "DNS 服务器 地址 assigned 到 用户 当 connecting site 到 EO via NS. You need 到 switch NameServer 的 域名 名称 到 此 地址",
													Elem: &schema.Schema{
														Type: schema.TypeString,
													},
												},
											},
										},
									},
								},
							},
						},
					},
				},
			},

			"result_output_file": {
				Type:        schema.TypeString,
				Optional:    true,
				Description: "用于保存结果。",
			},
		},
	}
}

func dataSourceTencentCloudTeoZonesRead(d *schema.ResourceData, meta interface{}) error {
	defer tccommon.LogElapsed("data_source.tencentcloud_teo_zones.read")()
	defer tccommon.InconsistentCheck(d, meta)()

	logId := tccommon.GetLogId(nil)
	ctx := tccommon.NewResourceLifeCycleHandleFuncContext(context.Background(), logId, d, meta)

	service := TeoService{client: meta.(tccommon.ProviderMeta).GetAPIV3Conn()}

	paramMap := make(map[string]interface{})
	if v, ok := d.GetOk("filters"); ok {
		filtersSet := v.([]interface{})
		tmpSet := make([]*teov20220901.AdvancedFilter, 0, len(filtersSet))
		for _, item := range filtersSet {
			filtersMap := item.(map[string]interface{})
			advancedFilter := teov20220901.AdvancedFilter{}
			if v, ok := filtersMap["name"].(string); ok && v != "" {
				advancedFilter.Name = helper.String(v)
			}
			if v, ok := filtersMap["values"]; ok {
				valuesSet := v.(*schema.Set).List()
				for i := range valuesSet {
					values := valuesSet[i].(string)
					advancedFilter.Values = append(advancedFilter.Values, helper.String(values))
				}
			}
			if v, ok := filtersMap["fuzzy"].(bool); ok {
				advancedFilter.Fuzzy = helper.Bool(v)
			}
			tmpSet = append(tmpSet, &advancedFilter)
		}
		paramMap["Filters"] = tmpSet
	}

	if v, ok := d.GetOk("order"); ok {
		paramMap["Order"] = helper.String(v.(string))
	}

	if v, ok := d.GetOk("direction"); ok {
		paramMap["Direction"] = helper.String(v.(string))
	}

	var respData []*teov20220901.Zone
	reqErr := resource.Retry(tccommon.ReadRetryTimeout, func() *resource.RetryError {
		result, e := service.DescribeTeoZonesByFilter(ctx, paramMap)
		if e != nil {
			return tccommon.RetryError(e)
		}
		respData = result
		return nil
	})
	if reqErr != nil {
		return reqErr
	}

	var zoneIds []string
	zonesList := make([]map[string]interface{}, 0, len(respData))
	if respData != nil {
		for _, zones := range respData {
			zonesMap := map[string]interface{}{}

			var zoneId string
			if zones.ZoneId != nil {
				zonesMap["zone_id"] = zones.ZoneId
				zoneId = *zones.ZoneId
			}

			if zones.ZoneName != nil {
				zonesMap["zone_name"] = zones.ZoneName
			}

			if zones.OriginalNameServers != nil {
				zonesMap["original_name_servers"] = zones.OriginalNameServers
			}

			if zones.NameServers != nil {
				zonesMap["name_servers"] = zones.NameServers
			}

			if zones.Status != nil {
				zonesMap["status"] = zones.Status
			}

			if zones.Type != nil {
				zonesMap["type"] = zones.Type
			}

			if zones.Paused != nil {
				zonesMap["paused"] = zones.Paused
			}

			if zones.CnameSpeedUp != nil {
				zonesMap["cname_speed_up"] = zones.CnameSpeedUp
			}

			if zones.CnameStatus != nil {
				zonesMap["cname_status"] = zones.CnameStatus
			}

			tagsList := make([]map[string]interface{}, 0, len(zones.Tags))
			if zones.Tags != nil {
				for _, tags := range zones.Tags {
					tagsMap := map[string]interface{}{}

					if tags.TagKey != nil {
						tagsMap["tag_key"] = tags.TagKey
					}

					if tags.TagValue != nil {
						tagsMap["tag_value"] = tags.TagValue
					}

					tagsList = append(tagsList, tagsMap)
				}

				zonesMap["tags"] = tagsList
			}
			resourcesList := make([]map[string]interface{}, 0, len(zones.Resources))
			if zones.Resources != nil {
				for _, resources := range zones.Resources {
					resourcesMap := map[string]interface{}{}

					if resources.Id != nil {
						resourcesMap["id"] = resources.Id
					}

					if resources.PayMode != nil {
						resourcesMap["pay_mode"] = resources.PayMode
					}

					if resources.CreateTime != nil {
						resourcesMap["create_time"] = resources.CreateTime
					}

					if resources.EnableTime != nil {
						resourcesMap["enable_time"] = resources.EnableTime
					}

					if resources.ExpireTime != nil {
						resourcesMap["expire_time"] = resources.ExpireTime
					}

					if resources.Status != nil {
						resourcesMap["status"] = resources.Status
					}

					svList := make([]map[string]interface{}, 0, len(resources.Sv))
					if resources.Sv != nil {
						for _, sv := range resources.Sv {
							svMap := map[string]interface{}{}

							if sv.Key != nil {
								svMap["key"] = sv.Key
							}

							if sv.Value != nil {
								svMap["value"] = sv.Value
							}

							if sv.Pack != nil {
								svMap["pack"] = sv.Pack
							}

							if sv.InstanceId != nil {
								svMap["instance_id"] = sv.InstanceId
							}

							if sv.ProtectionSpecs != nil {
								svMap["protection_specs"] = sv.ProtectionSpecs
							}

							svList = append(svList, svMap)
						}

						resourcesMap["sv"] = svList
					}
					if resources.AutoRenewFlag != nil {
						resourcesMap["auto_renew_flag"] = resources.AutoRenewFlag
					}

					if resources.PlanId != nil {
						resourcesMap["plan_id"] = resources.PlanId
					}

					if resources.Area != nil {
						resourcesMap["area"] = resources.Area
					}

					if resources.Group != nil {
						resourcesMap["group"] = resources.Group
					}

					if resources.ZoneNumber != nil {
						resourcesMap["zone_number"] = resources.ZoneNumber
					}

					if resources.Type != nil {
						resourcesMap["type"] = resources.Type
					}

					resourcesList = append(resourcesList, resourcesMap)
				}

				zonesMap["resources"] = resourcesList
			}
			if zones.CreatedOn != nil {
				zonesMap["created_on"] = zones.CreatedOn
			}

			if zones.ModifiedOn != nil {
				zonesMap["modified_on"] = zones.ModifiedOn
			}

			if zones.Area != nil {
				zonesMap["area"] = zones.Area
			}

			vanityNameServersMap := map[string]interface{}{}

			if zones.VanityNameServers != nil {
				if zones.VanityNameServers.Switch != nil {
					vanityNameServersMap["switch"] = zones.VanityNameServers.Switch
				}

				if zones.VanityNameServers.Servers != nil {
					vanityNameServersMap["servers"] = zones.VanityNameServers.Servers
				}

				zonesMap["vanity_name_servers"] = []interface{}{vanityNameServersMap}
			}

			vanityNameServersIpsList := make([]map[string]interface{}, 0, len(zones.VanityNameServersIps))
			if zones.VanityNameServersIps != nil {
				for _, vanityNameServersIps := range zones.VanityNameServersIps {
					vanityNameServersIpsMap := map[string]interface{}{}

					if vanityNameServersIps.Name != nil {
						vanityNameServersIpsMap["name"] = vanityNameServersIps.Name
					}

					if vanityNameServersIps.IPv4 != nil {
						vanityNameServersIpsMap["i_pv4"] = vanityNameServersIps.IPv4
					}

					vanityNameServersIpsList = append(vanityNameServersIpsList, vanityNameServersIpsMap)
				}

				zonesMap["vanity_name_servers_ips"] = vanityNameServersIpsList
			}
			if zones.ActiveStatus != nil {
				zonesMap["active_status"] = zones.ActiveStatus
			}

			if zones.AliasZoneName != nil {
				zonesMap["alias_zone_name"] = zones.AliasZoneName
			}

			if zones.IsFake != nil {
				zonesMap["is_fake"] = zones.IsFake
			}

			if zones.LockStatus != nil {
				zonesMap["lock_status"] = zones.LockStatus
			}

			ownershipVerificationMap := map[string]interface{}{}

			if zones.OwnershipVerification != nil {
				dnsVerificationMap := map[string]interface{}{}

				if zones.OwnershipVerification.DnsVerification != nil {
					if zones.OwnershipVerification.DnsVerification.Subdomain != nil {
						dnsVerificationMap["subdomain"] = zones.OwnershipVerification.DnsVerification.Subdomain
					}

					if zones.OwnershipVerification.DnsVerification.RecordType != nil {
						dnsVerificationMap["record_type"] = zones.OwnershipVerification.DnsVerification.RecordType
					}

					if zones.OwnershipVerification.DnsVerification.RecordValue != nil {
						dnsVerificationMap["record_value"] = zones.OwnershipVerification.DnsVerification.RecordValue
					}

					ownershipVerificationMap["dns_verification"] = []interface{}{dnsVerificationMap}
				}

				fileVerificationMap := map[string]interface{}{}

				if zones.OwnershipVerification.FileVerification != nil {
					if zones.OwnershipVerification.FileVerification.Path != nil {
						fileVerificationMap["path"] = zones.OwnershipVerification.FileVerification.Path
					}

					if zones.OwnershipVerification.FileVerification.Content != nil {
						fileVerificationMap["content"] = zones.OwnershipVerification.FileVerification.Content
					}

					ownershipVerificationMap["file_verification"] = []interface{}{fileVerificationMap}
				}

				nsVerificationMap := map[string]interface{}{}

				if zones.OwnershipVerification.NsVerification != nil {
					if zones.OwnershipVerification.NsVerification.NameServers != nil {
						nsVerificationMap["name_servers"] = zones.OwnershipVerification.NsVerification.NameServers
					}

					ownershipVerificationMap["ns_verification"] = []interface{}{nsVerificationMap}
				}

				zonesMap["ownership_verification"] = []interface{}{ownershipVerificationMap}
			}

			zoneIds = append(zoneIds, zoneId)
			zonesList = append(zonesList, zonesMap)
		}

		_ = d.Set("zones", zonesList)
	}

	d.SetId(helper.DataResourceIdsHash(zoneIds))

	output, ok := d.GetOk("result_output_file")
	if ok && output.(string) != "" {
		if e := tccommon.WriteToFile(output.(string), zonesList); e != nil {
			return e
		}
	}

	return nil
}
