// Code generated by iacg; DO NOT EDIT.
package teo

import (
	"context"

	"github.com/hashicorp/terraform-plugin-sdk/v2/helper/resource"
	"github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema"
	teo "github.com/tencentcloud/tencentcloud-sdk-go/tencentcloud/teo/v20220901"

	tccommon "github.com/tencentcloudstack/terraform-provider-tencentcloud/tencentcloud/common"
	"github.com/tencentcloudstack/terraform-provider-tencentcloud/tencentcloud/internal/helper"
)

func DataSourceTencentCloudTeoRuleEngineSettings() *schema.Resource {
	return &schema.Resource{
		Read: dataSourceTencentCloudTeoRuleEngineSettingsRead,
		Schema: map[string]*schema.Schema{
			"actions": {
				Type:        schema.TypeList,
				Computed:    true,
				Description: "Detail info 的 actions 其中 可以 是 使用 在 规则 引擎。",
				Elem: &schema.Resource{
					Schema: map[string]*schema.Schema{
						"action": {
							Type:        schema.TypeString,
							Computed:    true,
							Description: "操作 名称",
						},
						"properties": {
							Type:        schema.TypeList,
							Computed:    true,
							Description: "操作 properties。",
							Elem: &schema.Resource{
								Schema: map[string]*schema.Schema{
									"name": {
										Type:        schema.TypeString,
										Computed:    true,
										Description: "属性名称",
									},
									"type": {
										Type:        schema.TypeString,
										Computed:    true,
										Description: "属性值 类型 有效 值:- `CHOICE`: enum 类型，必须 select 一个 的 值 在 `ChoicesValue`.- `TOGGLE`: switch 类型，必须 select 一个 的 值 在 `ChoicesValue`.- `OBJECT`: 对象 类型， `ChoiceProperties` 列表 all properties 的 对象.- `CUSTOM_NUM`: 整数 类型- `CUSTOM_STRING`: 字符串 类型",
									},
									"choices_value": {
										Type:        schema.TypeSet,
										Computed:    true,
										Description: "choices 其中 可以 是 使用. 此 列表 可能 是 空。",
										Elem: &schema.Schema{
											Type: schema.TypeString,
										},
									},
									"min": {
										Type:        schema.TypeInt,
										Computed:    true,
										Description: "Min 整数 值 可以 bse 使用 当 属性 类型 是 `CUSTOM_NUM`. 当 `Min` 和 `Max` both 是 0，此 字段 是 meaningless。",
									},
									"max": {
										Type:        schema.TypeInt,
										Computed:    true,
										Description: "Max 整数 值 可以 bse 使用 当 属性 类型 是 `CUSTOM_NUM`. 当 `Min` 和 `Max` both 是 0，此 字段 是 meaningless。",
									},
									"is_multiple": {
										Type:        schema.TypeBool,
										Computed:    true,
										Description: "Whether 此 属性 是 allowed 到 集合 多个 值。",
									},
									"is_allow_empty": {
										Type:        schema.TypeBool,
										Computed:    true,
										Description: "Whether 此 属性 是 allowed 到 集合 空。",
									},
									"choice_properties": {
										Type:        schema.TypeList,
										Computed:    true,
										Description: "Associative properties 的 此 属性，they 是 all 必填 注意：此字段可能返回 null，表示无法获取有效值。",
										Elem: &schema.Resource{
											Schema: map[string]*schema.Schema{
												"name": {
													Type:        schema.TypeString,
													Computed:    true,
													Description: "属性名称",
												},
												"type": {
													Type:        schema.TypeString,
													Computed:    true,
													Description: "属性值 类型 有效 值:- `CHOICE`: enum 类型，必须 select 一个 的 值 在 `ChoicesValue`.- `TOGGLE`: switch 类型，必须 select 一个 的 值 在 `ChoicesValue`.- `OBJECT`: 对象 类型， `ChoiceProperties` 列表 all properties 的 对象.- `CUSTOM_NUM`: 整数 类型- `CUSTOM_STRING`: 字符串 类型",
												},
												"choices_value": {
													Type:        schema.TypeSet,
													Computed:    true,
													Description: "choices 其中 可以 是 使用. 此 列表 可能 是 空。",
													Elem: &schema.Schema{
														Type: schema.TypeString,
													},
												},
												"min": {
													Type:        schema.TypeInt,
													Computed:    true,
													Description: "Min 整数 值 可以 bse 使用 当 属性 类型 是 `CUSTOM_NUM`. 当 `Min` 和 `Max` both 是 0，此 字段 是 meaningless。",
												},
												"max": {
													Type:        schema.TypeInt,
													Computed:    true,
													Description: "Max 整数 值 可以 bse 使用 当 属性 类型 是 `CUSTOM_NUM`. 当 `Min` 和 `Max` both 是 0，此 字段 是 meaningless。",
												},
												"is_multiple": {
													Type:        schema.TypeBool,
													Computed:    true,
													Description: "Whether 此 属性 是 allowed 到 集合 多个 值。",
												},
												"is_allow_empty": {
													Type:        schema.TypeBool,
													Computed:    true,
													Description: "Whether 此 属性 是 allowed 到 集合 空。",
												},
												"extra_parameter": {
													Type:        schema.TypeList,
													Computed:    true,
													Description: "Special 参数. 注意：此字段可能返回 null，表示无法获取有效值。",
													Elem: &schema.Resource{
														Schema: map[string]*schema.Schema{
															"id": {
																Type:        schema.TypeString,
																Computed:    true,
																Description: "Parameter 名称 有效 值:- `操作`: 此 extra 参数 为必填项 当 modify HTTP 头部，此 操作 should 是 `RewriteAction`.- `StatusCode`: 此 extra 参数 为必填项 当 modify HTTP 状态 代码，此 操作 should 是 `CodeAction`.- `NULL`: 此 操作 should 是 `NormalAction`。",
															},
															"type": {
																Type:        schema.TypeString,
																Computed:    true,
																Description: "Parameter 值 类型 有效 值:- `CHOICE`: select 一个 值 从 `Choices`.- `CUSTOM_NUM`: 整数 值- `CUSTOM_STRING`: 字符串 值",
															},
															"choices": {
																Type:        schema.TypeSet,
																Computed:    true,
																Description: "A 列表 choices 其中 可以 是 使用 当 `类型` 是 `CHOICE`。",
																Elem: &schema.Schema{
																	Type: schema.TypeString,
																},
															},
														},
													},
												},
											},
										},
									},
									"extra_parameter": {
										Type:        schema.TypeList,
										Computed:    true,
										Description: "Special 参数. 注意：此字段可能返回 null，表示无法获取有效值。",
										Elem: &schema.Resource{
											Schema: map[string]*schema.Schema{
												"id": {
													Type:        schema.TypeString,
													Computed:    true,
													Description: "Parameter 名称 有效 值:- `操作`: 此 extra 参数 为必填项 当 modify HTTP 头部，此 操作 should 是 `RewriteAction`.- `StatusCode`: 此 extra 参数 为必填项 当 modify HTTP 状态 代码，此 操作 should 是 `CodeAction`.- `NULL`: 此 操作 should 是 `NormalAction`。",
												},
												"type": {
													Type:        schema.TypeString,
													Computed:    true,
													Description: "Parameter 值 类型 有效 值:- `CHOICE`: select 一个 值 从 `Choices`.- `CUSTOM_NUM`: 整数 值- `CUSTOM_STRING`: 字符串 值",
												},
												"choices": {
													Type:        schema.TypeSet,
													Computed:    true,
													Description: "A 列表 choices 其中 可以 是 使用 当 `类型` 是 `CHOICE`。",
													Elem: &schema.Schema{
														Type: schema.TypeString,
													},
												},
											},
										},
									},
								},
							},
						},
					},
				},
			},

			"result_output_file": {
				Type:        schema.TypeString,
				Optional:    true,
				Description: "用于保存结果。",
			},
		},
	}
}

func dataSourceTencentCloudTeoRuleEngineSettingsRead(d *schema.ResourceData, meta interface{}) error {
	defer tccommon.LogElapsed("data_source.tencentcloud_teo_rule_engine_settings.read")()
	defer tccommon.InconsistentCheck(d, meta)()

	logId := tccommon.GetLogId(nil)
	ctx := tccommon.NewResourceLifeCycleHandleFuncContext(context.Background(), logId, d, meta)

	service := TeoService{client: meta.(tccommon.ProviderMeta).GetAPIV3Conn()}

	paramMap := make(map[string]interface{})
	var respData []*teo.RulesSettingAction
	err := resource.Retry(tccommon.ReadRetryTimeout, func() *resource.RetryError {
		result, e := service.DescribeTeoRuleEngineSettingsByFilter(ctx, paramMap)
		if e != nil {
			return tccommon.RetryError(e)
		}
		respData = result
		return nil
	})
	if err != nil {
		return err
	}

	actionsId := make([]string, 0, len(respData))
	actionsList := make([]map[string]interface{}, 0, len(respData))
	if respData != nil {
		for _, actions := range respData {
			actionsMap := map[string]interface{}{}

			var action string
			if actions.Action != nil {
				actionsMap["action"] = actions.Action
				action = *actions.Action
			}

			propertiesList := make([]map[string]interface{}, 0, len(actions.Properties))
			if actions.Properties != nil {
				for _, properties := range actions.Properties {
					propertiesMap := map[string]interface{}{}

					if properties.Name != nil {
						propertiesMap["name"] = properties.Name
					}

					if properties.Type != nil {
						propertiesMap["type"] = properties.Type
					}

					if properties.ChoicesValue != nil {
						propertiesMap["choices_value"] = properties.ChoicesValue
					}

					if properties.Min != nil {
						propertiesMap["min"] = properties.Min
					}

					if properties.Max != nil {
						propertiesMap["max"] = properties.Max
					}

					if properties.IsMultiple != nil {
						propertiesMap["is_multiple"] = properties.IsMultiple
					}

					if properties.IsAllowEmpty != nil {
						propertiesMap["is_allow_empty"] = properties.IsAllowEmpty
					}

					choicePropertiesList := make([]map[string]interface{}, 0, len(properties.ChoiceProperties))
					if properties.ChoiceProperties != nil {
						for _, choiceProperties := range properties.ChoiceProperties {
							choicePropertiesMap := map[string]interface{}{}

							if choiceProperties.Name != nil {
								choicePropertiesMap["name"] = choiceProperties.Name
							}

							if choiceProperties.Type != nil {
								choicePropertiesMap["type"] = choiceProperties.Type
							}

							if choiceProperties.ChoicesValue != nil {
								choicePropertiesMap["choices_value"] = choiceProperties.ChoicesValue
							}

							if choiceProperties.Min != nil {
								choicePropertiesMap["min"] = choiceProperties.Min
							}

							if choiceProperties.Max != nil {
								choicePropertiesMap["max"] = choiceProperties.Max
							}

							if choiceProperties.IsMultiple != nil {
								choicePropertiesMap["is_multiple"] = choiceProperties.IsMultiple
							}

							if choiceProperties.IsAllowEmpty != nil {
								choicePropertiesMap["is_allow_empty"] = choiceProperties.IsAllowEmpty
							}

							extraParameterMap := map[string]interface{}{}

							if choiceProperties.ExtraParameter != nil {
								if choiceProperties.ExtraParameter.Id != nil {
									extraParameterMap["id"] = choiceProperties.ExtraParameter.Id
								}

								if choiceProperties.ExtraParameter.Type != nil {
									extraParameterMap["type"] = choiceProperties.ExtraParameter.Type
								}

								if choiceProperties.ExtraParameter.Choices != nil {
									extraParameterMap["choices"] = choiceProperties.ExtraParameter.Choices
								}

								choicePropertiesMap["extra_parameter"] = []interface{}{extraParameterMap}
							}

							choicePropertiesList = append(choicePropertiesList, choicePropertiesMap)
						}

						propertiesMap["choice_properties"] = choicePropertiesList
					}
					extraParameterMap := map[string]interface{}{}

					if properties.ExtraParameter != nil {
						if properties.ExtraParameter.Id != nil {
							extraParameterMap["id"] = properties.ExtraParameter.Id
						}

						if properties.ExtraParameter.Type != nil {
							extraParameterMap["type"] = properties.ExtraParameter.Type
						}

						if properties.ExtraParameter.Choices != nil {
							extraParameterMap["choices"] = properties.ExtraParameter.Choices
						}

						propertiesMap["extra_parameter"] = []interface{}{extraParameterMap}
					}

					propertiesList = append(propertiesList, propertiesMap)
				}

				actionsMap["properties"] = propertiesList
			}
			actionsId = append(actionsId, action)
			actionsList = append(actionsList, actionsMap)
		}

		_ = d.Set("actions", actionsList)
	}

	d.SetId(helper.DataResourceIdsHash(actionsId))

	output, ok := d.GetOk("result_output_file")
	if ok && output.(string) != "" {
		if e := tccommon.WriteToFile(output.(string), actionsList); e != nil {
			return e
		}
	}

	return nil
}
