// Code generated by iacg; DO NOT EDIT.
package teo

import (
	"context"
	"fmt"
	"log"
	"strings"

	"github.com/hashicorp/terraform-plugin-sdk/v2/helper/resource"
	"github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema"
	sdkErrors "github.com/tencentcloud/tencentcloud-sdk-go/tencentcloud/common/errors"
	teov20220901 "github.com/tencentcloud/tencentcloud-sdk-go/tencentcloud/teo/v20220901"

	tccommon "github.com/tencentcloudstack/terraform-provider-tencentcloud/tencentcloud/common"
	"github.com/tencentcloudstack/terraform-provider-tencentcloud/tencentcloud/internal/helper"
)

func ResourceTencentCloudTeoFunctionRule() *schema.Resource {
	return &schema.Resource{
		Create: resourceTencentCloudTeoFunctionRuleCreate,
		Read:   resourceTencentCloudTeoFunctionRuleRead,
		Update: resourceTencentCloudTeoFunctionRuleUpdate,
		Delete: resourceTencentCloudTeoFunctionRuleDelete,
		Importer: &schema.ResourceImporter{
			State: schema.ImportStatePassthrough,
		},
		Schema: map[string]*schema.Schema{
			"zone_id": {
				Type:        schema.TypeString,
				Required:    true,
				ForceNew:    true,
				Description: "站点 ID。",
			},

			"rule_id": {
				Type:        schema.TypeString,
				Computed:    true,
				Description: "边缘函数触发规则 ID。",
			},

			"function_id": {
				Type:        schema.TypeString,
				Required:    true,
				ForceNew:    true,
				Description: "边缘函数 ID。",
			},

			"remark": {
				Type:        schema.TypeString,
				Optional:    true,
				Description: "规则描述，最大支持 60 个字符。",
			},

			"function_name": {
				Type:        schema.TypeString,
				Computed:    true,
				Description: "函数名称。",
			},

			"priority": {
				Type:        schema.TypeInt,
				Computed:    true,
				Description: "函数触发规则的优先级，数值越大优先级越高。",
			},

			"function_rule_conditions": {
				Type:        schema.TypeList,
				Required:    true,
				Description: "规则条件列表，条件之间为「或」关系。",
				Elem: &schema.Resource{
					Schema: map[string]*schema.Schema{
						"rule_conditions": {
							Type:        schema.TypeList,
							Required:    true,
							Description: "边缘函数触发规则条件，当列表内所有条件都满足时，该条件才认为满足。",
							Elem: &schema.Resource{
								Schema: map[string]*schema.Schema{
									"operator": {
										Type:        schema.TypeString,
										Required:    true,
										Description: "操作符。取值有：\n  - `equals`：等于。\n  - `notEquals`：不等于。\n  - `exist`：存在。\n  - `notexist`：不存在。",
									},
									"target": {
										Type:        schema.TypeString,
										Required:    true,
										Description: "匹配类型。取值有：\n  - `filename`：文件名。\n  - `extension`：文件扩展名。\n  - `host`：主机。\n  - `full_url`：完整 URL，即当前站点下的完整 URL 路径，必须包含 HTTP 协议、主机和路径。\n  - `url`：当前站点下的部分 URL。\n  - `client_country`：客户端国家/地区。\n  - `query_string`：请求 URL 中的查询字符串。\n  - `request_header`：HTTP 请求头。",
									},
									"values": {
										Type:        schema.TypeSet,
										Optional:    true,
										Description: "匹配类型的参数值。仅当 `Target=query_string/request_header` 且 `Operator=exist/notexist` 时允许为空。\n  - 当 `Target=extension` 时，输入文件扩展名，如 \"jpg\"、\"txt\"。\n  - 当 `Target=filename` 时，输入文件名，如 \"foo.jpg\" 中的 \"foo\"。\n  - 当 `Target=all` 时，表示任意站点请求。\n  - 当 `Target=host` 时，输入当前站点下的主机名，如 \"www.maxx55.com\"。\n  - 当 `Target=url` 时，输入当前站点下的部分 URL 路径，如 \"/example\"。\n  - 当 `Target=full_url` 时，输入当前站点下的完整 URL，必须包含 HTTP 协议、主机和路径，如 \"https://www.maxx55.cn/example\"。\n  - 当 `Target=client_country` 时，输入 ISO-3166 国家/地区代码。\n  - 当 `Target=query_string` 时，输入查询字符串的值，如 \"lang=cn&version=1\" 中的 \"cn\" 和 \"1\"。\n  - 当 `Target=request_header` 时，输入 HTTP 请求头的值，如 \"Accept-Language:zh-CN,zh;q=0.9\" 头中的 \"zh-CN,zh;q=0.9\"。",
										Elem: &schema.Schema{
											Type: schema.TypeString,
										},
									},
									"ignore_case": {
										Type:        schema.TypeBool,
										Optional:    true,
										Description: "参数值是否忽略大小写。默认值：false。",
									},
									"name": {
										Type:        schema.TypeString,
										Optional:    true,
										Description: "匹配类型的参数名称。仅当 `Target=query_string/request_header` 时需要填写。\n  - `query_string`：查询字符串的名称，如 \"lang=cn&version=1\" 中的 \"lang\" 和 \"version\"。\n  - `request_header`：HTTP 请求头的名称，如 \"Accept-Language:zh-CN,zh;q=0.9\" 头中的 \"Accept-Language\"。",
									},
								},
							},
						},
					},
				},
			},
		},
	}
}

func resourceTencentCloudTeoFunctionRuleCreate(d *schema.ResourceData, meta interface{}) error {
	defer tccommon.LogElapsed("resource.tencentcloud_teo_function_rule.create")()
	defer tccommon.InconsistentCheck(d, meta)()

	logId := tccommon.GetLogId(tccommon.ContextNil)

	ctx := tccommon.NewResourceLifeCycleHandleFuncContext(context.Background(), logId, d, meta)

	var (
		zoneId     string
		functionId string
		ruleId     string
	)
	var (
		request  = teov20220901.NewCreateFunctionRuleRequest()
		response = teov20220901.NewCreateFunctionRuleResponse()
	)

	if v, ok := d.GetOk("zone_id"); ok {
		zoneId = v.(string)
	}
	if v, ok := d.GetOk("function_id"); ok {
		functionId = v.(string)
	}

	request.ZoneId = helper.String(zoneId)

	if v, ok := d.GetOk("function_rule_conditions"); ok {
		for _, item := range v.([]interface{}) {
			functionRuleConditionsMap := item.(map[string]interface{})
			functionRuleCondition := teov20220901.FunctionRuleCondition{}
			if v, ok := functionRuleConditionsMap["rule_conditions"]; ok {
				for _, item := range v.([]interface{}) {
					ruleConditionsMap := item.(map[string]interface{})
					ruleCondition := teov20220901.RuleCondition{}
					if v, ok := ruleConditionsMap["operator"]; ok {
						ruleCondition.Operator = helper.String(v.(string))
					}
					if v, ok := ruleConditionsMap["target"]; ok {
						ruleCondition.Target = helper.String(v.(string))
					}
					if v, ok := ruleConditionsMap["values"]; ok {
						valuesSet := v.(*schema.Set).List()
						for i := range valuesSet {
							values := valuesSet[i].(string)
							ruleCondition.Values = append(ruleCondition.Values, helper.String(values))
						}
					}
					if v, ok := ruleConditionsMap["ignore_case"]; ok {
						ruleCondition.IgnoreCase = helper.Bool(v.(bool))
					}
					if v, ok := ruleConditionsMap["name"]; ok {
						ruleCondition.Name = helper.String(v.(string))
					}
					functionRuleCondition.RuleConditions = append(functionRuleCondition.RuleConditions, &ruleCondition)
				}
			}
			request.FunctionRuleConditions = append(request.FunctionRuleConditions, &functionRuleCondition)
		}
	}

	request.FunctionId = helper.String(functionId)

	if v, ok := d.GetOk("remark"); ok {
		request.Remark = helper.String(v.(string))
	}

	err := resource.Retry(tccommon.WriteRetryTimeout, func() *resource.RetryError {
		result, e := meta.(tccommon.ProviderMeta).GetAPIV3Conn().UseTeoV20220901Client().CreateFunctionRuleWithContext(ctx, request)
		if e != nil {
			if sdkerr, ok := e.(*sdkErrors.TencentCloudSDKError); ok {
				if sdkerr.Code == "ResourceUnavailable.FunctionNotFound" {
					return resource.NonRetryableError(e)
				}
			}
			return tccommon.RetryError(e)
		} else {
			log.Printf("[DEBUG]%s api[%s] success, request body [%s], response body [%s]\n", logId, request.GetAction(), request.ToJsonString(), result.ToJsonString())
		}
		response = result
		return nil
	})
	if err != nil {
		log.Printf("[CRITAL]%s create teo function rule failed, reason:%+v", logId, err)
		return err
	}

	ruleId = *response.Response.RuleId

	d.SetId(strings.Join([]string{zoneId, functionId, ruleId}, tccommon.FILED_SP))

	return resourceTencentCloudTeoFunctionRuleRead(d, meta)
}

func resourceTencentCloudTeoFunctionRuleRead(d *schema.ResourceData, meta interface{}) error {
	defer tccommon.LogElapsed("resource.tencentcloud_teo_function_rule.read")()
	defer tccommon.InconsistentCheck(d, meta)()

	logId := tccommon.GetLogId(tccommon.ContextNil)

	ctx := tccommon.NewResourceLifeCycleHandleFuncContext(context.Background(), logId, d, meta)

	service := TeoService{client: meta.(tccommon.ProviderMeta).GetAPIV3Conn()}

	idSplit := strings.Split(d.Id(), tccommon.FILED_SP)
	if len(idSplit) != 3 {
		return fmt.Errorf("id is broken,%s", d.Id())
	}
	zoneId := idSplit[0]
	functionId := idSplit[1]
	ruleId := idSplit[2]

	_ = d.Set("zone_id", zoneId)

	_ = d.Set("function_id", functionId)

	respData, err := service.DescribeTeoFunctionRuleById(ctx, zoneId, functionId, ruleId)
	if err != nil {
		return err
	}

	if respData == nil {
		d.SetId("")
		log.Printf("[WARN]%s resource `teo_function_rule` [%s] not found, please check if it has been deleted.\n", logId, d.Id())
		return nil
	}
	if respData.RuleId != nil {
		_ = d.Set("rule_id", respData.RuleId)
		ruleId = *respData.RuleId
	}

	if respData.FunctionId != nil {
		_ = d.Set("function_id", respData.FunctionId)
	}

	if respData.FunctionName != nil {
		_ = d.Set("function_name", respData.FunctionName)
	}

	if respData.Remark != nil {
		_ = d.Set("remark", respData.Remark)
	}

	if respData.Priority != nil {
		_ = d.Set("priority", respData.Priority)
	}

	functionRuleConditionsList := make([]map[string]interface{}, 0, len(respData.FunctionRuleConditions))
	if respData.FunctionRuleConditions != nil {
		for _, functionRuleConditions := range respData.FunctionRuleConditions {
			functionRuleConditionsMap := map[string]interface{}{}

			ruleConditionsList := make([]map[string]interface{}, 0, len(functionRuleConditions.RuleConditions))
			if functionRuleConditions.RuleConditions != nil {
				for _, ruleConditions := range functionRuleConditions.RuleConditions {
					ruleConditionsMap := map[string]interface{}{}

					if ruleConditions.Operator != nil {
						ruleConditionsMap["operator"] = ruleConditions.Operator
					}

					if ruleConditions.Target != nil {
						ruleConditionsMap["target"] = ruleConditions.Target
					}

					if ruleConditions.Values != nil {
						ruleConditionsMap["values"] = ruleConditions.Values
					}

					if ruleConditions.IgnoreCase != nil {
						ruleConditionsMap["ignore_case"] = ruleConditions.IgnoreCase
					}

					if ruleConditions.Name != nil {
						ruleConditionsMap["name"] = ruleConditions.Name
					}

					ruleConditionsList = append(ruleConditionsList, ruleConditionsMap)
				}

				functionRuleConditionsMap["rule_conditions"] = ruleConditionsList
			}
			functionRuleConditionsList = append(functionRuleConditionsList, functionRuleConditionsMap)
		}

		_ = d.Set("function_rule_conditions", functionRuleConditionsList)
	}

	return nil
}

func resourceTencentCloudTeoFunctionRuleUpdate(d *schema.ResourceData, meta interface{}) error {
	defer tccommon.LogElapsed("resource.tencentcloud_teo_function_rule.update")()
	defer tccommon.InconsistentCheck(d, meta)()

	logId := tccommon.GetLogId(tccommon.ContextNil)

	ctx := tccommon.NewResourceLifeCycleHandleFuncContext(context.Background(), logId, d, meta)

	idSplit := strings.Split(d.Id(), tccommon.FILED_SP)
	if len(idSplit) != 3 {
		return fmt.Errorf("id is broken,%s", d.Id())
	}
	zoneId := idSplit[0]
	functionId := idSplit[1]
	ruleId := idSplit[2]

	needChange := false
	mutableArgs := []string{"function_rule_conditions", "remark"}
	for _, v := range mutableArgs {
		if d.HasChange(v) {
			needChange = true
			break
		}
	}

	if needChange {
		request := teov20220901.NewModifyFunctionRuleRequest()

		request.ZoneId = helper.String(zoneId)

		request.RuleId = helper.String(ruleId)

		if v, ok := d.GetOk("function_rule_conditions"); ok {
			for _, item := range v.([]interface{}) {
				functionRuleConditionsMap := item.(map[string]interface{})
				functionRuleCondition := teov20220901.FunctionRuleCondition{}
				if v, ok := functionRuleConditionsMap["rule_conditions"]; ok {
					for _, item := range v.([]interface{}) {
						ruleConditionsMap := item.(map[string]interface{})
						ruleCondition := teov20220901.RuleCondition{}
						if v, ok := ruleConditionsMap["operator"]; ok {
							ruleCondition.Operator = helper.String(v.(string))
						}
						if v, ok := ruleConditionsMap["target"]; ok {
							ruleCondition.Target = helper.String(v.(string))
						}
						if v, ok := ruleConditionsMap["values"]; ok {
							valuesSet := v.(*schema.Set).List()
							for i := range valuesSet {
								values := valuesSet[i].(string)
								ruleCondition.Values = append(ruleCondition.Values, helper.String(values))
							}
						}
						if v, ok := ruleConditionsMap["ignore_case"]; ok {
							ruleCondition.IgnoreCase = helper.Bool(v.(bool))
						}
						if v, ok := ruleConditionsMap["name"]; ok {
							ruleCondition.Name = helper.String(v.(string))
						}
						functionRuleCondition.RuleConditions = append(functionRuleCondition.RuleConditions, &ruleCondition)
					}
				}
				request.FunctionRuleConditions = append(request.FunctionRuleConditions, &functionRuleCondition)
			}
		}

		request.FunctionId = helper.String(functionId)

		if v, ok := d.GetOk("remark"); ok {
			request.Remark = helper.String(v.(string))
		}

		err := resource.Retry(tccommon.WriteRetryTimeout, func() *resource.RetryError {
			result, e := meta.(tccommon.ProviderMeta).GetAPIV3Conn().UseTeoV20220901Client().ModifyFunctionRuleWithContext(ctx, request)
			if e != nil {
				return tccommon.RetryError(e)
			} else {
				log.Printf("[DEBUG]%s api[%s] success, request body [%s], response body [%s]\n", logId, request.GetAction(), request.ToJsonString(), result.ToJsonString())
			}
			return nil
		})
		if err != nil {
			log.Printf("[CRITAL]%s update teo function rule failed, reason:%+v", logId, err)
			return err
		}
	}

	return resourceTencentCloudTeoFunctionRuleRead(d, meta)
}

func resourceTencentCloudTeoFunctionRuleDelete(d *schema.ResourceData, meta interface{}) error {
	defer tccommon.LogElapsed("resource.tencentcloud_teo_function_rule.delete")()
	defer tccommon.InconsistentCheck(d, meta)()

	logId := tccommon.GetLogId(tccommon.ContextNil)
	ctx := tccommon.NewResourceLifeCycleHandleFuncContext(context.Background(), logId, d, meta)

	idSplit := strings.Split(d.Id(), tccommon.FILED_SP)
	if len(idSplit) != 3 {
		return fmt.Errorf("id is broken,%s", d.Id())
	}
	zoneId := idSplit[0]
	functionId := idSplit[1]
	ruleId := idSplit[2]

	var (
		request  = teov20220901.NewDeleteFunctionRulesRequest()
		response = teov20220901.NewDeleteFunctionRulesResponse()
	)

	request.ZoneId = helper.String(zoneId)

	request.RuleIds = []*string{helper.String(ruleId)}

	err := resource.Retry(tccommon.WriteRetryTimeout, func() *resource.RetryError {
		result, e := meta.(tccommon.ProviderMeta).GetAPIV3Conn().UseTeoV20220901Client().DeleteFunctionRulesWithContext(ctx, request)
		if e != nil {
			return tccommon.RetryError(e)
		} else {
			log.Printf("[DEBUG]%s api[%s] success, request body [%s], response body [%s]\n", logId, request.GetAction(), request.ToJsonString(), result.ToJsonString())
		}
		response = result
		return nil
	})
	if err != nil {
		log.Printf("[CRITAL]%s delete teo function rule failed, reason:%+v", logId, err)
		return err
	}

	_ = response
	_ = functionId
	return nil
}
