// Code generated by iacg; DO NOT EDIT.
package teo

import (
	"context"
	"fmt"
	"log"
	"strings"
	"time"

	"github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema"

	tccommon "github.com/tencentcloudstack/terraform-provider-tencentcloud/tencentcloud/common"
)

func ResourceTencentCloudTeoCertificateConfig() *schema.Resource {
	return &schema.Resource{
		Create: resourceTencentCloudTeoCertificateConfigCreate,
		Read:   resourceTencentCloudTeoCertificateConfigRead,
		Update: resourceTencentCloudTeoCertificateConfigUpdate,
		Delete: resourceTencentCloudTeoCertificateConfigDelete,
		Importer: &schema.ResourceImporter{
			StateContext: schema.ImportStatePassthroughContext,
		},
		Timeouts: &schema.ResourceTimeout{
			Create: schema.DefaultTimeout(20 * time.Minute),
			Update: schema.DefaultTimeout(20 * time.Minute),
		},
		Schema: map[string]*schema.Schema{
			"zone_id": {
				Type:        schema.TypeString,
				Required:    true,
				ForceNew:    true,
				Description: "站点 ID",
			},

			"host": {
				Type:        schema.TypeString,
				Required:    true,
				ForceNew:    true,
				Description: "Acceleration 域名 名称 that needs to modify the certificate configuration。",
			},

			"server_cert_info": {
				Type:        schema.TypeList,
				Optional:    true,
				Computed:    true,
				Description: "SSL certificate configuration，this parameter takes effect only when 模式 = sslcert，just enter the corresponding CertId. You can go to the SSL certificate list to view the CertId。",
				Elem: &schema.Resource{
					Schema: map[string]*schema.Schema{
						"cert_id": {
							Type:        schema.TypeString,
							Required:    true,
							Description: "ID server certificate.注意：此字段可能返回 null，表示无法获取有效值。",
						},
						"alias": {
							Type:        schema.TypeString,
							Optional:    true,
							Computed:    true,
							Description: "Alias of the certificate.注意：此字段可能返回 null，表示无法获取有效值。",
						},
						"type": {
							Type:        schema.TypeString,
							Optional:    true,
							Computed:    true,
							Description: "类型 certificate. Values: `default`: Default certificate; `upload`: Specified certificate; `managed`: Tencent Cloud-managed certificate. Note: This field may return `null`，indicating that no valid 值 can be obtained。",
						},
						"expire_time": {
							Type:        schema.TypeString,
							Optional:    true,
							Computed:    true,
							Description: "Time when the certificate expires. 注意：此字段可能返回 null，表示无法获取有效值。",
						},
						"deploy_time": {
							Type:        schema.TypeString,
							Optional:    true,
							Computed:    true,
							Description: "Time when the certificate is deployed. 注意：此字段可能返回 null，表示无法获取有效值。",
						},
						"sign_algo": {
							Type:        schema.TypeString,
							Optional:    true,
							Computed:    true,
							Description: "签名 algorithm. 注意：此字段可能返回 null，表示无法获取有效值。",
						},
						"common_name": {
							Type:        schema.TypeString,
							Optional:    true,
							Computed:    true,
							Description: "域名 名称 certificate. Note: This field may return `null`，indicating that no valid 值 can be obtained。",
						},
					},
				},
			},

			"upstream_cert_info": {
				Type:        schema.TypeList,
				Optional:    true,
				Computed:    true,
				MaxItems:    1,
				Description: "配置certificate presented by the EO node during origin-pull for mutual TLS authentication. 已禁用 by default; leaving the field blank will retain the current configuration. This feature is currently in beta testing. please [contact us](https://cloud.tencent.com/online-service) to request access。",
				Elem: &schema.Resource{
					Schema: map[string]*schema.Schema{
						"upstream_mutual_tls": {
							Type:        schema.TypeList,
							Optional:    true,
							Computed:    true,
							MaxItems:    1,
							Description: "In the origin-pull mutual authentication scenario，this field represents the certificate (including the public and private keys) carried during EO node origin-pull，which is deployed in the EO node for the origin server to authenticate the EO node. When used as an input parameter，it is left blank to indicate retaining the original configuration。",
							Elem: &schema.Resource{
								Schema: map[string]*schema.Schema{
									"switch": {
										Type:        schema.TypeString,
										Required:    true,
										Description: "Mutual authentication configuration switch，the values are: `on`: enable; `off`: disable。",
									},
									"cert_infos": {
										Type:        schema.TypeList,
										Optional:    true,
										Computed:    true,
										Description: "Mutual authentication certificate list.\nNote: When using MutualTLS as an input parameter in ModifyHostsCertificate，you only need to provide the CertId of the corresponding certificate. You can check the CertId from the [SSL Certificate List](https://console.cloud.tencent.com/ssl)。",
										Elem: &schema.Resource{
											Schema: map[string]*schema.Schema{
												"cert_id": {
													Type:        schema.TypeString,
													Required:    true,
													Description: "证书 ID，which originates from the SSL side. You can check the CertId from the [SSL Certificate List](https://console.cloud.tencent.com/ssl)。",
												},
												"alias": {
													Type:        schema.TypeString,
													Computed:    true,
													Description: "Alias of the certificate。",
												},
												"type": {
													Type:        schema.TypeString,
													Computed:    true,
													Description: "类型 certificate. Values: `default`: Default certificate `upload`: Specified certificate `managed`: Tencent Cloud-managed certificate。",
												},
												"expire_time": {
													Type:        schema.TypeString,
													Computed:    true,
													Description: "The certificate 过期时间。",
												},
												"deploy_time": {
													Type:        schema.TypeString,
													Computed:    true,
													Description: "Time when the certificate is deployed。",
												},
												"sign_algo": {
													Type:        schema.TypeString,
													Computed:    true,
													Description: "签名 algorithm。",
												},
											},
										},
									},
								},
							},
						},
					},
				},
			},

			"mode": {
				Type:        schema.TypeString,
				Optional:    true,
				Computed:    true,
				Description: "模式 of configuring the certificate，the values are: `disable`: Do not configure the certificate; `eofreecert`: Configure EdgeOne free certificate; `sslcert`: Configure SSL certificate. 如果未填写 in，the 默认值为 `disable`。",
			},
		},
	}
}

func resourceTencentCloudTeoCertificateConfigCreate(d *schema.ResourceData, meta interface{}) error {
	defer tccommon.LogElapsed("resource.tencentcloud_teo_certificate_config.create")()
	defer tccommon.InconsistentCheck(d, meta)()

	var (
		zoneId string
		host   string
	)
	if v, ok := d.GetOk("zone_id"); ok {
		zoneId = v.(string)
	}
	if v, ok := d.GetOk("host"); ok {
		host = v.(string)
	}

	d.SetId(strings.Join([]string{zoneId, host}, tccommon.FILED_SP))

	return resourceTencentCloudTeoCertificateConfigUpdate(d, meta)
}

func resourceTencentCloudTeoCertificateConfigRead(d *schema.ResourceData, meta interface{}) error {
	defer tccommon.LogElapsed("resource.tencentcloud_teo_certificate_config.read")()
	defer tccommon.InconsistentCheck(d, meta)()

	logId := tccommon.GetLogId(tccommon.ContextNil)

	ctx := tccommon.NewResourceLifeCycleHandleFuncContext(context.Background(), logId, d, meta)

	service := TeoService{client: meta.(tccommon.ProviderMeta).GetAPIV3Conn()}

	idSplit := strings.Split(d.Id(), tccommon.FILED_SP)
	if len(idSplit) != 2 {
		return fmt.Errorf("id is broken,%s", d.Id())
	}
	zoneId := idSplit[0]
	host := idSplit[1]

	_ = d.Set("zone_id", zoneId)

	_ = d.Set("host", host)

	respData, err := service.DescribeTeoCertificateConfigById(ctx, zoneId, host)
	if err != nil {
		return err
	}

	if respData == nil {
		d.SetId("")
		log.Printf("[WARN]%s resource `teo_certificate_config` [%s] not found, please check if it has been deleted.\n", logId, d.Id())
		return nil
	}

	if err := resourceTencentCloudTeoCertificateConfigReadPostHandleResponse0(ctx, respData); err != nil {
		return err
	}

	return nil
}

func resourceTencentCloudTeoCertificateConfigUpdate(d *schema.ResourceData, meta interface{}) error {
	defer tccommon.LogElapsed("resource.tencentcloud_teo_certificate_config.update")()
	defer tccommon.InconsistentCheck(d, meta)()

	logId := tccommon.GetLogId(tccommon.ContextNil)

	ctx := tccommon.NewResourceLifeCycleHandleFuncContext(context.Background(), logId, d, meta)

	idSplit := strings.Split(d.Id(), tccommon.FILED_SP)
	if len(idSplit) != 2 {
		return fmt.Errorf("id is broken,%s", d.Id())
	}
	zoneId := idSplit[0]
	host := idSplit[1]

	if err := resourceTencentCloudTeoCertificateConfigUpdateOnStart(ctx); err != nil {
		return err
	}

	if err := resourceTencentCloudTeoCertificateConfigUpdateOnExit(ctx); err != nil {
		return err
	}

	_ = zoneId
	_ = host
	return resourceTencentCloudTeoCertificateConfigRead(d, meta)
}

func resourceTencentCloudTeoCertificateConfigDelete(d *schema.ResourceData, meta interface{}) error {
	defer tccommon.LogElapsed("resource.tencentcloud_teo_certificate_config.delete")()
	defer tccommon.InconsistentCheck(d, meta)()

	return nil
}
