// Code generated by iacg; DO NOT EDIT.
package tke

import (
	"context"

	"github.com/hashicorp/terraform-plugin-sdk/v2/helper/resource"
	"github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema"
	tkev20180525 "github.com/tencentcloud/tencentcloud-sdk-go/tencentcloud/tke/v20180525"

	tccommon "github.com/tencentcloudstack/terraform-provider-tencentcloud/tencentcloud/common"
	"github.com/tencentcloudstack/terraform-provider-tencentcloud/tencentcloud/internal/helper"
)

func DataSourceTencentCloudKubernetesClusterNodePools() *schema.Resource {
	return &schema.Resource{
		Read: dataSourceTencentCloudKubernetesClusterNodePoolsRead,
		Schema: map[string]*schema.Schema{
			"cluster_id": {
				Type:        schema.TypeString,
				Required:    true,
				Description: "ID 集群。",
			},

			"filters": {
				Type:        schema.TypeList,
				Optional:    true,
				Description: "NodePoolsName，过滤器 according 到 节点 池 名称，类型: String，必填: 无. NodePoolsId，过滤器 according 到 节点 池 ID，类型: String，必填: 无. 标签，过滤器 according 到 标签 键 值 pairs，类型: String，必填: 无. 标签:标签-键，过滤器 according 到 标签 键 值 pairs，类型: String，必填: 无。",
				Elem: &schema.Resource{
					Schema: map[string]*schema.Schema{
						"name": {
							Type:        schema.TypeString,
							Required:    true,
							Description: "attribute 名称，如果 there 是 多个 filters， relationship between filters 是 logical AND relationship。",
						},
						"values": {
							Type:        schema.TypeSet,
							Required:    true,
							Description: "Attribute 值，如果 there 是 多个 值 在 same 过滤器， relationship between 值 under same 过滤器 是 logical OR relationship。",
							Elem: &schema.Schema{
								Type: schema.TypeString,
							},
						},
					},
				},
			},

			"node_pool_set": {
				Type:        schema.TypeList,
				Computed:    true,
				Description: "Node Pool List。",
				Elem: &schema.Resource{
					Schema: map[string]*schema.Schema{
						"node_pool_id": {
							Type:        schema.TypeString,
							Computed:    true,
							Description: "ID 节点 池。",
						},
						"name": {
							Type:        schema.TypeString,
							Computed:    true,
							Description: "名称 节点 池。",
						},
						"cluster_instance_id": {
							Type:        schema.TypeString,
							Computed:    true,
							Description: "ID 集群。",
						},
						"life_state": {
							Type:        schema.TypeString,
							Computed:    true,
							Description: "Life cycle state 的 节点 池，include: creating，normal，updating，deleting，删除。",
						},
						"launch_configuration_id": {
							Type:        schema.TypeString,
							Computed:    true,
							Description: "ID launch 配置。",
						},
						"autoscaling_group_id": {
							Type:        schema.TypeString,
							Computed:    true,
							Description: "ID autoscaling 组。",
						},
						"labels": {
							Type:        schema.TypeList,
							Computed:    true,
							Description: "Labels 的 节点 池。",
							Elem: &schema.Resource{
								Schema: map[string]*schema.Schema{
									"name": {
										Type:        schema.TypeString,
										Computed:    true,
										Description: "名称 在 map 表。",
									},
									"value": {
										Type:        schema.TypeString,
										Computed:    true,
										Description: "值 在 map 表。",
									},
								},
							},
						},
						"taints": {
							Type:        schema.TypeList,
							Computed:    true,
							Description: "Labels 的 节点 池。",
							Elem: &schema.Resource{
								Schema: map[string]*schema.Schema{
									"key": {
										Type:        schema.TypeString,
										Computed:    true,
										Description: "键 的 taints mark。",
									},
									"value": {
										Type:        schema.TypeString,
										Computed:    true,
										Description: "值 的 taints mark。",
									},
									"effect": {
										Type:        schema.TypeString,
										Computed:    true,
										Description: "Effect 的 taints mark。",
									},
								},
							},
						},
						"node_count_summary": {
							Type:        schema.TypeList,
							Computed:    true,
							Description: "Node List。",
							Elem: &schema.Resource{
								Schema: map[string]*schema.Schema{
									"manually_added": {
										Type:        schema.TypeList,
										Computed:    true,
										Description: "Manually managed nodes。",
										Elem: &schema.Resource{
											Schema: map[string]*schema.Schema{
												"joining": {
													Type:        schema.TypeInt,
													Computed:    true,
													Description: "节点数量 joining。",
												},
												"initializing": {
													Type:        schema.TypeInt,
													Computed:    true,
													Description: "节点数量 在 initialization。",
												},
												"normal": {
													Type:        schema.TypeInt,
													Computed:    true,
													Description: "Normal 数量 nodes。",
												},
												"total": {
													Type:        schema.TypeInt,
													Computed:    true,
													Description: "Total 数量 nodes。",
												},
											},
										},
									},
									"autoscaling_added": {
										Type:        schema.TypeList,
										Computed:    true,
										Description: "Automatically managed nodes。",
										Elem: &schema.Resource{
											Schema: map[string]*schema.Schema{
												"joining": {
													Type:        schema.TypeInt,
													Computed:    true,
													Description: "节点数量 joining。",
												},
												"initializing": {
													Type:        schema.TypeInt,
													Computed:    true,
													Description: "节点数量 在 initialization。",
												},
												"normal": {
													Type:        schema.TypeInt,
													Computed:    true,
													Description: "Normal 数量 nodes。",
												},
												"total": {
													Type:        schema.TypeInt,
													Computed:    true,
													Description: "Total 数量 nodes。",
												},
											},
										},
									},
								},
							},
						},
						"autoscaling_group_status": {
							Type:        schema.TypeString,
							Computed:    true,
							Description: "状态 信息。",
						},
						"max_nodes_num": {
							Type:        schema.TypeInt,
							Computed:    true,
							Description: "最大nodes。",
						},
						"min_nodes_num": {
							Type:        schema.TypeInt,
							Computed:    true,
							Description: "最小nodes。",
						},
						"desired_nodes_num": {
							Type:        schema.TypeInt,
							Computed:    true,
							Description: "Expected 数量 nodes。",
						},
						"node_pool_os": {
							Type:        schema.TypeString,
							Computed:    true,
							Description: "Node Pool OS 名称",
						},
						"os_customize_type": {
							Type:        schema.TypeString,
							Computed:    true,
							Description: "Mirror 版本 的 容器。",
						},
						"image_id": {
							Type:        schema.TypeString,
							Computed:    true,
							Description: "ID 镜像。",
						},
						"desired_pod_num": {
							Type:        schema.TypeInt,
							Computed:    true,
							Description: "当 集群 belongs 到 节点 podCIDR 大小 customization 模式， 节点 池 needs 到 have pod 数量 attribute。",
						},
						"user_script": {
							Type:        schema.TypeString,
							Computed:    true,
							Description: "用户 defined scripts。",
						},
						"tags": {
							Type:        schema.TypeList,
							Computed:    true,
							Description: "Resource 标签",
							Elem: &schema.Resource{
								Schema: map[string]*schema.Schema{
									"key": {
										Type:        schema.TypeString,
										Computed:    true,
										Description: "标签 键",
									},
									"value": {
										Type:        schema.TypeString,
										Computed:    true,
										Description: "标签值",
									},
								},
							},
						},
						"deletion_protection": {
							Type:        schema.TypeBool,
							Computed:    true,
							Description: "Remove protection switch。",
						},
						"extra_args": {
							Type:        schema.TypeList,
							Computed:    true,
							Description: "Node 配置。",
							Elem: &schema.Resource{
								Schema: map[string]*schema.Schema{
									"kubelet": {
										Type:        schema.TypeSet,
										Computed:    true,
										Description: "Kubelet 自定义 参数。",
										Elem: &schema.Schema{
											Type: schema.TypeString,
										},
									},
								},
							},
						},
						"gpu_args": {
							Type:        schema.TypeList,
							Computed:    true,
							Description: "GPU 驱动 related 参数。",
							Elem: &schema.Resource{
								Schema: map[string]*schema.Schema{
									"mig_enable": {
										Type:        schema.TypeBool,
										Computed:    true,
										Description: "Is MIG 功能 已启用",
									},
									"driver": {
										Type:        schema.TypeList,
										Computed:    true,
										Description: "GPU 驱动 版本 信息。",
										Elem: &schema.Resource{
											Schema: map[string]*schema.Schema{
												"version": {
													Type:        schema.TypeString,
													Computed:    true,
													Description: "GPU 驱动 或 CUDA 版本",
												},
												"name": {
													Type:        schema.TypeString,
													Computed:    true,
													Description: "GPU 驱动 或 CUDA 名称",
												},
											},
										},
									},
									"cuda": {
										Type:        schema.TypeList,
										Computed:    true,
										Description: "CUDA 版本 信息。",
										Elem: &schema.Resource{
											Schema: map[string]*schema.Schema{
												"version": {
													Type:        schema.TypeString,
													Computed:    true,
													Description: "GPU 驱动 或 CUDA 版本",
												},
												"name": {
													Type:        schema.TypeString,
													Computed:    true,
													Description: "GPU 驱动 或 CUDA 名称",
												},
											},
										},
									},
									"cudnn": {
										Type:        schema.TypeList,
										Computed:    true,
										Description: "CuDNN 版本 信息。",
										Elem: &schema.Resource{
											Schema: map[string]*schema.Schema{
												"version": {
													Type:        schema.TypeString,
													Computed:    true,
													Description: "版本 的 cuDNN。",
												},
												"name": {
													Type:        schema.TypeString,
													Computed:    true,
													Description: "名称 cuDNN。",
												},
												"doc_name": {
													Type:        schema.TypeString,
													Computed:    true,
													Description: "Doc 名称 cuDNN。",
												},
												"dev_name": {
													Type:        schema.TypeString,
													Computed:    true,
													Description: "Dev 名称 cuDNN。",
												},
											},
										},
									},
									"custom_driver": {
										Type:        schema.TypeList,
										Computed:    true,
										Description: "Custom GPU 驱动 信息。",
										Elem: &schema.Resource{
											Schema: map[string]*schema.Schema{
												"address": {
													Type:        schema.TypeString,
													Computed:    true,
													Description: "Custom GPU 驱动 地址 link。",
												},
											},
										},
									},
								},
							},
						},
						"docker_graph_path": {
							Type:        schema.TypeString,
							Computed:    true,
							Description: "Dockerd --graph 指定 值，默认为 /var/lib/docker。",
						},
						"data_disks": {
							Type:        schema.TypeList,
							Computed:    true,
							Description: "Multi 磁盘 数据 磁盘 mounting 信息。",
							Elem: &schema.Resource{
								Schema: map[string]*schema.Schema{
									"disk_type": {
										Type:        schema.TypeString,
										Computed:    true,
										Description: "Cloud 磁盘 类型",
									},
									"file_system": {
										Type:        schema.TypeString,
										Computed:    true,
										Description: "File 系统(ext3/ext4/xfs)。",
									},
									"disk_size": {
										Type:        schema.TypeInt,
										Computed:    true,
										Description: "Cloud 磁盘 大小(G)。",
									},
									"auto_format_and_mount": {
										Type:        schema.TypeBool,
										Computed:    true,
										Description: "是否automate 格式 磁盘 和 mount 它。",
									},
									"mount_target": {
										Type:        schema.TypeString,
										Computed:    true,
										Description: "挂载目录",
									},
									"disk_partition": {
										Type:        schema.TypeString,
										Computed:    true,
										Description: "Mount device 名称 或 分区 名称",
									},
								},
							},
						},
						"unschedulable": {
							Type:        schema.TypeInt,
							Computed:    true,
							Description: "Is 它 不 schedulable。",
						},
						"pre_start_user_script": {
							Type:        schema.TypeString,
							Computed:    true,
							Description: "用户 defined 脚本，executed before 用户 Script。",
						},
					},
				},
			},

			"result_output_file": {
				Type:        schema.TypeString,
				Optional:    true,
				Description: "用于保存结果。",
			},
		},
	}
}

func dataSourceTencentCloudKubernetesClusterNodePoolsRead(d *schema.ResourceData, meta interface{}) error {
	defer tccommon.LogElapsed("data_source.tencentcloud_kubernetes_cluster_node_pools.read")()
	defer tccommon.InconsistentCheck(d, meta)()

	logId := tccommon.GetLogId(nil)
	ctx := tccommon.NewResourceLifeCycleHandleFuncContext(context.Background(), logId, d, meta)

	service := TkeService{client: meta.(tccommon.ProviderMeta).GetAPIV3Conn()}

	paramMap := make(map[string]interface{})
	if v, ok := d.GetOk("cluster_id"); ok {
		paramMap["ClusterId"] = helper.String(v.(string))
	}

	if v, ok := d.GetOk("filters"); ok {
		filtersSet := v.([]interface{})
		tmpSet := make([]*tkev20180525.Filter, 0, len(filtersSet))
		for _, item := range filtersSet {
			filtersMap := item.(map[string]interface{})
			filter := tkev20180525.Filter{}
			if v, ok := filtersMap["name"]; ok {
				filter.Name = helper.String(v.(string))
			}
			if v, ok := filtersMap["values"]; ok {
				valuesSet := v.(*schema.Set).List()
				for i := range valuesSet {
					values := valuesSet[i].(string)
					filter.Values = append(filter.Values, helper.String(values))
				}
			}
			tmpSet = append(tmpSet, &filter)
		}
		paramMap["Filters"] = tmpSet
	}

	var respData []*tkev20180525.NodePool
	err := resource.Retry(tccommon.ReadRetryTimeout, func() *resource.RetryError {
		result, e := service.DescribeKubernetesClusterNodePoolsByFilter(ctx, paramMap)
		if e != nil {
			return tccommon.RetryError(e)
		}
		respData = result
		return nil
	})
	if err != nil {
		return err
	}

	var ids []string
	nodePoolSetList := make([]map[string]interface{}, 0, len(respData))
	if respData != nil {
		for _, nodePoolSet := range respData {
			nodePoolSetMap := map[string]interface{}{}

			var nodePoolId string
			if nodePoolSet.NodePoolId != nil {
				nodePoolSetMap["node_pool_id"] = nodePoolSet.NodePoolId
				nodePoolId = *nodePoolSet.NodePoolId
			}

			if nodePoolSet.Name != nil {
				nodePoolSetMap["name"] = nodePoolSet.Name
			}

			if nodePoolSet.ClusterInstanceId != nil {
				nodePoolSetMap["cluster_instance_id"] = nodePoolSet.ClusterInstanceId
			}

			if nodePoolSet.LifeState != nil {
				nodePoolSetMap["life_state"] = nodePoolSet.LifeState
			}

			if nodePoolSet.LaunchConfigurationId != nil {
				nodePoolSetMap["launch_configuration_id"] = nodePoolSet.LaunchConfigurationId
			}

			if nodePoolSet.AutoscalingGroupId != nil {
				nodePoolSetMap["autoscaling_group_id"] = nodePoolSet.AutoscalingGroupId
			}

			labelsList := make([]map[string]interface{}, 0, len(nodePoolSet.Labels))
			if nodePoolSet.Labels != nil {
				for _, labels := range nodePoolSet.Labels {
					labelsMap := map[string]interface{}{}

					if labels.Name != nil {
						labelsMap["name"] = labels.Name
					}

					if labels.Value != nil {
						labelsMap["value"] = labels.Value
					}

					labelsList = append(labelsList, labelsMap)
				}

				nodePoolSetMap["labels"] = labelsList
			}
			taintsList := make([]map[string]interface{}, 0, len(nodePoolSet.Taints))
			if nodePoolSet.Taints != nil {
				for _, taints := range nodePoolSet.Taints {
					taintsMap := map[string]interface{}{}

					if taints.Key != nil {
						taintsMap["key"] = taints.Key
					}

					if taints.Value != nil {
						taintsMap["value"] = taints.Value
					}

					if taints.Effect != nil {
						taintsMap["effect"] = taints.Effect
					}

					taintsList = append(taintsList, taintsMap)
				}

				nodePoolSetMap["taints"] = taintsList
			}
			nodeCountSummaryMap := map[string]interface{}{}

			if nodePoolSet.NodeCountSummary != nil {
				manuallyAddedMap := map[string]interface{}{}

				if nodePoolSet.NodeCountSummary.ManuallyAdded != nil {
					if nodePoolSet.NodeCountSummary.ManuallyAdded.Joining != nil {
						manuallyAddedMap["joining"] = nodePoolSet.NodeCountSummary.ManuallyAdded.Joining
					}

					if nodePoolSet.NodeCountSummary.ManuallyAdded.Initializing != nil {
						manuallyAddedMap["initializing"] = nodePoolSet.NodeCountSummary.ManuallyAdded.Initializing
					}

					if nodePoolSet.NodeCountSummary.ManuallyAdded.Normal != nil {
						manuallyAddedMap["normal"] = nodePoolSet.NodeCountSummary.ManuallyAdded.Normal
					}

					if nodePoolSet.NodeCountSummary.ManuallyAdded.Total != nil {
						manuallyAddedMap["total"] = nodePoolSet.NodeCountSummary.ManuallyAdded.Total
					}

					nodeCountSummaryMap["manually_added"] = []interface{}{manuallyAddedMap}
				}

				autoscalingAddedMap := map[string]interface{}{}

				if nodePoolSet.NodeCountSummary.AutoscalingAdded != nil {
					if nodePoolSet.NodeCountSummary.AutoscalingAdded.Joining != nil {
						autoscalingAddedMap["joining"] = nodePoolSet.NodeCountSummary.AutoscalingAdded.Joining
					}

					if nodePoolSet.NodeCountSummary.AutoscalingAdded.Initializing != nil {
						autoscalingAddedMap["initializing"] = nodePoolSet.NodeCountSummary.AutoscalingAdded.Initializing
					}

					if nodePoolSet.NodeCountSummary.AutoscalingAdded.Normal != nil {
						autoscalingAddedMap["normal"] = nodePoolSet.NodeCountSummary.AutoscalingAdded.Normal
					}

					if nodePoolSet.NodeCountSummary.AutoscalingAdded.Total != nil {
						autoscalingAddedMap["total"] = nodePoolSet.NodeCountSummary.AutoscalingAdded.Total
					}

					nodeCountSummaryMap["autoscaling_added"] = []interface{}{autoscalingAddedMap}
				}

				nodePoolSetMap["node_count_summary"] = []interface{}{nodeCountSummaryMap}
			}

			if nodePoolSet.AutoscalingGroupStatus != nil {
				nodePoolSetMap["autoscaling_group_status"] = nodePoolSet.AutoscalingGroupStatus
			}

			if nodePoolSet.MaxNodesNum != nil {
				nodePoolSetMap["max_nodes_num"] = nodePoolSet.MaxNodesNum
			}

			if nodePoolSet.MinNodesNum != nil {
				nodePoolSetMap["min_nodes_num"] = nodePoolSet.MinNodesNum
			}

			if nodePoolSet.DesiredNodesNum != nil {
				nodePoolSetMap["desired_nodes_num"] = nodePoolSet.DesiredNodesNum
			}

			if nodePoolSet.NodePoolOs != nil {
				nodePoolSetMap["node_pool_os"] = nodePoolSet.NodePoolOs
			}

			if nodePoolSet.OsCustomizeType != nil {
				nodePoolSetMap["os_customize_type"] = nodePoolSet.OsCustomizeType
			}

			if nodePoolSet.ImageId != nil {
				nodePoolSetMap["image_id"] = nodePoolSet.ImageId
			}

			if nodePoolSet.DesiredPodNum != nil {
				nodePoolSetMap["desired_pod_num"] = nodePoolSet.DesiredPodNum
			}

			if nodePoolSet.UserScript != nil {
				nodePoolSetMap["user_script"] = nodePoolSet.UserScript
			}

			tagsList := make([]map[string]interface{}, 0, len(nodePoolSet.Tags))
			if nodePoolSet.Tags != nil {
				for _, tags := range nodePoolSet.Tags {
					tagsMap := map[string]interface{}{}

					if tags.Key != nil {
						tagsMap["key"] = tags.Key
					}

					if tags.Value != nil {
						tagsMap["value"] = tags.Value
					}

					tagsList = append(tagsList, tagsMap)
				}

				nodePoolSetMap["tags"] = tagsList
			}
			if nodePoolSet.DeletionProtection != nil {
				nodePoolSetMap["deletion_protection"] = nodePoolSet.DeletionProtection
			}

			extraArgsMap := map[string]interface{}{}

			if nodePoolSet.ExtraArgs != nil {
				if nodePoolSet.ExtraArgs.Kubelet != nil {
					extraArgsMap["kubelet"] = nodePoolSet.ExtraArgs.Kubelet
				}

				nodePoolSetMap["extra_args"] = []interface{}{extraArgsMap}
			}

			gPUArgsMap := map[string]interface{}{}

			if nodePoolSet.GPUArgs != nil {
				if nodePoolSet.GPUArgs.MIGEnable != nil {
					gPUArgsMap["mig_enable"] = nodePoolSet.GPUArgs.MIGEnable
				}

				driverMap := map[string]interface{}{}

				if nodePoolSet.GPUArgs.Driver != nil {
					if nodePoolSet.GPUArgs.Driver.Version != nil {
						driverMap["version"] = nodePoolSet.GPUArgs.Driver.Version
					}

					if nodePoolSet.GPUArgs.Driver.Name != nil {
						driverMap["name"] = nodePoolSet.GPUArgs.Driver.Name
					}

					gPUArgsMap["driver"] = []interface{}{driverMap}
				}

				cUDAMap := map[string]interface{}{}

				if nodePoolSet.GPUArgs.CUDA != nil {
					if nodePoolSet.GPUArgs.CUDA.Version != nil {
						cUDAMap["version"] = nodePoolSet.GPUArgs.CUDA.Version
					}

					if nodePoolSet.GPUArgs.CUDA.Name != nil {
						cUDAMap["name"] = nodePoolSet.GPUArgs.CUDA.Name
					}

					gPUArgsMap["cuda"] = []interface{}{cUDAMap}
				}

				cUDNNMap := map[string]interface{}{}

				if nodePoolSet.GPUArgs.CUDNN != nil {
					if nodePoolSet.GPUArgs.CUDNN.Version != nil {
						cUDNNMap["version"] = nodePoolSet.GPUArgs.CUDNN.Version
					}

					if nodePoolSet.GPUArgs.CUDNN.Name != nil {
						cUDNNMap["name"] = nodePoolSet.GPUArgs.CUDNN.Name
					}

					if nodePoolSet.GPUArgs.CUDNN.DocName != nil {
						cUDNNMap["doc_name"] = nodePoolSet.GPUArgs.CUDNN.DocName
					}

					if nodePoolSet.GPUArgs.CUDNN.DevName != nil {
						cUDNNMap["dev_name"] = nodePoolSet.GPUArgs.CUDNN.DevName
					}

					gPUArgsMap["cudnn"] = []interface{}{cUDNNMap}
				}

				customDriverMap := map[string]interface{}{}

				if nodePoolSet.GPUArgs.CustomDriver != nil {
					if nodePoolSet.GPUArgs.CustomDriver.Address != nil {
						customDriverMap["address"] = nodePoolSet.GPUArgs.CustomDriver.Address
					}

					gPUArgsMap["custom_driver"] = []interface{}{customDriverMap}
				}

				nodePoolSetMap["gpu_args"] = []interface{}{gPUArgsMap}
			}

			if nodePoolSet.DockerGraphPath != nil {
				nodePoolSetMap["docker_graph_path"] = nodePoolSet.DockerGraphPath
			}

			dataDisksList := make([]map[string]interface{}, 0, len(nodePoolSet.DataDisks))
			if nodePoolSet.DataDisks != nil {
				for _, dataDisks := range nodePoolSet.DataDisks {
					dataDisksMap := map[string]interface{}{}

					if dataDisks.DiskType != nil {
						dataDisksMap["disk_type"] = dataDisks.DiskType
					}

					if dataDisks.FileSystem != nil {
						dataDisksMap["file_system"] = dataDisks.FileSystem
					}

					if dataDisks.DiskSize != nil {
						dataDisksMap["disk_size"] = dataDisks.DiskSize
					}

					if dataDisks.AutoFormatAndMount != nil {
						dataDisksMap["auto_format_and_mount"] = dataDisks.AutoFormatAndMount
					}

					if dataDisks.MountTarget != nil {
						dataDisksMap["mount_target"] = dataDisks.MountTarget
					}

					if dataDisks.DiskPartition != nil {
						dataDisksMap["disk_partition"] = dataDisks.DiskPartition
					}

					dataDisksList = append(dataDisksList, dataDisksMap)
				}

				nodePoolSetMap["data_disks"] = dataDisksList
			}
			if nodePoolSet.Unschedulable != nil {
				nodePoolSetMap["unschedulable"] = nodePoolSet.Unschedulable
			}

			if nodePoolSet.PreStartUserScript != nil {
				nodePoolSetMap["pre_start_user_script"] = nodePoolSet.PreStartUserScript
			}

			ids = append(ids, nodePoolId)
			nodePoolSetList = append(nodePoolSetList, nodePoolSetMap)
		}

		_ = d.Set("node_pool_set", nodePoolSetList)
	}

	d.SetId(helper.DataResourceIdsHash(ids))

	output, ok := d.GetOk("result_output_file")
	if ok && output.(string) != "" {
		if e := tccommon.WriteToFile(output.(string), nodePoolSetList); e != nil {
			return e
		}
	}

	return nil
}
