// Code generated by iacg; DO NOT EDIT.
package tke

import (
	"context"

	"github.com/hashicorp/terraform-plugin-sdk/v2/helper/resource"
	"github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema"
	tkev20180525 "github.com/tencentcloud/tencentcloud-sdk-go/tencentcloud/tke/v20180525"

	tccommon "github.com/tencentcloudstack/terraform-provider-tencentcloud/tencentcloud/common"
	"github.com/tencentcloudstack/terraform-provider-tencentcloud/tencentcloud/internal/helper"
)

func DataSourceTencentCloudKubernetesClusterInstances() *schema.Resource {
	return &schema.Resource{
		Read: dataSourceTencentCloudKubernetesClusterInstancesRead,
		Schema: map[string]*schema.Schema{
			"cluster_id": {
				Type:        schema.TypeString,
				Required:    true,
				Description: "ID cluster。",
			},

			"instance_ids": {
				Type:        schema.TypeSet,
				Optional:    true,
				Description: "列表 node instance IDs to be obtained. If it is empty，it means pulling all node instances in the cluster。",
				Elem: &schema.Schema{
					Type: schema.TypeString,
				},
			},

			"instance_role": {
				Type:        schema.TypeString,
				Optional:    true,
				Description: "Node 角色，MASTER，WORKER，ETCD，MASTER_ETCD,ALL，默认为 WORKER。",
			},

			"filters": {
				Type:        schema.TypeList,
				Optional:    true,
				Description: "列表 filter conditions. The 可选 values of 名称 are `nodepool-id` and `nodepool-instance-类型`. 名称 is `nodepool-id`，which means filtering machines based on node pool id，and 值 is the specific node pool id. 名称 is `nodepool-instance-类型`，which 表示how the node is added to the node pool. 值 is MANUALLY_ADDED (manually added to the node pool)，AUTOSCALING_ADDED (joined by scaling group expansion method)，ALL (manually join the node pool and join the node pool through scaling group expansion)。",
				Elem: &schema.Resource{
					Schema: map[string]*schema.Schema{
						"name": {
							Type:        schema.TypeString,
							Required:    true,
							Description: "The attribute 名称，if there are multiple filters，the relationship between the filters is a logical AND relationship。",
						},
						"values": {
							Type:        schema.TypeSet,
							Required:    true,
							Description: "Attribute values，if there are multiple values in the same filter，the relationship between values under the same filter is a logical OR relationship。",
							Elem: &schema.Schema{
								Type: schema.TypeString,
							},
						},
					},
				},
			},

			"instance_set": {
				Type:        schema.TypeList,
				Computed:    true,
				Description: "列表 instances in the cluster。",
				Elem: &schema.Resource{
					Schema: map[string]*schema.Schema{
						"instance_id": {
							Type:        schema.TypeString,
							Computed:    true,
							Description: "实例 ID",
						},
						"instance_role": {
							Type:        schema.TypeString,
							Computed:    true,
							Description: "Node 角色，MASTER，WORKER，ETCD，MASTER_ETCD,ALL，默认为 WORKER。",
						},
						"failed_reason": {
							Type:        schema.TypeString,
							Computed:    true,
							Description: "Reasons for instance exception (or being initialized)。",
						},
						"instance_state": {
							Type:        schema.TypeString,
							Computed:    true,
							Description: "The 状态 instance (running，initializing，failed)。",
						},
						"drain_status": {
							Type:        schema.TypeString,
							Computed:    true,
							Description: "是否instance is blocked。",
						},
						"instance_advanced_settings": {
							Type:        schema.TypeList,
							Computed:    true,
							Description: "Node configuration。",
							Elem: &schema.Resource{
								Schema: map[string]*schema.Schema{
									"desired_pod_number": {
										Type:        schema.TypeInt,
										Computed:    true,
										Description: "When the node belongs to the podCIDR size customization 模式，you can 指定upper 限制 of the 数量 pods running on the node。",
									},
									"gpu_args": {
										Type:        schema.TypeList,
										Computed:    true,
										Description: "GPU driver related parameters，obtain related GPU parameters: https://cloud.tencent.com/document/api/213/15715。",
										Elem: &schema.Resource{
											Schema: map[string]*schema.Schema{
												"mig_enable": {
													Type:        schema.TypeBool,
													Computed:    true,
													Description: "是否enable MIG features。",
												},
												"driver": {
													Type:        schema.TypeList,
													Computed:    true,
													Description: "GPU driver 版本 information。",
													Elem: &schema.Resource{
														Schema: map[string]*schema.Schema{
															"version": {
																Type:        schema.TypeString,
																Computed:    true,
																Description: "GPU driver or CUDA 版本",
															},
															"name": {
																Type:        schema.TypeString,
																Computed:    true,
																Description: "The 名称 GPU driver or CUDA。",
															},
														},
													},
												},
												"cuda": {
													Type:        schema.TypeList,
													Computed:    true,
													Description: "CUDA 版本 information。",
													Elem: &schema.Resource{
														Schema: map[string]*schema.Schema{
															"version": {
																Type:        schema.TypeString,
																Computed:    true,
																Description: "GPU driver or CUDA 版本",
															},
															"name": {
																Type:        schema.TypeString,
																Computed:    true,
																Description: "The 名称 GPU driver or CUDA。",
															},
														},
													},
												},
												"cudnn": {
													Type:        schema.TypeList,
													Computed:    true,
													Description: "CuDNN 版本 information。",
													Elem: &schema.Resource{
														Schema: map[string]*schema.Schema{
															"version": {
																Type:        schema.TypeString,
																Computed:    true,
																Description: "版本 of cuDNN。",
															},
															"name": {
																Type:        schema.TypeString,
																Computed:    true,
																Description: "CuDNN 名称",
															},
															"doc_name": {
																Type:        schema.TypeString,
																Computed:    true,
																Description: "Doc 名称 cuDNN。",
															},
															"dev_name": {
																Type:        schema.TypeString,
																Computed:    true,
																Description: "Dev 名称 cuDNN。",
															},
														},
													},
												},
												"custom_driver": {
													Type:        schema.TypeList,
													Computed:    true,
													Description: "Custom GPU driver information。",
													Elem: &schema.Resource{
														Schema: map[string]*schema.Schema{
															"address": {
																Type:        schema.TypeString,
																Computed:    true,
																Description: "Custom GPU driver 地址 link。",
															},
														},
													},
												},
											},
										},
									},
									"pre_start_user_script": {
										Type:        schema.TypeString,
										Computed:    true,
										Description: "Base64 encoded 用户 script，executed before initializing the node，currently only effective for adding existing nodes。",
									},
									"taints": {
										Type:        schema.TypeList,
										Computed:    true,
										Description: "Node taint。",
										Elem: &schema.Resource{
											Schema: map[string]*schema.Schema{
												"key": {
													Type:        schema.TypeString,
													Computed:    true,
													Description: "键 of taints mark。",
												},
												"value": {
													Type:        schema.TypeString,
													Computed:    true,
													Description: "值 of taints mark。",
												},
												"effect": {
													Type:        schema.TypeString,
													Computed:    true,
													Description: "Effect of taints mark。",
												},
											},
										},
									},
									"mount_target": {
										Type:        schema.TypeString,
										Computed:    true,
										Description: "Data disk mount point，the data disk is not mounted by default. Formatted ext3，ext4，xfs file system data disks will be mounted directly. Other file systems or unformatted data disks will be automatically formatted as ext4 (tlinux system formatted as xfs) and mounted. Please pay attention to backing up the data. This setting does not take effect for cloud hosts that have no data disks or multiple data disks。",
									},
									"docker_graph_path": {
										Type:        schema.TypeString,
										Computed:    true,
										Description: "Dockerd --graph 指定value，the 默认为 /var/lib/docker。",
									},
									"user_script": {
										Type:        schema.TypeString,
										Computed:    true,
										Description: "Base64 encoded userscript。",
									},
									"unschedulable": {
										Type:        schema.TypeInt,
										Computed:    true,
										Description: "Set 是否added node participates in scheduling. The 默认值为 0，which means participating in scheduling; non-0 means not participating in scheduling. After the node initialization is completed，you can execute kubectl uncordon nodename to join the node in scheduling。",
									},
									"labels": {
										Type:        schema.TypeList,
										Computed:    true,
										Description: "Node 标签 array。",
										Elem: &schema.Resource{
											Schema: map[string]*schema.Schema{
												"name": {
													Type:        schema.TypeString,
													Computed:    true,
													Description: "名称 in the map table。",
												},
												"value": {
													Type:        schema.TypeString,
													Computed:    true,
													Description: "值 in map table。",
												},
											},
										},
									},
									"data_disks": {
										Type:        schema.TypeList,
										Computed:    true,
										Description: "Multi-disk data disk mounting information。",
										Elem: &schema.Resource{
											Schema: map[string]*schema.Schema{
												"disk_type": {
													Type:        schema.TypeString,
													Computed:    true,
													Description: "Cloud disk 类型",
												},
												"file_system": {
													Type:        schema.TypeString,
													Computed:    true,
													Description: "File system (ext3/ext4/xfs)。",
												},
												"disk_size": {
													Type:        schema.TypeInt,
													Computed:    true,
													Description: "Cloud disk size (G)。",
												},
												"auto_format_and_mount": {
													Type:        schema.TypeBool,
													Computed:    true,
													Description: "是否automatically 格式 the disk and mount it。",
												},
												"mount_target": {
													Type:        schema.TypeString,
													Computed:    true,
													Description: "挂载目录",
												},
												"disk_partition": {
													Type:        schema.TypeString,
													Computed:    true,
													Description: "Mount device 名称 or partition 名称，必填 when and only when adding an existing node。",
												},
											},
										},
									},
									"extra_args": {
										Type:        schema.TypeList,
										Computed:    true,
										Description: "Node-related custom parameter information。",
										Elem: &schema.Resource{
											Schema: map[string]*schema.Schema{
												"kubelet": {
													Type:        schema.TypeSet,
													Computed:    true,
													Description: "Kubelet custom parameters。",
													Elem: &schema.Schema{
														Type: schema.TypeString,
													},
												},
											},
										},
									},
								},
							},
						},
						"created_time": {
							Type:        schema.TypeString,
							Computed:    true,
							Description: "Add time。",
						},
						"lan_ip": {
							Type:        schema.TypeString,
							Computed:    true,
							Description: "Node intranet IP。",
						},
						"node_pool_id": {
							Type:        schema.TypeString,
							Computed:    true,
							Description: "Resource pool ID。",
						},
						"autoscaling_group_id": {
							Type:        schema.TypeString,
							Computed:    true,
							Description: "Auto scaling 组 ID",
						},
					},
				},
			},

			"result_output_file": {
				Type:        schema.TypeString,
				Optional:    true,
				Description: "用于保存结果。",
			},
		},
	}
}

func dataSourceTencentCloudKubernetesClusterInstancesRead(d *schema.ResourceData, meta interface{}) error {
	defer tccommon.LogElapsed("data_source.tencentcloud_kubernetes_cluster_instances.read")()
	defer tccommon.InconsistentCheck(d, meta)()

	logId := tccommon.GetLogId(nil)
	ctx := tccommon.NewResourceLifeCycleHandleFuncContext(context.Background(), logId, d, meta)

	service := TkeService{client: meta.(tccommon.ProviderMeta).GetAPIV3Conn()}

	paramMap := make(map[string]interface{})
	if v, ok := d.GetOk("cluster_id"); ok {
		paramMap["ClusterId"] = helper.String(v.(string))
	}

	if v, ok := d.GetOk("instance_ids"); ok {
		instanceIdsList := []*string{}
		instanceIdsSet := v.(*schema.Set).List()
		for i := range instanceIdsSet {
			instanceIds := instanceIdsSet[i].(string)
			instanceIdsList = append(instanceIdsList, helper.String(instanceIds))
		}
		paramMap["InstanceIds"] = instanceIdsList
	}

	if v, ok := d.GetOk("instance_role"); ok {
		paramMap["InstanceRole"] = helper.String(v.(string))
	}

	if v, ok := d.GetOk("filters"); ok {
		filtersSet := v.([]interface{})
		tmpSet := make([]*tkev20180525.Filter, 0, len(filtersSet))
		for _, item := range filtersSet {
			filtersMap := item.(map[string]interface{})
			filter := tkev20180525.Filter{}
			if v, ok := filtersMap["name"]; ok {
				filter.Name = helper.String(v.(string))
			}
			if v, ok := filtersMap["values"]; ok {
				valuesSet := v.(*schema.Set).List()
				for i := range valuesSet {
					values := valuesSet[i].(string)
					filter.Values = append(filter.Values, helper.String(values))
				}
			}
			tmpSet = append(tmpSet, &filter)
		}
		paramMap["Filters"] = tmpSet
	}

	var respData []*tkev20180525.Instance
	err := resource.Retry(tccommon.ReadRetryTimeout, func() *resource.RetryError {
		result, e := service.DescribeKubernetesClusterInstancesByFilter(ctx, paramMap)
		if e != nil {
			return tccommon.RetryError(e)
		}
		respData = result
		return nil
	})
	if err != nil {
		return err
	}

	var ids []string
	instanceSetList := make([]map[string]interface{}, 0, len(respData))
	if respData != nil {
		for _, instanceSet := range respData {
			instanceSetMap := map[string]interface{}{}

			var instanceId string
			if instanceSet.InstanceId != nil {
				instanceSetMap["instance_id"] = instanceSet.InstanceId
				instanceId = *instanceSet.InstanceId
			}

			if instanceSet.InstanceRole != nil {
				instanceSetMap["instance_role"] = instanceSet.InstanceRole
			}

			if instanceSet.FailedReason != nil {
				instanceSetMap["failed_reason"] = instanceSet.FailedReason
			}

			if instanceSet.InstanceState != nil {
				instanceSetMap["instance_state"] = instanceSet.InstanceState
			}

			if instanceSet.DrainStatus != nil {
				instanceSetMap["drain_status"] = instanceSet.DrainStatus
			}

			instanceAdvancedSettingsMap := map[string]interface{}{}

			if instanceSet.InstanceAdvancedSettings != nil {
				if instanceSet.InstanceAdvancedSettings.DesiredPodNumber != nil {
					instanceAdvancedSettingsMap["desired_pod_number"] = instanceSet.InstanceAdvancedSettings.DesiredPodNumber
				}

				gPUArgsMap := map[string]interface{}{}

				if instanceSet.InstanceAdvancedSettings.GPUArgs != nil {
					if instanceSet.InstanceAdvancedSettings.GPUArgs.MIGEnable != nil {
						gPUArgsMap["mig_enable"] = instanceSet.InstanceAdvancedSettings.GPUArgs.MIGEnable
					}

					driverMap := map[string]interface{}{}

					if instanceSet.InstanceAdvancedSettings.GPUArgs.Driver != nil {
						if instanceSet.InstanceAdvancedSettings.GPUArgs.Driver.Version != nil {
							driverMap["version"] = instanceSet.InstanceAdvancedSettings.GPUArgs.Driver.Version
						}

						if instanceSet.InstanceAdvancedSettings.GPUArgs.Driver.Name != nil {
							driverMap["name"] = instanceSet.InstanceAdvancedSettings.GPUArgs.Driver.Name
						}

						gPUArgsMap["driver"] = []interface{}{driverMap}
					}

					cUDAMap := map[string]interface{}{}

					if instanceSet.InstanceAdvancedSettings.GPUArgs.CUDA != nil {
						if instanceSet.InstanceAdvancedSettings.GPUArgs.CUDA.Version != nil {
							cUDAMap["version"] = instanceSet.InstanceAdvancedSettings.GPUArgs.CUDA.Version
						}

						if instanceSet.InstanceAdvancedSettings.GPUArgs.CUDA.Name != nil {
							cUDAMap["name"] = instanceSet.InstanceAdvancedSettings.GPUArgs.CUDA.Name
						}

						gPUArgsMap["cuda"] = []interface{}{cUDAMap}
					}

					cUDNNMap := map[string]interface{}{}

					if instanceSet.InstanceAdvancedSettings.GPUArgs.CUDNN != nil {
						if instanceSet.InstanceAdvancedSettings.GPUArgs.CUDNN.Version != nil {
							cUDNNMap["version"] = instanceSet.InstanceAdvancedSettings.GPUArgs.CUDNN.Version
						}

						if instanceSet.InstanceAdvancedSettings.GPUArgs.CUDNN.Name != nil {
							cUDNNMap["name"] = instanceSet.InstanceAdvancedSettings.GPUArgs.CUDNN.Name
						}

						if instanceSet.InstanceAdvancedSettings.GPUArgs.CUDNN.DocName != nil {
							cUDNNMap["doc_name"] = instanceSet.InstanceAdvancedSettings.GPUArgs.CUDNN.DocName
						}

						if instanceSet.InstanceAdvancedSettings.GPUArgs.CUDNN.DevName != nil {
							cUDNNMap["dev_name"] = instanceSet.InstanceAdvancedSettings.GPUArgs.CUDNN.DevName
						}

						gPUArgsMap["cudnn"] = []interface{}{cUDNNMap}
					}

					customDriverMap := map[string]interface{}{}

					if instanceSet.InstanceAdvancedSettings.GPUArgs.CustomDriver != nil {
						if instanceSet.InstanceAdvancedSettings.GPUArgs.CustomDriver.Address != nil {
							customDriverMap["address"] = instanceSet.InstanceAdvancedSettings.GPUArgs.CustomDriver.Address
						}

						gPUArgsMap["custom_driver"] = []interface{}{customDriverMap}
					}

					instanceAdvancedSettingsMap["gpu_args"] = []interface{}{gPUArgsMap}
				}

				if instanceSet.InstanceAdvancedSettings.PreStartUserScript != nil {
					instanceAdvancedSettingsMap["pre_start_user_script"] = instanceSet.InstanceAdvancedSettings.PreStartUserScript
				}

				taintsList := make([]map[string]interface{}, 0, len(instanceSet.InstanceAdvancedSettings.Taints))
				if instanceSet.InstanceAdvancedSettings.Taints != nil {
					for _, taints := range instanceSet.InstanceAdvancedSettings.Taints {
						taintsMap := map[string]interface{}{}

						if taints.Key != nil {
							taintsMap["key"] = taints.Key
						}

						if taints.Value != nil {
							taintsMap["value"] = taints.Value
						}

						if taints.Effect != nil {
							taintsMap["effect"] = taints.Effect
						}

						taintsList = append(taintsList, taintsMap)
					}

					instanceAdvancedSettingsMap["taints"] = taintsList
				}
				if instanceSet.InstanceAdvancedSettings.MountTarget != nil {
					instanceAdvancedSettingsMap["mount_target"] = instanceSet.InstanceAdvancedSettings.MountTarget
				}

				if instanceSet.InstanceAdvancedSettings.DockerGraphPath != nil {
					instanceAdvancedSettingsMap["docker_graph_path"] = instanceSet.InstanceAdvancedSettings.DockerGraphPath
				}

				if instanceSet.InstanceAdvancedSettings.UserScript != nil {
					instanceAdvancedSettingsMap["user_script"] = instanceSet.InstanceAdvancedSettings.UserScript
				}

				if instanceSet.InstanceAdvancedSettings.Unschedulable != nil {
					instanceAdvancedSettingsMap["unschedulable"] = instanceSet.InstanceAdvancedSettings.Unschedulable
				}

				labelsList := make([]map[string]interface{}, 0, len(instanceSet.InstanceAdvancedSettings.Labels))
				if instanceSet.InstanceAdvancedSettings.Labels != nil {
					for _, labels := range instanceSet.InstanceAdvancedSettings.Labels {
						labelsMap := map[string]interface{}{}

						if labels.Name != nil {
							labelsMap["name"] = labels.Name
						}

						if labels.Value != nil {
							labelsMap["value"] = labels.Value
						}

						labelsList = append(labelsList, labelsMap)
					}

					instanceAdvancedSettingsMap["labels"] = labelsList
				}
				dataDisksList := make([]map[string]interface{}, 0, len(instanceSet.InstanceAdvancedSettings.DataDisks))
				if instanceSet.InstanceAdvancedSettings.DataDisks != nil {
					for _, dataDisks := range instanceSet.InstanceAdvancedSettings.DataDisks {
						dataDisksMap := map[string]interface{}{}

						if dataDisks.DiskType != nil {
							dataDisksMap["disk_type"] = dataDisks.DiskType
						}

						if dataDisks.FileSystem != nil {
							dataDisksMap["file_system"] = dataDisks.FileSystem
						}

						if dataDisks.DiskSize != nil {
							dataDisksMap["disk_size"] = dataDisks.DiskSize
						}

						if dataDisks.AutoFormatAndMount != nil {
							dataDisksMap["auto_format_and_mount"] = dataDisks.AutoFormatAndMount
						}

						if dataDisks.MountTarget != nil {
							dataDisksMap["mount_target"] = dataDisks.MountTarget
						}

						if dataDisks.DiskPartition != nil {
							dataDisksMap["disk_partition"] = dataDisks.DiskPartition
						}

						dataDisksList = append(dataDisksList, dataDisksMap)
					}

					instanceAdvancedSettingsMap["data_disks"] = dataDisksList
				}
				extraArgsMap := map[string]interface{}{}

				if instanceSet.InstanceAdvancedSettings.ExtraArgs != nil {
					if instanceSet.InstanceAdvancedSettings.ExtraArgs.Kubelet != nil {
						extraArgsMap["kubelet"] = instanceSet.InstanceAdvancedSettings.ExtraArgs.Kubelet
					}

					instanceAdvancedSettingsMap["extra_args"] = []interface{}{extraArgsMap}
				}

				instanceSetMap["instance_advanced_settings"] = []interface{}{instanceAdvancedSettingsMap}
			}

			if instanceSet.CreatedTime != nil {
				instanceSetMap["created_time"] = instanceSet.CreatedTime
			}

			if instanceSet.LanIP != nil {
				instanceSetMap["lan_ip"] = instanceSet.LanIP
			}

			if instanceSet.NodePoolId != nil {
				instanceSetMap["node_pool_id"] = instanceSet.NodePoolId
			}

			if instanceSet.AutoscalingGroupId != nil {
				instanceSetMap["autoscaling_group_id"] = instanceSet.AutoscalingGroupId
			}

			ids = append(ids, instanceId)
			instanceSetList = append(instanceSetList, instanceSetMap)
		}

		_ = d.Set("instance_set", instanceSetList)
	}

	d.SetId(helper.DataResourceIdsHash(ids))

	output, ok := d.GetOk("result_output_file")
	if ok && output.(string) != "" {
		if e := tccommon.WriteToFile(output.(string), instanceSetList); e != nil {
			return e
		}
	}

	return nil
}
