// Code generated by iacg; DO NOT EDIT.
package tke

import (
	"context"
	"encoding/base64"

	"github.com/hashicorp/terraform-plugin-sdk/v2/helper/resource"
	"github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema"
	tkev20180525 "github.com/tencentcloud/tencentcloud-sdk-go/tencentcloud/tke/v20180525"
	tccommon "github.com/tencentcloudstack/terraform-provider-tencentcloud/tencentcloud/common"
)

func DataSourceTencentCloudKubernetesAddons() *schema.Resource {
	return &schema.Resource{
		Read: dataSourceTencentCloudKubernetesAddonsRead,
		Schema: map[string]*schema.Schema{
			"cluster_id": {
				Type:        schema.TypeString,
				Required:    true,
				Description: "集群 ID",
			},

			"addon_name": {
				Type:        schema.TypeString,
				Optional:    true,
				Description: "Add-在 名称 (all add-ons 在 集群 是 返回 如果 此 参数 是 不 指定)。",
			},

			"addons": {
				Type:        schema.TypeList,
				Computed:    true,
				Description: "列表 add-ons。",
				Elem: &schema.Resource{
					Schema: map[string]*schema.Schema{
						"addon_name": {
							Type:        schema.TypeString,
							Computed:    true,
							Description: "Add-在 名称",
						},
						"addon_version": {
							Type:        schema.TypeString,
							Computed:    true,
							Description: "Add-在 版本",
						},
						"raw_values": {
							Type:        schema.TypeString,
							Computed:    true,
							Description: "Add-在 参数，其中 是 base64-encoded strings 在 JSON/\nNote: 此 字段 可能 返回 `null`，indicating 该 无 有效 值 可以 是 获取。",
						},
						"decode_values": {
							Type:        schema.TypeString,
							Computed:    true,
							Description: "Decoded add-在 参数 (base64 decoded 从 raw_values).\nNote: 此 字段 可能 返回 空 字符串 如果 raw_values 是 null 或 无效 base64。",
						},
						"phase": {
							Type:        schema.TypeString,
							Computed:    true,
							Description: "Add-在 状态\nNote: 此 字段 可能 返回 `null`，indicating 该 无 有效 值 可以 是 获取。",
						},
						"reason": {
							Type:        schema.TypeString,
							Computed:    true,
							Description: "Reason 对于 add-在 failure\nNote: 此 字段 可能 返回 `null`，indicating 该 无 有效 值 可以 是 获取。",
						},
					},
				},
			},

			"result_output_file": {
				Type:        schema.TypeString,
				Optional:    true,
				Description: "用于保存结果。",
			},
		},
	}
}

func dataSourceTencentCloudKubernetesAddonsRead(d *schema.ResourceData, meta interface{}) error {
	defer tccommon.LogElapsed("data_source.tencentcloud_kubernetes_addons.read")()
	defer tccommon.InconsistentCheck(d, meta)()

	logId := tccommon.GetLogId(nil)
	ctx := tccommon.NewResourceLifeCycleHandleFuncContext(context.Background(), logId, d, meta)

	service := TkeService{client: meta.(tccommon.ProviderMeta).GetAPIV3Conn()}

	var (
		clusterId string
		addonName string
	)
	if v, ok := d.GetOk("cluster_id"); ok {
		clusterId = v.(string)
	}

	if v, ok := d.GetOk("addon_name"); ok {
		addonName = v.(string)
	}

	var respData []*tkev20180525.Addon
	reqErr := resource.Retry(tccommon.ReadRetryTimeout, func() *resource.RetryError {
		result, e := service.DescribeAddonList(ctx, clusterId, addonName)
		if e != nil {
			return tccommon.RetryError(e)
		}
		respData = result
		return nil
	})
	if reqErr != nil {
		return reqErr
	}

	addonsList := make([]map[string]interface{}, 0, len(respData))
	if respData != nil {
		for _, addons := range respData {
			addonsMap := map[string]interface{}{}

			if addons.AddonName != nil {
				addonsMap["addon_name"] = addons.AddonName
			}

			if addons.AddonVersion != nil {
				addonsMap["addon_version"] = addons.AddonVersion
			}

			if addons.RawValues != nil {
				addonsMap["raw_values"] = addons.RawValues
				// Decode base64 raw_values to decode_values
				if decoded, err := base64.StdEncoding.DecodeString(*addons.RawValues); err == nil {
					addonsMap["decode_values"] = string(decoded)
				} else {
					// If decode fails, set empty string
					addonsMap["decode_values"] = ""
				}
			}

			if addons.Phase != nil {
				addonsMap["phase"] = addons.Phase
			}

			if addons.Reason != nil {
				addonsMap["reason"] = addons.Reason
			}

			addonsList = append(addonsList, addonsMap)
		}

		_ = d.Set("addons", addonsList)
	}

	// Use cluster_id as the resource ID since it's a required parameter
	d.SetId(clusterId)

	output, ok := d.GetOk("result_output_file")
	if ok && output.(string) != "" {
		if e := tccommon.WriteToFile(output.(string), addonsList); e != nil {
			return e
		}
	}

	return nil
}
