// Code generated by iacg; DO NOT EDIT.
package tke

import (
	"context"
	"fmt"
	"log"
	"strings"

	"github.com/hashicorp/terraform-plugin-sdk/v2/helper/resource"
	"github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema"
	tkev20180525 "github.com/tencentcloud/tencentcloud-sdk-go/tencentcloud/tke/v20180525"
	tccommon "github.com/tencentcloudstack/terraform-provider-tencentcloud/tencentcloud/common"
	"github.com/tencentcloudstack/terraform-provider-tencentcloud/tencentcloud/internal/helper"
)

func ResourceTencentCloudKubernetesScaleWorker() *schema.Resource {
	return &schema.Resource{
		Create: resourceTencentCloudKubernetesScaleWorkerCreate,
		Read:   resourceTencentCloudKubernetesScaleWorkerRead,
		Delete: resourceTencentCloudKubernetesScaleWorkerDelete,
		Importer: &schema.ResourceImporter{
			StateContext: customScaleWorkerResourceImporter,
		},
		Schema: map[string]*schema.Schema{
			"cluster_id": {
				Type:        schema.TypeString,
				Required:    true,
				ForceNew:    true,
				Description: "ID cluster。",
			},

			"data_disk": {
				Type:        schema.TypeList,
				Optional:    true,
				ForceNew:    true,
				MaxItems:    11,
				Description: "TKE 数据盘配置",
				Elem: &schema.Resource{
					Schema: map[string]*schema.Schema{
						"auto_format_and_mount": {
							Type:        schema.TypeBool,
							Optional:    true,
							ForceNew:    true,
							Default:     false,
							Description: "Indicate 是否auto 格式 and mount or not. 默认为 `false`。",
						},
						"disk_size": {
							Type:        schema.TypeInt,
							Optional:    true,
							ForceNew:    true,
							Default:     0,
							Description: "Volume of disk （GB）。 默认为 `0`。",
						},
						"disk_type": {
							Type:        schema.TypeString,
							Optional:    true,
							ForceNew:    true,
							Default:     "CLOUD_PREMIUM",
							Description: "Types of disk，可用值：`CLOUD_PREMIUM` and `CLOUD_SSD` and `CLOUD_HSSD` and `CLOUD_TSSD`。",
						},
						"file_system": {
							Type:        schema.TypeString,
							Optional:    true,
							ForceNew:    true,
							Default:     "",
							Description: "File system，e.g. `ext3/ext4/xfs`。",
						},
						"mount_target": {
							Type:        schema.TypeString,
							Optional:    true,
							ForceNew:    true,
							Default:     "",
							Description: "挂载目标",
						},
						"disk_partition": {
							Type:        schema.TypeString,
							Optional:    true,
							ForceNew:    true,
							Default:     "",
							Description: "The 名称 device or partition to mount。",
						},
					},
				},
			},

			"desired_pod_num": {
				Type:        schema.TypeInt,
				Optional:    true,
				ForceNew:    true,
				Description: "Indicate to set desired pod number in current node. Valid when the cluster enable customized pod cidr。",
			},

			"docker_graph_path": {
				Type:        schema.TypeString,
				Optional:    true,
				ForceNew:    true,
				Description: "Docker graph 路径 默认为 `/var/lib/docker`。",
			},

			"extra_args": {
				Type:        schema.TypeList,
				Optional:    true,
				ForceNew:    true,
				Description: "Custom parameter information related to the node。",
				Elem: &schema.Schema{
					Type: schema.TypeString,
				},
			},

			"gpu_args": {
				Type:        schema.TypeList,
				Optional:    true,
				ForceNew:    true,
				MaxItems:    1,
				Description: "GPU driver parameters。",
				Elem: &schema.Resource{
					Schema: map[string]*schema.Schema{
						"cuda": {
							Type:        schema.TypeMap,
							Optional:    true,
							Description: "CUDA  版本 格式 like: `{ 版本: String，名称: String }`. `版本`: 版本 of GPU driver or CUDA; `名称`: 名称 GPU driver or CUDA。",
						},
						"cudnn": {
							Type:        schema.TypeMap,
							Optional:    true,
							Description: "cuDNN 版本 格式 like: `{ 版本: String，名称: String，doc_name: String，dev_name: String }`. `版本`: cuDNN 版本; `名称`: cuDNN 名称; `doc_name`: Doc 名称 cuDNN; `dev_name`: Dev 名称 cuDNN。",
						},
						"custom_driver": {
							Type:        schema.TypeMap,
							Optional:    true,
							Description: "Custom GPU driver. 格式 like: `{地址: String}`. `地址`: URL of custom GPU driver 地址",
						},
						"driver": {
							Type:        schema.TypeMap,
							Optional:    true,
							Description: "GPU driver 版本 格式 like: `{ 版本: String，名称: String }`. `版本`: 版本 of GPU driver or CUDA; `名称`: 名称 GPU driver or CUDA。",
						},
						"mig_enable": {
							Type:        schema.TypeBool,
							Optional:    true,
							Default:     false,
							Description: "是否enable MIG。",
						},
					},
				},
			},

			"labels": {
				Type:        schema.TypeMap,
				Optional:    true,
				ForceNew:    true,
				Description: "Labels of kubernetes scale worker created nodes。",
			},

			"mount_target": {
				Type:        schema.TypeString,
				Optional:    true,
				ForceNew:    true,
				Description: "挂载目标 默认为 not mounting。",
			},

			"unschedulable": {
				Type:        schema.TypeInt,
				Optional:    true,
				ForceNew:    true,
				Default:     0,
				Description: "Set 是否added node participates in scheduling. The 默认值为 0，which means participating in scheduling; non-0 means not participating in scheduling. After the node initialization is completed，you can execute kubectl uncordon nodename to join the node in scheduling。",
			},

			"worker_config": {
				Type:        schema.TypeList,
				Required:    true,
				ForceNew:    true,
				MaxItems:    1,
				MinItems:    1,
				Description: "Deploy the machine configuration information of the 'WORK' service，and create <=20 units for common users。",
				Elem: &schema.Resource{
					Schema: map[string]*schema.Schema{
						"availability_zone": {
							Type:        schema.TypeString,
							Optional:    true,
							ForceNew:    true,
							Description: "表示which availability 可用区 will be used。",
						},
						"bandwidth_package_id": {
							Type:        schema.TypeString,
							Optional:    true,
							Description: "bandwidth package id. if 用户 is standard 用户，then the bandwidth_package_id is needed，or default has bandwidth_package_id。",
						},
						"cam_role_name": {
							Type:        schema.TypeString,
							Optional:    true,
							ForceNew:    true,
							Description: "被授权访问的 CAM 角色名称",
						},
						"count": {
							Type:        schema.TypeInt,
							Optional:    true,
							ForceNew:    true,
							Default:     1,
							Description: "数量 cvm。",
						},
						"data_disk": {
							Type:        schema.TypeList,
							Optional:    true,
							ForceNew:    true,
							MaxItems:    11,
							Description: "CVM 数据盘配置",
							Elem: &schema.Resource{
								Schema: map[string]*schema.Schema{
									"auto_format_and_mount": {
										Type:        schema.TypeBool,
										Optional:    true,
										ForceNew:    true,
										Default:     false,
										Description: "Indicate 是否auto 格式 and mount or not. 默认为 `false`。",
										Deprecated:  "This argument was deprecated, use `data_disk` instead.",
									},
									"disk_partition": {
										Type:        schema.TypeString,
										Optional:    true,
										ForceNew:    true,
										Description: "The 名称 device or partition to mount。",
										Deprecated:  "This argument was deprecated, use `data_disk` instead.",
									},
									"disk_size": {
										Type:        schema.TypeInt,
										Optional:    true,
										ForceNew:    true,
										Default:     0,
										Description: "Volume of disk （GB）。 默认为 `0`。",
									},
									"disk_type": {
										Type:        schema.TypeString,
										Optional:    true,
										ForceNew:    true,
										Default:     "CLOUD_PREMIUM",
										Description: "Types of disk，可用值：`CLOUD_PREMIUM` and `CLOUD_SSD` and `CLOUD_HSSD` and `CLOUD_TSSD`。",
									},
									"encrypt": {
										Type:        schema.TypeBool,
										Optional:    true,
										Description: "表示是否encrypt data disk，default `false`。",
									},
									"file_system": {
										Type:        schema.TypeString,
										Optional:    true,
										ForceNew:    true,
										Description: "File system，e.g. `ext3/ext4/xfs`。",
										Deprecated:  "This argument was deprecated, use `data_disk` instead.",
									},
									"kms_key_id": {
										Type:        schema.TypeString,
										Optional:    true,
										Description: "ID custom CMK in the 格式 of UUID or `kms-abcd1234`. This parameter is 用于encrypt cloud disks。",
									},
									"mount_target": {
										Type:        schema.TypeString,
										Optional:    true,
										ForceNew:    true,
										Description: "挂载目标",
										Deprecated:  "This argument was deprecated, use `data_disk` instead.",
									},
									"snapshot_id": {
										Type:        schema.TypeString,
										Optional:    true,
										ForceNew:    true,
										Description: "Data disk snapshot ID。",
									},
								},
							},
						},
						"desired_pod_num": {
							Type:        schema.TypeInt,
							Optional:    true,
							ForceNew:    true,
							Default:     0,
							Description: "Indicate to set desired pod number in node. valid when enable_customized_pod_cidr=true，and it override `[globe_]desired_pod_num` for current node. Either all the fields `desired_pod_num` or none。",
						},
						"disaster_recover_group_ids": {
							Type:        schema.TypeList,
							Optional:    true,
							ForceNew:    true,
							Description: "Disaster recover groups to which a CVM instance belongs. Only support maximum 1。",
							Elem: &schema.Schema{
								Type: schema.TypeString,
							},
						},
						"enhanced_monitor_service": {
							Type:        schema.TypeBool,
							Optional:    true,
							ForceNew:    true,
							Default:     true,
							Description: "To 指定是否enable cloud monitor service. 默认为 TRUE。",
						},
						"enhanced_security_service": {
							Type:        schema.TypeBool,
							Optional:    true,
							ForceNew:    true,
							Default:     true,
							Description: "To 指定是否enable cloud security service. 默认为 TRUE。",
						},
						"hostname": {
							Type:        schema.TypeString,
							Optional:    true,
							ForceNew:    true,
							Description: "The 主机 名称 attached instance. Dot (.) and dash (-) cannot be used as the first and last characters of HostName and cannot be used consecutively. Windows example: The length of the 名称 character is [2，15]，letters (capitalization is not restricted)，numbers and dashes (-) are allowed，dots (.) are not supported，and not all numbers are allowed. Examples of other types (Linux，etc.): The character length is [2，60]，and multiple dots are allowed. There is a segment between the dots. Each segment allows letters (with no limitation on capitalization)，numbers and dashes (-)。",
						},
						"hpc_cluster_id": {
							Type:        schema.TypeString,
							Optional:    true,
							Description: "Id of cvm hpc cluster。",
						},
						"img_id": {
							Type:        schema.TypeString,
							Optional:    true,
							Description: "The valid image id，格式 of img-xxx。",
						},
						"instance_charge_type": {
							Type:        schema.TypeString,
							Optional:    true,
							ForceNew:    true,
							Default:     "POSTPAID_BY_HOUR",
							Description: "The charge 类型 instance. Valid values are `PREPAID`，`POSTPAID_BY_HOUR`，`SPOTPAID`，`CDCPAID`. The 默认为 `POSTPAID_BY_HOUR`. Note: TencentCloud International only supports `POSTPAID_BY_HOUR`，`PREPAID` instance will not terminated after cluster deleted，and may not allow to delete before expired。",
						},
						"instance_charge_type_prepaid_period": {
							Type:        schema.TypeInt,
							Optional:    true,
							ForceNew:    true,
							Default:     1,
							Description: "The tenancy (time unit is month) of the prepaid instance. NOTE: it only works when instance_charge_type is set to `PREPAID`. Valid values are `1`，`2`，`3`，`4`，`5`，`6`，`7`，`8`，`9`，`10`，`11`，`12`，`24`，`36`。",
						},
						"instance_charge_type_prepaid_renew_flag": {
							Type:        schema.TypeString,
							Optional:    true,
							Computed:    true,
							ForceNew:    true,
							Description: "自动续费标识 有效值：`NOTIFY_AND_AUTO_RENEW`: notify upon expiration and renew automatically，`NOTIFY_AND_MANUAL_RENEW`: notify upon expiration but do not renew automatically，`DISABLE_NOTIFY_AND_MANUAL_RENEW`: neither notify upon expiration nor renew automatically. 默认值：`NOTIFY_AND_MANUAL_RENEW`. If this parameter is specified as `NOTIFY_AND_AUTO_RENEW`，the instance will be automatically renewed on a monthly basis if the 账号 balance is sufficient. NOTE: it only works when instance_charge_type is set to `PREPAID`。",
						},
						"instance_name": {
							Type:        schema.TypeString,
							Optional:    true,
							ForceNew:    true,
							Default:     "sub machine of tke",
							Description: "名称 CVMs。",
						},
						"instance_type": {
							Type:        schema.TypeString,
							Required:    true,
							ForceNew:    true,
							Description: "Specified types of CVM instance。",
						},
						"internet_charge_type": {
							Type:        schema.TypeString,
							Optional:    true,
							ForceNew:    true,
							Default:     "TRAFFIC_POSTPAID_BY_HOUR",
							Description: "Charge types for network traffic. Available values include `TRAFFIC_POSTPAID_BY_HOUR`。",
						},
						"internet_max_bandwidth_out": {
							Type:        schema.TypeInt,
							Optional:    true,
							Default:     0,
							Description: "Max bandwidth of Internet access in Mbps. 默认为 0。",
						},
						"key_ids": {
							Type:        schema.TypeList,
							Optional:    true,
							ForceNew:    true,
							MaxItems:    1,
							Description: "ID 列表 keys，should be set if `密码` not set。",
							Elem: &schema.Schema{
								Type: schema.TypeString,
							},
						},
						"password": {
							Type:        schema.TypeString,
							Optional:    true,
							ForceNew:    true,
							Sensitive:   true,
							Description: "密码 to access，should be set if `key_ids` not set。",
						},
						"public_ip_assigned": {
							Type:        schema.TypeBool,
							Optional:    true,
							ForceNew:    true,
							Description: "指定是否assign an 公网 IP 地址",
						},
						"security_group_ids": {
							Type:        schema.TypeList,
							Optional:    true,
							ForceNew:    true,
							Description: "Security groups to which a CVM instance belongs。",
							Elem: &schema.Schema{
								Type: schema.TypeString,
							},
						},
						"subnet_id": {
							Type:        schema.TypeString,
							Required:    true,
							ForceNew:    true,
							Description: "Private network ID。",
						},
						"system_disk_size": {
							Type:        schema.TypeInt,
							Optional:    true,
							ForceNew:    true,
							Default:     50,
							Description: "Volume of system disk （GB）。 默认为 `50`。",
						},
						"system_disk_type": {
							Type:        schema.TypeString,
							Optional:    true,
							ForceNew:    true,
							Default:     "CLOUD_PREMIUM",
							Description: "System disk 类型 For more information on limits of system disk types，see [Storage Overview](https://intl.cloud.tencent.com/document/product/213/4952). 有效值：`LOCAL_BASIC`: local disk，`LOCAL_SSD`: local SSD disk，`CLOUD_SSD`: SSD，`CLOUD_PREMIUM`: Premium Cloud Storage. NOTE: `CLOUD_BASIC`，`LOCAL_BASIC` and `LOCAL_SSD` are 已弃用",
						},
						"user_data": {
							Type:        schema.TypeString,
							Optional:    true,
							ForceNew:    true,
							Description: "用户 data provided to instances，needs to be encoded in base64，and the maximum supported data size is 16KB。",
						},
						"tags": {
							Type:        schema.TypeList,
							Optional:    true,
							ForceNew:    true,
							Computed:    true,
							Description: "标签 pairs。",
							Elem: &schema.Resource{
								Schema: map[string]*schema.Schema{
									"key": {
										Type:        schema.TypeString,
										Required:    true,
										ForceNew:    true,
										Description: "标签键",
									},
									"value": {
										Type:        schema.TypeString,
										Required:    true,
										ForceNew:    true,
										Description: "标签值",
									},
								},
							},
						},
						"cdc_id": {
							Type:        schema.TypeString,
							Optional:    true,
							ForceNew:    true,
							Description: "CDC ID。",
						},
					},
				},
			},

			"pre_start_user_script": {
				Type:        schema.TypeString,
				Optional:    true,
				ForceNew:    true,
				Description: "Base64-encoded 用户 script，executed before initializing the node，currently only effective for adding existing nodes。",
			},

			"taints": {
				Type:        schema.TypeList,
				Optional:    true,
				ForceNew:    true,
				Description: "Node taint。",
				Elem: &schema.Resource{
					Schema: map[string]*schema.Schema{
						"key": {
							Type:        schema.TypeString,
							Optional:    true,
							ForceNew:    true,
							Description: "键 of the taint。",
						},
						"value": {
							Type:        schema.TypeString,
							Optional:    true,
							ForceNew:    true,
							Description: "值 of the taint。",
						},
						"effect": {
							Type:        schema.TypeString,
							Optional:    true,
							ForceNew:    true,
							Description: "Effect of the taint。",
						},
					},
				},
			},

			"user_script": {
				Type:        schema.TypeString,
				Optional:    true,
				ForceNew:    true,
				Description: "Base64 encoded 用户 script，this script will be executed after the k8s component is run. The 用户 needs to ensure that the script is reentrant and retry logic. The script and its generated log files can be viewed in the /data/ccs_userscript/ 路径 of the node，if 必填 The node needs to be initialized before it can be added to the schedule. It can be used with the unschedulable parameter. After the final initialization of userScript is completed，add the kubectl uncordon nodename --kubeconfig=/root/.kube/配置 command to add the node to the schedule。",
			},

			"worker_instances_list": {
				Type:        schema.TypeList,
				Computed:    true,
				Description: "An information 列表 kubernetes cluster 'WORKER'. Each element 包含following attributes:",
				Elem: &schema.Resource{
					Schema: map[string]*schema.Schema{
						"failed_reason": {
							Type:        schema.TypeString,
							Computed:    true,
							Description: "Information of the cvm when it is failed。",
						},
						"instance_id": {
							Type:        schema.TypeString,
							Computed:    true,
							Description: "ID cvm。",
						},
						"instance_role": {
							Type:        schema.TypeString,
							Computed:    true,
							Description: "角色 of the cvm。",
						},
						"instance_state": {
							Type:        schema.TypeString,
							Computed:    true,
							Description: "State of the cvm。",
						},
						"lan_ip": {
							Type:        schema.TypeString,
							Computed:    true,
							Description: "LAN IP of the cvm。",
						},
					},
				},
			},

			"create_result_output_file": {
				Type:        schema.TypeString,
				Optional:    true,
				ForceNew:    true,
				Description: "用于保存结果 of CVMs creation 错误 messages。",
			},
		},
	}
}

func resourceTencentCloudKubernetesScaleWorkerCreate(d *schema.ResourceData, meta interface{}) error {
	defer tccommon.LogElapsed("resource.tencentcloud_kubernetes_scale_worker.create")()
	defer tccommon.InconsistentCheck(d, meta)()

	logId := tccommon.GetLogId(tccommon.ContextNil)

	ctx := tccommon.NewResourceLifeCycleHandleFuncContext(context.Background(), logId, d, meta)

	if err := resourceTencentCloudKubernetesScaleWorkerCreateOnStart(ctx); err != nil {
		return err
	}

	_ = ctx
	return resourceTencentCloudKubernetesScaleWorkerRead(d, meta)
}

func resourceTencentCloudKubernetesScaleWorkerRead(d *schema.ResourceData, meta interface{}) error {
	defer tccommon.LogElapsed("resource.tencentcloud_kubernetes_scale_worker.read")()
	defer tccommon.InconsistentCheck(d, meta)()

	logId := tccommon.GetLogId(tccommon.ContextNil)

	ctx := tccommon.NewResourceLifeCycleHandleFuncContext(context.Background(), logId, d, meta)

	service := TkeService{client: meta.(tccommon.ProviderMeta).GetAPIV3Conn()}

	idSplit := strings.Split(d.Id(), tccommon.FILED_SP)
	if len(idSplit) != 2 {
		return fmt.Errorf("id is broken,%s", d.Id())
	}
	clusterId := idSplit[0]
	instanceIdSet := idSplit[1]

	_ = d.Set("cluster_id", clusterId)

	respData, err := service.DescribeKubernetesScaleWorkerById(ctx, clusterId)
	if err != nil {
		return err
	}

	if respData == nil {
		d.SetId("")
		log.Printf("[WARN]%s resource `kubernetes_scale_worker` [%s] not found, please check if it has been deleted.\n", logId, d.Id())
		return nil
	}
	if err := resourceTencentCloudKubernetesScaleWorkerReadPostHandleResponse0(ctx, respData); err != nil {
		return err
	}

	_ = instanceIdSet
	return nil
}

func resourceTencentCloudKubernetesScaleWorkerDelete(d *schema.ResourceData, meta interface{}) error {
	defer tccommon.LogElapsed("resource.tencentcloud_kubernetes_scale_worker.delete")()
	defer tccommon.InconsistentCheck(d, meta)()

	logId := tccommon.GetLogId(tccommon.ContextNil)
	ctx := tccommon.NewResourceLifeCycleHandleFuncContext(context.Background(), logId, d, meta)

	idSplit := strings.Split(d.Id(), tccommon.FILED_SP)
	if len(idSplit) != 2 {
		return fmt.Errorf("id is broken,%s", d.Id())
	}
	clusterId := idSplit[0]
	instanceIdSet := idSplit[1]

	var (
		request  = tkev20180525.NewDescribeClustersRequest()
		response = tkev20180525.NewDescribeClustersResponse()
	)

	request.ClusterIds = []*string{helper.String(clusterId)}

	err := resource.Retry(tccommon.WriteRetryTimeout, func() *resource.RetryError {
		result, e := meta.(tccommon.ProviderMeta).GetAPIV3Conn().UseTkeV20180525Client().DescribeClustersWithContext(ctx, request)
		if e != nil {
			return tccommon.RetryError(e)
		} else {
			log.Printf("[DEBUG]%s api[%s] success, request body [%s], response body [%s]\n", logId, request.GetAction(), request.ToJsonString(), result.ToJsonString())
		}
		if err := resourceTencentCloudKubernetesScaleWorkerDeletePostRequest0(ctx, request, result); err != nil {
			return err
		}

		response = result
		return nil
	})
	if err != nil {
		log.Printf("[CRITAL]%s delete kubernetes scale worker failed, reason:%+v", logId, err)
		return err
	}

	_ = response
	if err := resourceTencentCloudKubernetesScaleWorkerDeleteOnExit(ctx); err != nil {
		return err
	}

	_ = instanceIdSet
	return nil
}
