// Code generated by iacg; DO NOT EDIT.
package tke

import (
	"context"
	"fmt"
	"log"
	"strings"
	"time"

	"github.com/hashicorp/terraform-plugin-sdk/v2/helper/resource"
	"github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema"
	tkev20180525 "github.com/tencentcloud/tencentcloud-sdk-go/tencentcloud/tke/v20180525"

	tccommon "github.com/tencentcloudstack/terraform-provider-tencentcloud/tencentcloud/common"
	"github.com/tencentcloudstack/terraform-provider-tencentcloud/tencentcloud/internal/helper"
	svcas "github.com/tencentcloudstack/terraform-provider-tencentcloud/tencentcloud/services/as"
	svccvm "github.com/tencentcloudstack/terraform-provider-tencentcloud/tencentcloud/services/cvm"
)

func ResourceTencentCloudKubernetesNodePool() *schema.Resource {
	return &schema.Resource{
		Create: resourceTencentCloudKubernetesNodePoolCreate,
		Read:   resourceTencentCloudKubernetesNodePoolRead,
		Update: resourceTencentCloudKubernetesNodePoolUpdate,
		Delete: resourceTencentCloudKubernetesNodePoolDelete,
		Timeouts: &schema.ResourceTimeout{
			Create: schema.DefaultTimeout(30 * time.Minute),
			Update: schema.DefaultTimeout(30 * time.Minute),
		},
		Importer: &schema.ResourceImporter{
			StateContext: nodePoolCustomResourceImporter,
		},
		Schema: map[string]*schema.Schema{
			"cluster_id": {
				Type:        schema.TypeString,
				Required:    true,
				ForceNew:    true,
				Description: "ID 集群。",
			},

			"name": {
				Type:        schema.TypeString,
				Required:    true,
				Description: "名称 节点 池. 名称 does 不 exceed 25 字符，和 仅 支持 Chinese，English，numbers，underscores，separators (`-`) 和 decimal points。",
			},

			"max_size": {
				Type:         schema.TypeInt,
				Required:     true,
				Description:  "最大node。",
				ValidateFunc: tccommon.ValidateIntegerInRange(0, 2000),
			},

			"min_size": {
				Type:         schema.TypeInt,
				Required:     true,
				Description:  "最小node。",
				ValidateFunc: tccommon.ValidateIntegerInRange(0, 2000),
			},

			"desired_capacity": {
				Type:         schema.TypeInt,
				Optional:     true,
				Computed:     true,
				Description:  "Desired 容量 的 节点. 如果 `enable_auto_scale` 是 集合 `true`，此 将 是 computed 参数。",
				ValidateFunc: tccommon.ValidateIntegerInRange(0, 2000),
			},

			"wait_node_ready": {
				Type:        schema.TypeBool,
				Optional:    true,
				Description: "是否wait 对于 all desired nodes 到 是 ready. 默认为 false. Only 可以 是 集合 如果 `enable_auto_scale` 是 `false`。",
			},

			"scale_tolerance": {
				Type:         schema.TypeInt,
				Optional:     true,
				Description:  "Control how many expectations(`desired_capacity`) 可以 是 tolerated successfully. Unit 是 percentage，默认为 `100`. Only 可以 是 集合 如果 `wait_node_ready` 是 `true`。",
				ValidateFunc: tccommon.ValidateIntegerInRange(0, 100),
			},

			"enable_auto_scale": {
				Type:        schema.TypeBool,
				Optional:    true,
				Default:     true,
				Description: "Indicate 是否enable auto scaling 或 不。",
			},

			"retry_policy": {
				Type:         schema.TypeString,
				Optional:     true,
				ForceNew:     true,
				Default:      "IMMEDIATE_RETRY",
				Description:  "Available 值 对于 retry policies include `IMMEDIATE_RETRY` 和 `INCREMENTAL_INTERVALS`。",
				ValidateFunc: tccommon.ValidateAllowedStringValue([]string{svcas.SCALING_GROUP_RETRY_POLICY_IMMEDIATE_RETRY, svcas.SCALING_GROUP_RETRY_POLICY_INCREMENTAL_INTERVALS, svcas.SCALING_GROUP_RETRY_POLICY_NO_RETRY}),
			},

			"vpc_id": {
				Type:        schema.TypeString,
				Required:    true,
				ForceNew:    true,
				Description: "ID VPC 网络。",
			},

			"subnet_ids": {
				Type:        schema.TypeList,
				Optional:    true,
				ForceNew:    true,
				Description: "ID 列表 子网，和 对于 VPC 它 为必填项。",
				Elem: &schema.Schema{
					Type: schema.TypeString,
				},
			},

			"scaling_mode": {
				Type:        schema.TypeString,
				Optional:    true,
				ForceNew:    true,
				Description: "Auto scaling 模式 有效 值 是 `CLASSIC_SCALING`(scaling 通过 create/destroy 实例)，`WAKE_UP_STOPPED_SCALING`(Boot 优先级 对于 expansion. 当 expanding 容量， shutdown operation 是 given 优先级 到 shutdown 的 实例. 如果 数量 实例 是 still lower 比 expected 数量 实例 after startup， 实例 将 是 创建，和 方法 的 destroying 实例 将 still 是 用于shrinking)。",
			},

			"auto_update_instance_tags": {
				Type:        schema.TypeBool,
				Optional:    true,
				Computed:    true,
				ForceNew:    true,
				Description: "Automatically update 实例 标签 默认值为 false. After 配置，如果 scaling 组 标签 是 更新， 标签 的 running 实例 在 scaling 组 将 是 更新 synchronously (synchronous updates 仅 support adding 和 modifying 标签，和 do 不 support deleting 标签 对于 时间 being). Synchronous updates do 不 take effect immediately 和 there 是 certain 延迟",
			},

			"multi_zone_subnet_policy": {
				Type:         schema.TypeString,
				Optional:     true,
				Description:  "Multi-availability 可用区/子网 策略. 有效值：PRIORITY 和 EQUALITY. 默认值：PRIORITY。",
				ValidateFunc: tccommon.ValidateAllowedStringValue([]string{svcas.MultiZoneSubnetPolicyPriority, svcas.MultiZoneSubnetPolicyEquality}),
			},

			"node_config": {
				Type:        schema.TypeList,
				Optional:    true,
				MaxItems:    1,
				Description: "Node 配置",
				Elem: &schema.Resource{
					Schema: map[string]*schema.Schema{
						"mount_target": {
							Type:        schema.TypeString,
							Optional:    true,
							ForceNew:    true,
							Description: "挂载目标 默认为 不 mounting。",
						},
						"docker_graph_path": {
							Type:        schema.TypeString,
							Optional:    true,
							ForceNew:    true,
							Default:     "/var/lib/docker",
							Description: "Docker graph 路径 默认为 `/var/lib/docker`。",
						},
						"data_disk": {
							Type:        schema.TypeList,
							Optional:    true,
							ForceNew:    true,
							MaxItems:    11,
							Description: "数据盘配置",
							Elem: &schema.Resource{
								Schema: map[string]*schema.Schema{
									"disk_type": {
										Type:         schema.TypeString,
										Optional:     true,
										ForceNew:     true,
										Default:      "CLOUD_PREMIUM",
										Description:  "Types 的 磁盘. 有效 值: `LOCAL_BASIC`，`LOCAL_SSD`，`CLOUD_BASIC`，`CLOUD_PREMIUM`，`CLOUD_SSD`，`CLOUD_HSSD`，`CLOUD_TSSD`，`CLOUD_BSSD` 和 `LOCAL_NVME`。",
										ValidateFunc: tccommon.ValidateAllowedStringValue(svcas.SYSTEM_DISK_ALLOW_TYPE),
									},
									"disk_size": {
										Type:        schema.TypeInt,
										Optional:    true,
										ForceNew:    true,
										Default:     0,
										Description: "Volume 的 磁盘 （GB）。 默认为 `0`。",
									},
									"file_system": {
										Type:        schema.TypeString,
										Optional:    true,
										ForceNew:    true,
										Default:     "",
										Description: "File 系统，e.g. `ext3/ext4/xfs`。",
									},
									"auto_format_and_mount": {
										Type:        schema.TypeBool,
										Optional:    true,
										ForceNew:    true,
										Default:     false,
										Description: "Indicate 是否auto 格式 和 mount 或 不. 默认为 `false`。",
									},
									"mount_target": {
										Type:        schema.TypeString,
										Optional:    true,
										ForceNew:    true,
										Default:     "",
										Description: "挂载目标",
									},
									"disk_partition": {
										Type:        schema.TypeString,
										Optional:    true,
										ForceNew:    true,
										Description: "名称 device 或 分区 到 mount. NOTE: 此 argument doesn't support setting 在 节点 池，或 将 leads 到 mount 错误",
									},
								},
							},
						},
						"extra_args": {
							Type:        schema.TypeList,
							Optional:    true,
							ForceNew:    true,
							Description: "Custom 参数 信息 related 到 节点. 此 是 white-列表 参数。",
							Elem: &schema.Schema{
								Type: schema.TypeString,
							},
						},
						"user_data": {
							Type:        schema.TypeString,
							Optional:    true,
							Description: "Base64-encoded 用户 Data text， 长度 限制 是 16KB。",
						},
						"pre_start_user_script": {
							Type:        schema.TypeString,
							Optional:    true,
							Description: "Base64-encoded 用户 脚本，executed before initializing 节点，currently 仅 effective 对于 adding existing nodes。",
						},
						"is_schedule": {
							Type:        schema.TypeBool,
							Optional:    true,
							ForceNew:    true,
							Default:     true,
							Description: "Indicate 到 调度 adding 节点 或 不. 默认为 true。",
						},
						"desired_pod_num": {
							Type:        schema.TypeInt,
							Optional:    true,
							ForceNew:    true,
							Description: "Indicate 到 集合 desired pod 数量 在 节点. 有效 当 集群 是 podCIDR。",
						},
						"gpu_args": {
							Type:        schema.TypeList,
							Optional:    true,
							ForceNew:    true,
							MaxItems:    1,
							Description: "GPU 驱动 参数。",
							Elem: &schema.Resource{
								Schema: map[string]*schema.Schema{
									"mig_enable": {
										Type:        schema.TypeBool,
										Optional:    true,
										Default:     false,
										Description: "是否enable MIG。",
									},
									"driver": {
										Type:         schema.TypeMap,
										Optional:     true,
										Description:  "GPU 驱动 版本 格式 like: `{ 版本: String，名称: String }`. `版本`: 版本 的 GPU 驱动 或 CUDA; `名称`: 名称 GPU 驱动 或 CUDA。",
										ValidateFunc: tccommon.ValidateTkeGpuDriverVersion,
									},
									"cuda": {
										Type:         schema.TypeMap,
										Optional:     true,
										Description:  "CUDA 版本 格式 like: `{ 版本: String，名称: String }`. `版本`: 版本 的 GPU 驱动 或 CUDA; `名称`: 名称 GPU 驱动 或 CUDA。",
										ValidateFunc: tccommon.ValidateTkeGpuDriverVersion,
									},
									"cudnn": {
										Type:         schema.TypeMap,
										Optional:     true,
										Description:  "cuDNN 版本 格式 like: `{ 版本: String，名称: String，doc_name: String，dev_name: String }`. `版本`: cuDNN 版本; `名称`: cuDNN 名称; `doc_name`: Doc 名称 cuDNN; `dev_name`: Dev 名称 cuDNN。",
										ValidateFunc: tccommon.ValidateTkeGpuDriverVersion,
									},
									"custom_driver": {
										Type:        schema.TypeMap,
										Optional:    true,
										Description: "Custom GPU 驱动. 格式 like: `{地址: String}`. `地址`: URL 的 自定义 GPU 驱动 地址",
									},
								},
							},
						},
					},
				},
			},

			"auto_scaling_config": {
				Type:        schema.TypeList,
				Required:    true,
				MaxItems:    1,
				Description: "Auto scaling 配置 参数。",
				Elem: &schema.Resource{
					Schema: map[string]*schema.Schema{
						"instance_type": {
							Type:        schema.TypeString,
							Required:    true,
							ForceNew:    true,
							Description: "Specified types 的 CVM 实例。",
						},
						"backup_instance_types": {
							Type:        schema.TypeList,
							Optional:    true,
							Description: "Backup CVM 实例 types 如果 指定 实例类型 sold out 或 mismatch。",
							Elem: &schema.Schema{
								Type: schema.TypeString,
							},
						},
						"system_disk_type": {
							Type:         schema.TypeString,
							Optional:     true,
							Default:      "CLOUD_PREMIUM",
							Description:  "类型 CVM 磁盘. 有效 值: `LOCAL_BASIC`，`LOCAL_SSD`，`CLOUD_BASIC`，`CLOUD_PREMIUM`，`CLOUD_SSD`，`CLOUD_HSSD`，`CLOUD_TSSD`，`CLOUD_BSSD` 和 `LOCAL_NVME`. 默认为 `CLOUD_PREMIUM`。",
							ValidateFunc: tccommon.ValidateAllowedStringValue(svcas.SYSTEM_DISK_ALLOW_TYPE),
						},
						"system_disk_size": {
							Type:         schema.TypeInt,
							Optional:     true,
							Default:      50,
							Description:  "Volume 的 系统 磁盘 （GB）。 默认为 `50`。",
							ValidateFunc: tccommon.ValidateIntegerInRange(20, 2048),
						},
						"data_disk": {
							Type:        schema.TypeList,
							Optional:    true,
							Description: "数据盘配置",
							Elem: &schema.Resource{
								Schema: map[string]*schema.Schema{
									"disk_type": {
										Type:         schema.TypeString,
										Optional:     true,
										Default:      "CLOUD_PREMIUM",
										Description:  "Types 的 磁盘. 有效 值: `LOCAL_BASIC`，`LOCAL_SSD`，`CLOUD_BASIC`，`CLOUD_PREMIUM`，`CLOUD_SSD`，`CLOUD_HSSD`，`CLOUD_TSSD` 和 `CLOUD_BSSD`。",
										ValidateFunc: tccommon.ValidateAllowedStringValue(svcas.SYSTEM_DISK_ALLOW_TYPE),
									},
									"disk_size": {
										Type:        schema.TypeInt,
										Optional:    true,
										Default:     0,
										Description: "Volume 的 磁盘 （GB）。 默认为 `0`。",
									},
									"snapshot_id": {
										Type:        schema.TypeString,
										Optional:    true,
										ForceNew:    true,
										Description: "Data 磁盘 快照 ID。",
									},
									"delete_with_instance": {
										Type:        schema.TypeBool,
										Optional:    true,
										Description: "表示是否disk remove after 实例 terminated. 默认为 `false`。",
									},
									"encrypt": {
										Type:        schema.TypeBool,
										Optional:    true,
										Description: "指定是否encrypt 数据 磁盘，默认值：false. NOTE: Make sure 实例类型 是 offering 和 cam 角色 `QcloudKMSAccessForCVMRole` 是 提供。",
									},
									"throughput_performance": {
										Type:        schema.TypeInt,
										Optional:    true,
										Description: "Add extra performance 到 数据 磁盘. Only works 当 磁盘 类型 是 `CLOUD_TSSD` 或 `CLOUD_HSSD` 和 `data_size` > 460GB。",
									},
								},
							},
						},
						"instance_charge_type": {
							Type:        schema.TypeString,
							Optional:    true,
							Computed:    true,
							Description: "Charge 类型 实例. 有效 值 是 `PREPAID`，`POSTPAID_BY_HOUR`，`SPOTPAID`，`CDCPAID`. 默认为 `POSTPAID_BY_HOUR`. NOTE: `SPOTPAID` 实例 必须 集合 `spot_instance_type` 和 `spot_max_price` 在 same 时间。",
						},
						"instance_charge_type_prepaid_period": {
							Type:         schema.TypeInt,
							Optional:     true,
							Description:  "tenancy (在 month) 的 prepaid 实例，NOTE: 它 仅 works 当 instance_charge_type 是 集合 到 `PREPAID`. 有效 值 是 `1`，`2`，`3`，`4`，`5`，`6`，`7`，`8`，`9`，`10`，`11`，`12`，`24`，`36`。",
							ValidateFunc: tccommon.ValidateAllowedIntValue(svccvm.CVM_PREPAID_PERIOD),
						},
						"instance_charge_type_prepaid_renew_flag": {
							Type:         schema.TypeString,
							Optional:     true,
							Computed:     true,
							Description:  "自动续费标识 有效值：`NOTIFY_AND_AUTO_RENEW`: notify upon expiration 和 renew automatically，`NOTIFY_AND_MANUAL_RENEW`: notify upon expiration 但 do 不 renew automatically，`DISABLE_NOTIFY_AND_MANUAL_RENEW`: neither notify upon expiration nor renew automatically. 默认值：`NOTIFY_AND_MANUAL_RENEW`. 如果 此 参数 是 指定 作为 `NOTIFY_AND_AUTO_RENEW`， 实例 将 是 automatically renewed 在 monthly basis 如果 账号 balance 是 sufficient. NOTE: 它 仅 works 当 instance_charge_type 是 集合 到 `PREPAID`。",
							ValidateFunc: tccommon.ValidateAllowedStringValue(svccvm.CVM_PREPAID_RENEW_FLAG),
						},
						"spot_instance_type": {
							Type:         schema.TypeString,
							Optional:     true,
							Description:  "类型 spot 实例，仅 support `一个-时间` now. 注意: 它 仅 works 当 instance_charge_type 是 集合 到 `SPOTPAID`。",
							ValidateFunc: tccommon.ValidateAllowedStringValue([]string{"one-time"}),
						},
						"spot_max_price": {
							Type:         schema.TypeString,
							Optional:     true,
							Description:  "Max 价格 的 spot 实例, 是 格式 的 decimal 字符串, 对于 示例 \"0.50\". 注意: 它 仅 works 当 instance_charge_type 是 集合 到 `SPOTPAID`.",
							ValidateFunc: tccommon.ValidateStringNumber,
						},
						"internet_charge_type": {
							Type:         schema.TypeString,
							Optional:     true,
							Default:      "TRAFFIC_POSTPAID_BY_HOUR",
							Description:  "Charge types 对于 网络 流量. 有效 值: `BANDWIDTH_PREPAID`，`TRAFFIC_POSTPAID_BY_HOUR` 和 `BANDWIDTH_PACKAGE`。",
							ValidateFunc: tccommon.ValidateAllowedStringValue(svcas.INTERNET_CHARGE_ALLOW_TYPE),
						},
						"internet_max_bandwidth_out": {
							Type:        schema.TypeInt,
							Optional:    true,
							Default:     0,
							Description: "Max 带宽 的 Internet 访问 在 Mbps. 默认为 `0`。",
						},
						"bandwidth_package_id": {
							Type:        schema.TypeString,
							Optional:    true,
							Description: "带宽 包 ID. 如果 用户 是 standard 用户，then bandwidth_package_id 是 needed，或 默认值 has bandwidth_package_id。",
						},
						"public_ip_assigned": {
							Type:        schema.TypeBool,
							Optional:    true,
							Description: "指定是否assign 公网 IP 地址",
						},
						"ipv4_address_type": {
							Type:        schema.TypeString,
							Optional:    true,
							Computed:    true,
							Description: "类型 公网 IP 地址 WanIP: Ordinary 公网 IP 地址; HighQualityEIP: High Quality EIP 是 支持 仅 在 Singapore 和 Hong Kong; AntiDDoSEIP: Anti-DDoS IP 是 支持 仅 在 特定 regions. For details，see EIP Product Overview. 指定type 的 公有 IPv4 地址 到 assign 公有 IPv4 地址 到 资源. HighQualityEIP 和 AntiDDoSEIP features 是 gradually released 在 select regions. For usage，提交 ticket 对于 consultation。",
						},
						"password": {
							Type:          schema.TypeString,
							Optional:      true,
							ForceNew:      true,
							Sensitive:     true,
							ConflictsWith: []string{"auto_scaling_config.0.key_ids"},
							Description:   "密码 到 访问。",
							ValidateFunc:  tccommon.ValidateAsConfigPassword,
						},
						"key_ids": {
							Type:          schema.TypeList,
							Optional:      true,
							ForceNew:      true,
							ConflictsWith: []string{"auto_scaling_config.0.password"},
							Description:   "ID 列表 keys。",
							Elem: &schema.Schema{
								Type: schema.TypeString,
							},
						},
						"security_group_ids": {
							Type:          schema.TypeSet,
							Optional:      true,
							Computed:      true,
							ConflictsWith: []string{"auto_scaling_config.0.orderly_security_group_ids"},
							Description:   "Security groups 到 其中 CVM 实例 belongs。",
							Deprecated:    "The order of elements in this field cannot be guaranteed. Use `orderly_security_group_ids` instead.",
							Elem: &schema.Schema{
								Type: schema.TypeString,
							},
						},
						"orderly_security_group_ids": {
							Type:          schema.TypeList,
							Optional:      true,
							Computed:      true,
							ConflictsWith: []string{"auto_scaling_config.0.security_group_ids"},
							Description:   "Ordered 安全 groups 到 其中 CVM 实例 belongs。",
							Elem: &schema.Schema{
								Type: schema.TypeString,
							},
						},
						"enhanced_security_service": {
							Type:        schema.TypeBool,
							Optional:    true,
							Default:     true,
							Description: "To 指定是否enable 云 安全 服务. 默认为 TRUE。",
						},
						"enhanced_monitor_service": {
							Type:        schema.TypeBool,
							Optional:    true,
							ForceNew:    true,
							Default:     true,
							Description: "To 指定是否enable 云 监控 服务. 默认为 TRUE。",
						},
						"cam_role_name": {
							Type:        schema.TypeString,
							Optional:    true,
							ForceNew:    true,
							Description: "名称 cam 角色",
						},
						"instance_name": {
							Type:        schema.TypeString,
							Optional:    true,
							Computed:    true,
							Description: "实例名称，无 more 比 60 字符. For usage，refer 到 `InstanceNameSettings` 在 https://www.tencentcloud.com/document/product/377/31001。",
						},
						"instance_name_style": {
							Type:        schema.TypeString,
							Optional:    true,
							Computed:    true,
							Description: "类型 CVM 实例名称 有效值：`ORIGINAL` 和 `UNIQUE`. 默认值：`ORIGINAL`. For usage，refer 到 `InstanceNameSettings` 在 https://www.tencentcloud.com/document/product/377/31001。",
						},
						"host_name": {
							Type:        schema.TypeString,
							Optional:    true,
							Computed:    true,
							Description: "hostname 的 云 服务器，dot (.) 和 dash (-) 不能 是 使用 作为 first 和 last 字符 的 HostName 和 不能 是 使用 consecutively. Windows 实例 是 不 支持. Examples 的 other types (Linux，etc.): character 长度 是 [2，40]，多个 periods 是 allowed，和 there 是 paragraph between dots，和 each paragraph 是 allowed 到 consist 的 letters (unlimited case)，numbers 和 dashes (-). Pure numbers 是 不 allowed. For usage，refer 到 `HostNameSettings` 在 https://www.tencentcloud.com/document/product/377/31001。",
						},
						"host_name_style": {
							Type:        schema.TypeString,
							Optional:    true,
							Computed:    true,
							Description: "style 的 主机 名称 云 服务器， 值 范围 includes ORIGINAL 和 UNIQUE，和 默认为 ORIGINAL. For usage，refer 到 `HostNameSettings` 在 https://www.tencentcloud.com/document/product/377/31001。",
						},
						"cdc_id": {
							Type:        schema.TypeString,
							Optional:    true,
							ForceNew:    true,
							Description: "CDC ID。",
						},
					},
				},
			},

			"labels": {
				Type:        schema.TypeMap,
				Optional:    true,
				Description: "Labels 的 kubernetes 节点 池 创建 nodes. 标签 键 名称 does 不 exceed 63 字符，仅 支持 English，numbers,'/','-'，和 does 不 allow beginning 使用 ('/')。",
			},

			"unschedulable": {
				Type:        schema.TypeInt,
				Optional:    true,
				ForceNew:    true,
				Default:     0,
				Description: "Sets 是否joining 节点 participates 在 调度. 默认为 '0'. Participate 在 scheduling。",
			},

			"taints": {
				Type:        schema.TypeList,
				Optional:    true,
				Description: "Taints 的 kubernetes 节点 池 创建 nodes。",
				Elem: &schema.Resource{
					Schema: map[string]*schema.Schema{
						"key": {
							Type:        schema.TypeString,
							Required:    true,
							Description: "键 的 taint. taint 键 名称 does 不 exceed 63 字符，仅 支持 English，numbers,'/','-'，和 does 不 allow beginning 使用 ('/')。",
						},
						"value": {
							Type:        schema.TypeString,
							Required:    true,
							Description: "值 的 taint。",
						},
						"effect": {
							Type:        schema.TypeString,
							Required:    true,
							Description: "Effect 的 taint. 有效值：`NoSchedule`，`PreferNoSchedule`，`NoExecute`。",
						},
					},
				},
			},

			"delete_keep_instance": {
				Type:        schema.TypeBool,
				Optional:    true,
				Default:     true,
				Description: "Indicate 到 keep CVM 实例 当 delete 节点 池. 默认为 `true`。",
			},

			"deletion_protection": {
				Type:        schema.TypeBool,
				Optional:    true,
				Computed:    true,
				Description: "表示是否node 池 删除保护 是 已启用",
			},

			"annotations": {
				Type:        schema.TypeSet,
				Optional:    true,
				Computed:    true,
				Description: "Node Annotation List。",
				Elem: &schema.Resource{
					Schema: map[string]*schema.Schema{
						"name": {
							Type:        schema.TypeString,
							Required:    true,
							Description: "名称 在 map 表。",
						},
						"value": {
							Type:        schema.TypeString,
							Required:    true,
							Description: "值 在 map 表。",
						},
					},
				},
			},

			"node_os": {
				Type:        schema.TypeString,
				Optional:    true,
				Default:     "tlinux2.4x86_64",
				Description: "Node 池 operating 系统 (enter 镜像 ID 对于 自定义 镜像，和 enter OS 名称 对于 公有 镜像). 如果 自定义 镜像，please refer 到 [TencentCloud Documentation](https://www.tencentcloud.com/document/product/457/46750?lang=en&pg=#列表-的-公有-images-支持-通过-tke) 对于 可用 值. 默认为 'tlinux2.4x86_64'. 此 参数 将 仅 affect new nodes，不 包括 existing nodes。",
			},

			"node_os_type": {
				Type:             schema.TypeString,
				Optional:         true,
				Default:          "GENERAL",
				Description:      "镜像 版本 的 节点. Valida 值 是 `DOCKER_CUSTOMIZE` 和 `GENERAL`. 默认为 `GENERAL`. 此 参数 将 仅 affect new nodes，不 包括 existing nodes。",
				DiffSuppressFunc: nodeOsTypeDiffSuppressFunc,
			},

			"scaling_group_name": {
				Type:        schema.TypeString,
				Optional:    true,
				Computed:    true,
				Description: "名称 relative scaling 组。",
			},

			"zones": {
				Type:        schema.TypeList,
				Optional:    true,
				Description: "列表 auto scaling 组 可用 zones，对于 Basic 网络 它 为必填项。",
				Elem: &schema.Schema{
					Type: schema.TypeString,
				},
			},

			"scaling_group_project_id": {
				Type:        schema.TypeInt,
				Optional:    true,
				Default:     0,
				Description: "项目 ID scaling 组 belongs 到。",
			},

			"default_cooldown": {
				Type:        schema.TypeInt,
				Optional:    true,
				Computed:    true,
				Description: "Seconds 的 scaling 组 cool down. 默认值为 `300`。",
			},

			"termination_policies": {
				Type:        schema.TypeList,
				Optional:    true,
				Computed:    true,
				MaxItems:    1,
				Description: "Policy 的 scaling 组 termination. Available 值: `[\"OLDEST_INSTANCE\"]`, `[\"NEWEST_INSTANCE\"]`.",
				Elem: &schema.Schema{
					Type: schema.TypeString,
				},
			},

			"tags": {
				Type:        schema.TypeMap,
				Optional:    true,
				Computed:    true,
				Description: "Node 池 标签 specifications，将 passthroughs 到 scaling 实例。",
			},

			"status": {
				Type:        schema.TypeString,
				Computed:    true,
				Description: "状态 节点 池。",
			},

			"node_count": {
				Type:        schema.TypeInt,
				Computed:    true,
				Description: "总数 节点 count。",
			},

			"autoscaling_added_total": {
				Type:        schema.TypeInt,
				Computed:    true,
				Description: "总数 的 autoscaling added 节点。",
			},

			"manually_added_total": {
				Type:        schema.TypeInt,
				Computed:    true,
				Description: "总数 的 manually added 节点。",
			},

			"launch_config_id": {
				Type:        schema.TypeString,
				Computed:    true,
				Description: "launch 配置 ID。",
			},

			"auto_scaling_group_id": {
				Type:        schema.TypeString,
				Computed:    true,
				Description: "auto scaling 组 ID",
			},
		},
	}
}

func resourceTencentCloudKubernetesNodePoolCreate(d *schema.ResourceData, meta interface{}) error {
	defer tccommon.LogElapsed("resource.tencentcloud_kubernetes_node_pool.create")()
	defer tccommon.InconsistentCheck(d, meta)()

	logId := tccommon.GetLogId(tccommon.ContextNil)

	ctx := tccommon.NewResourceLifeCycleHandleFuncContext(context.Background(), logId, d, meta)

	var (
		clusterId  string
		nodePoolId string
	)
	var (
		request  = tkev20180525.NewCreateClusterNodePoolRequest()
		response = tkev20180525.NewCreateClusterNodePoolResponse()
	)

	if v, ok := d.GetOk("cluster_id"); ok {
		clusterId = v.(string)
	}

	request.ClusterId = helper.String(clusterId)

	if v, ok := d.GetOkExists("enable_auto_scale"); ok {
		request.EnableAutoscale = helper.Bool(v.(bool))
	}

	if v, ok := d.GetOk("name"); ok {
		request.Name = helper.String(v.(string))
	}

	if v, ok := d.GetOk("taints"); ok {
		for _, item := range v.([]interface{}) {
			taintsMap := item.(map[string]interface{})
			taint := tkev20180525.Taint{}
			if v, ok := taintsMap["key"]; ok {
				taint.Key = helper.String(v.(string))
			}
			if v, ok := taintsMap["value"]; ok {
				taint.Value = helper.String(v.(string))
			}
			if v, ok := taintsMap["effect"]; ok {
				taint.Effect = helper.String(v.(string))
			}
			request.Taints = append(request.Taints, &taint)
		}
	}

	if v, ok := d.GetOkExists("deletion_protection"); ok {
		request.DeletionProtection = helper.Bool(v.(bool))
	}

	if v, ok := d.GetOk("annotations"); ok {
		for _, item := range v.(*schema.Set).List() {
			annotationsMap := item.(map[string]interface{})
			annotationValue := tkev20180525.AnnotationValue{}
			if v, ok := annotationsMap["name"]; ok {
				annotationValue.Name = helper.String(v.(string))
			}
			if v, ok := annotationsMap["value"]; ok {
				annotationValue.Value = helper.String(v.(string))
			}
			request.Annotations = append(request.Annotations, &annotationValue)
		}
	}

	if err := resourceTencentCloudKubernetesNodePoolCreatePostFillRequest0(ctx, request); err != nil {
		return err
	}

	err := resource.Retry(tccommon.WriteRetryTimeout, func() *resource.RetryError {
		result, e := meta.(tccommon.ProviderMeta).GetAPIV3Conn().UseTkeV20180525Client().CreateClusterNodePoolWithContext(ctx, request)
		if e != nil {
			return tccommon.RetryError(e)
		} else {
			log.Printf("[DEBUG]%s api[%s] success, request body [%s], response body [%s]\n", logId, request.GetAction(), request.ToJsonString(), result.ToJsonString())
		}
		response = result
		return nil
	})
	if err != nil {
		log.Printf("[CRITAL]%s create kubernetes node pool failed, reason:%+v", logId, err)
		return err
	}

	nodePoolId = *response.Response.NodePoolId

	if err := resourceTencentCloudKubernetesNodePoolCreatePostHandleResponse0(ctx, response); err != nil {
		return err
	}

	d.SetId(strings.Join([]string{clusterId, nodePoolId}, tccommon.FILED_SP))

	return resourceTencentCloudKubernetesNodePoolRead(d, meta)
}

func resourceTencentCloudKubernetesNodePoolRead(d *schema.ResourceData, meta interface{}) error {
	defer tccommon.LogElapsed("resource.tencentcloud_kubernetes_node_pool.read")()
	defer tccommon.InconsistentCheck(d, meta)()

	logId := tccommon.GetLogId(tccommon.ContextNil)

	ctx := tccommon.NewResourceLifeCycleHandleFuncContext(context.Background(), logId, d, meta)

	service := TkeService{client: meta.(tccommon.ProviderMeta).GetAPIV3Conn()}

	idSplit := strings.Split(d.Id(), tccommon.FILED_SP)
	if len(idSplit) != 2 {
		return fmt.Errorf("id is broken,%s", d.Id())
	}
	clusterId := idSplit[0]
	nodePoolId := idSplit[1]

	_ = d.Set("cluster_id", clusterId)

	respData, err := service.DescribeKubernetesNodePoolById(ctx, clusterId)
	if err != nil {
		return err
	}

	if respData == nil {
		d.SetId("")
		log.Printf("[WARN]%s resource `kubernetes_node_pool` [%s] not found, please check if it has been deleted.\n", logId, d.Id())
		return nil
	}

	var respData1 *tkev20180525.NodePool
	reqErr1 := resource.Retry(tccommon.ReadRetryTimeout, func() *resource.RetryError {
		result, e := service.DescribeKubernetesNodePoolById1(ctx, clusterId, nodePoolId)
		if e != nil {
			if err := resourceTencentCloudKubernetesNodePoolReadRequestOnError1(ctx, result, e); err != nil {
				return err
			}
			return tccommon.RetryError(e)
		}
		if err := resourceTencentCloudKubernetesNodePoolReadRequestOnSuccess1(ctx, result); err != nil {
			return err
		}
		respData1 = result
		return nil
	})
	if reqErr1 != nil {
		log.Printf("[CRITAL]%s read kubernetes node pool failed, reason:%+v", logId, reqErr1)
		return reqErr1
	}

	if respData1 == nil {
		d.SetId("")
		log.Printf("[WARN]%s resource `kubernetes_node_pool` [%s] not found, please check if it has been deleted.\n", logId, d.Id())
		return nil
	}
	if respData1.Name != nil {
		_ = d.Set("name", respData1.Name)
	}

	if respData1.LifeState != nil {
		_ = d.Set("status", respData1.LifeState)
	}

	if respData1.LaunchConfigurationId != nil {
		_ = d.Set("launch_config_id", respData1.LaunchConfigurationId)
	}

	if respData1.AutoscalingGroupId != nil {
		_ = d.Set("auto_scaling_group_id", respData1.AutoscalingGroupId)
	}

	taintsList := make([]map[string]interface{}, 0, len(respData1.Taints))
	if respData1.Taints != nil {
		for _, taints := range respData1.Taints {
			taintsMap := map[string]interface{}{}

			if taints.Key != nil {
				taintsMap["key"] = taints.Key
			}

			if taints.Value != nil {
				taintsMap["value"] = taints.Value
			}

			if taints.Effect != nil {
				taintsMap["effect"] = taints.Effect
			}

			taintsList = append(taintsList, taintsMap)
		}

		_ = d.Set("taints", taintsList)
	}

	if respData1.NodeCountSummary != nil {
		if respData1.NodeCountSummary.ManuallyAdded != nil {
			if respData1.NodeCountSummary.ManuallyAdded.Total != nil {
				_ = d.Set("manually_added_total", respData1.NodeCountSummary.ManuallyAdded.Total)
			}

		}

		if respData1.NodeCountSummary.AutoscalingAdded != nil {
			if respData1.NodeCountSummary.AutoscalingAdded.Total != nil {
				_ = d.Set("autoscaling_added_total", respData1.NodeCountSummary.AutoscalingAdded.Total)
			}

		}

	}

	if respData1.MaxNodesNum != nil {
		_ = d.Set("max_size", respData1.MaxNodesNum)
	}

	if respData1.MinNodesNum != nil {
		_ = d.Set("min_size", respData1.MinNodesNum)
	}

	if respData1.DesiredNodesNum != nil {
		_ = d.Set("desired_capacity", respData1.DesiredNodesNum)
	}

	if respData1.DeletionProtection != nil {
		_ = d.Set("deletion_protection", respData1.DeletionProtection)
	}

	annotationsList := make([]map[string]interface{}, 0, len(respData1.Annotations))
	if respData1.Annotations != nil {
		for _, annotations := range respData1.Annotations {
			annotationsMap := map[string]interface{}{}

			if annotations.Name != nil {
				annotationsMap["name"] = annotations.Name
			}

			if annotations.Value != nil {
				annotationsMap["value"] = annotations.Value
			}

			annotationsList = append(annotationsList, annotationsMap)
		}

		_ = d.Set("annotations", annotationsList)
	}

	if err := resourceTencentCloudKubernetesNodePoolReadPostHandleResponse1(ctx, respData1); err != nil {
		return err
	}

	return nil
}

func resourceTencentCloudKubernetesNodePoolUpdate(d *schema.ResourceData, meta interface{}) error {
	defer tccommon.LogElapsed("resource.tencentcloud_kubernetes_node_pool.update")()
	defer tccommon.InconsistentCheck(d, meta)()

	logId := tccommon.GetLogId(tccommon.ContextNil)

	ctx := tccommon.NewResourceLifeCycleHandleFuncContext(context.Background(), logId, d, meta)

	idSplit := strings.Split(d.Id(), tccommon.FILED_SP)
	if len(idSplit) != 2 {
		return fmt.Errorf("id is broken,%s", d.Id())
	}
	clusterId := idSplit[0]
	nodePoolId := idSplit[1]

	if err := resourceTencentCloudKubernetesNodePoolUpdateOnStart(ctx); err != nil {
		return err
	}

	needChange := false
	mutableArgs := []string{"name", "max_size", "min_size", "enable_auto_scale", "deletion_protection", "annotations"}
	for _, v := range mutableArgs {
		if d.HasChange(v) {
			needChange = true
			break
		}
	}

	if needChange {
		request := tkev20180525.NewModifyClusterNodePoolRequest()

		request.ClusterId = helper.String(clusterId)

		request.NodePoolId = helper.String(nodePoolId)

		if v, ok := d.GetOk("name"); ok {
			request.Name = helper.String(v.(string))
		}

		if v, ok := d.GetOkExists("max_size"); ok {
			request.MaxNodesNum = helper.IntInt64(v.(int))
		}

		if v, ok := d.GetOkExists("min_size"); ok {
			request.MinNodesNum = helper.IntInt64(v.(int))
		}

		if v, ok := d.GetOkExists("enable_auto_scale"); ok {
			request.EnableAutoscale = helper.Bool(v.(bool))
		}

		if v, ok := d.GetOkExists("deletion_protection"); ok {
			request.DeletionProtection = helper.Bool(v.(bool))
		}

		if v, ok := d.GetOk("annotations"); ok {
			for _, item := range v.(*schema.Set).List() {
				annotationsMap := item.(map[string]interface{})
				annotationValue := tkev20180525.AnnotationValue{}
				if v, ok := annotationsMap["name"]; ok {
					annotationValue.Name = helper.String(v.(string))
				}
				if v, ok := annotationsMap["value"]; ok {
					annotationValue.Value = helper.String(v.(string))
				}
				request.Annotations = append(request.Annotations, &annotationValue)
			}
		}

		err := resource.Retry(tccommon.WriteRetryTimeout, func() *resource.RetryError {
			result, e := meta.(tccommon.ProviderMeta).GetAPIV3Conn().UseTkeV20180525Client().ModifyClusterNodePoolWithContext(ctx, request)
			if e != nil {
				return tccommon.RetryError(e)
			} else {
				log.Printf("[DEBUG]%s api[%s] success, request body [%s], response body [%s]\n", logId, request.GetAction(), request.ToJsonString(), result.ToJsonString())
			}
			return nil
		})
		if err != nil {
			log.Printf("[CRITAL]%s update kubernetes node pool failed, reason:%+v", logId, err)
			return err
		}
		if _, err := (&resource.StateChangeConf{
			Delay:      10 * time.Second,
			MinTimeout: 3 * time.Second,
			Pending:    []string{},
			Refresh:    resourceKubernetesNodePoolUpdateStateRefreshFunc_0_0(ctx, clusterId, nodePoolId),
			Target:     []string{"normal"},
			Timeout:    600 * time.Second,
		}).WaitForStateContext(ctx); err != nil {
			return err
		}
	}

	if err := resourceTencentCloudKubernetesNodePoolUpdateOnExit(ctx); err != nil {
		return err
	}

	return resourceTencentCloudKubernetesNodePoolRead(d, meta)
}

func resourceTencentCloudKubernetesNodePoolDelete(d *schema.ResourceData, meta interface{}) error {
	defer tccommon.LogElapsed("resource.tencentcloud_kubernetes_node_pool.delete")()
	defer tccommon.InconsistentCheck(d, meta)()

	logId := tccommon.GetLogId(tccommon.ContextNil)
	ctx := tccommon.NewResourceLifeCycleHandleFuncContext(context.Background(), logId, d, meta)

	idSplit := strings.Split(d.Id(), tccommon.FILED_SP)
	if len(idSplit) != 2 {
		return fmt.Errorf("id is broken,%s", d.Id())
	}
	clusterId := idSplit[0]
	nodePoolId := idSplit[1]

	var (
		request  = tkev20180525.NewDeleteClusterNodePoolRequest()
		response = tkev20180525.NewDeleteClusterNodePoolResponse()
	)

	request.ClusterId = helper.String(clusterId)

	request.NodePoolIds = []*string{helper.String(nodePoolId)}

	if v, ok := d.GetOkExists("delete_keep_instance"); ok {
		request.KeepInstance = helper.Bool(v.(bool))
	}

	if err := resourceTencentCloudKubernetesNodePoolDeletePostFillRequest0(ctx, request); err != nil {
		return err
	}

	err := resource.Retry(tccommon.WriteRetryTimeout, func() *resource.RetryError {
		result, e := meta.(tccommon.ProviderMeta).GetAPIV3Conn().UseTkeV20180525Client().DeleteClusterNodePoolWithContext(ctx, request)
		if e != nil {
			if err := resourceTencentCloudKubernetesNodePoolDeleteRequestOnError0(ctx, e); err != nil {
				return err
			}
			return tccommon.RetryError(e)
		} else {
			log.Printf("[DEBUG]%s api[%s] success, request body [%s], response body [%s]\n", logId, request.GetAction(), request.ToJsonString(), result.ToJsonString())
		}
		response = result
		return nil
	})
	if err != nil {
		log.Printf("[CRITAL]%s delete kubernetes node pool failed, reason:%+v", logId, err)
		return err
	}

	_ = response
	if err := resourceTencentCloudKubernetesNodePoolDeletePostHandleResponse0(ctx, response); err != nil {
		return err
	}

	return nil
}

func resourceKubernetesNodePoolUpdateStateRefreshFunc_0_0(ctx context.Context, clusterId string, nodePoolId string) resource.StateRefreshFunc {
	var req *tkev20180525.DescribeClusterNodePoolDetailRequest
	return func() (interface{}, string, error) {
		meta := tccommon.ProviderMetaFromContext(ctx)
		if meta == nil {
			return nil, "", fmt.Errorf("resource data can not be nil")
		}
		if req == nil {
			d := tccommon.ResourceDataFromContext(ctx)
			if d == nil {
				return nil, "", fmt.Errorf("resource data can not be nil")
			}
			_ = d
			req = tkev20180525.NewDescribeClusterNodePoolDetailRequest()
			req.ClusterId = helper.String(clusterId)

			req.NodePoolId = helper.String(nodePoolId)

		}
		resp, err := meta.(tccommon.ProviderMeta).GetAPIV3Conn().UseTkeV20180525Client().DescribeClusterNodePoolDetailWithContext(ctx, req)
		if err != nil {
			return nil, "", err
		}
		if resp == nil || resp.Response == nil {
			return nil, "", nil
		}
		state := fmt.Sprintf("%v", *resp.Response.NodePool.LifeState)
		return resp.Response, state, nil
	}
}
