// Code generated by iacg; DO NOT EDIT.
package tke

import (
	"context"
	"fmt"
	"log"
	"strings"

	"github.com/hashicorp/terraform-plugin-sdk/v2/helper/resource"
	"github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema"
	tkev20180525 "github.com/tencentcloud/tencentcloud-sdk-go/tencentcloud/tke/v20180525"
	tccommon "github.com/tencentcloudstack/terraform-provider-tencentcloud/tencentcloud/common"
	"github.com/tencentcloudstack/terraform-provider-tencentcloud/tencentcloud/internal/helper"
)

func ResourceTencentCloudKubernetesScaleWorker() *schema.Resource {
	return &schema.Resource{
		Create: resourceTencentCloudKubernetesScaleWorkerCreate,
		Read:   resourceTencentCloudKubernetesScaleWorkerRead,
		Delete: resourceTencentCloudKubernetesScaleWorkerDelete,
		Importer: &schema.ResourceImporter{
			StateContext: customScaleWorkerResourceImporter,
		},
		Schema: map[string]*schema.Schema{
			"cluster_id": {
				Type:        schema.TypeString,
				Required:    true,
				ForceNew:    true,
				Description: "ID 集群。",
			},

			"data_disk": {
				Type:        schema.TypeList,
				Optional:    true,
				ForceNew:    true,
				MaxItems:    11,
				Description: "TKE 数据盘配置",
				Elem: &schema.Resource{
					Schema: map[string]*schema.Schema{
						"auto_format_and_mount": {
							Type:        schema.TypeBool,
							Optional:    true,
							ForceNew:    true,
							Default:     false,
							Description: "Indicate 是否auto 格式 和 mount 或 不. 默认为 `false`。",
						},
						"disk_size": {
							Type:        schema.TypeInt,
							Optional:    true,
							ForceNew:    true,
							Default:     0,
							Description: "Volume 的 磁盘 （GB）。 默认为 `0`。",
						},
						"disk_type": {
							Type:        schema.TypeString,
							Optional:    true,
							ForceNew:    true,
							Default:     "CLOUD_PREMIUM",
							Description: "Types 的 磁盘，可用值：`CLOUD_PREMIUM` 和 `CLOUD_SSD` 和 `CLOUD_HSSD` 和 `CLOUD_TSSD`。",
						},
						"file_system": {
							Type:        schema.TypeString,
							Optional:    true,
							ForceNew:    true,
							Default:     "",
							Description: "File 系统，e.g. `ext3/ext4/xfs`。",
						},
						"mount_target": {
							Type:        schema.TypeString,
							Optional:    true,
							ForceNew:    true,
							Default:     "",
							Description: "挂载目标",
						},
						"disk_partition": {
							Type:        schema.TypeString,
							Optional:    true,
							ForceNew:    true,
							Default:     "",
							Description: "名称 device 或 分区 到 mount。",
						},
					},
				},
			},

			"desired_pod_num": {
				Type:        schema.TypeInt,
				Optional:    true,
				ForceNew:    true,
				Description: "Indicate 到 集合 desired pod 数量 在 当前 节点. 有效 当 集群 启用 customized pod cidr。",
			},

			"docker_graph_path": {
				Type:        schema.TypeString,
				Optional:    true,
				ForceNew:    true,
				Description: "Docker graph 路径 默认为 `/var/lib/docker`。",
			},

			"extra_args": {
				Type:        schema.TypeList,
				Optional:    true,
				ForceNew:    true,
				Description: "Custom 参数 信息 related 到 节点。",
				Elem: &schema.Schema{
					Type: schema.TypeString,
				},
			},

			"gpu_args": {
				Type:        schema.TypeList,
				Optional:    true,
				ForceNew:    true,
				MaxItems:    1,
				Description: "GPU 驱动 参数。",
				Elem: &schema.Resource{
					Schema: map[string]*schema.Schema{
						"cuda": {
							Type:        schema.TypeMap,
							Optional:    true,
							Description: "CUDA 版本 格式 like: `{ 版本: String，名称: String }`. `版本`: 版本 的 GPU 驱动 或 CUDA; `名称`: 名称 GPU 驱动 或 CUDA。",
						},
						"cudnn": {
							Type:        schema.TypeMap,
							Optional:    true,
							Description: "cuDNN 版本 格式 like: `{ 版本: String，名称: String，doc_name: String，dev_name: String }`. `版本`: cuDNN 版本; `名称`: cuDNN 名称; `doc_name`: Doc 名称 cuDNN; `dev_name`: Dev 名称 cuDNN。",
						},
						"custom_driver": {
							Type:        schema.TypeMap,
							Optional:    true,
							Description: "Custom GPU 驱动. 格式 like: `{地址: String}`. `地址`: URL 的 自定义 GPU 驱动 地址",
						},
						"driver": {
							Type:        schema.TypeMap,
							Optional:    true,
							Description: "GPU 驱动 版本 格式 like: `{ 版本: String，名称: String }`. `版本`: 版本 的 GPU 驱动 或 CUDA; `名称`: 名称 GPU 驱动 或 CUDA。",
						},
						"mig_enable": {
							Type:        schema.TypeBool,
							Optional:    true,
							Default:     false,
							Description: "是否enable MIG。",
						},
					},
				},
			},

			"labels": {
				Type:        schema.TypeMap,
				Optional:    true,
				ForceNew:    true,
				Description: "Labels 的 kubernetes scale worker 创建 nodes。",
			},

			"mount_target": {
				Type:        schema.TypeString,
				Optional:    true,
				ForceNew:    true,
				Description: "挂载目标 默认为 不 mounting。",
			},

			"unschedulable": {
				Type:        schema.TypeInt,
				Optional:    true,
				ForceNew:    true,
				Default:     0,
				Description: "Set 是否added 节点 participates 在 scheduling. 默认值为 0，其中 表示 participating 在 scheduling; non-0 表示 不 participating 在 scheduling. After 节点 initialization 是 completed，您 可以 execute kubectl uncordon nodename 到 join 节点 在 scheduling。",
			},

			"worker_config": {
				Type:        schema.TypeList,
				Required:    true,
				ForceNew:    true,
				MaxItems:    1,
				MinItems:    1,
				Description: "Deploy machine 配置 信息 的 'WORK' 服务，和 create <=20 units 对于 common users。",
				Elem: &schema.Resource{
					Schema: map[string]*schema.Schema{
						"availability_zone": {
							Type:        schema.TypeString,
							Optional:    true,
							ForceNew:    true,
							Description: "表示which availability 可用区 将 是 使用。",
						},
						"bandwidth_package_id": {
							Type:        schema.TypeString,
							Optional:    true,
							Description: "带宽 包 ID. 如果 用户 是 standard 用户，then bandwidth_package_id 是 needed，或 默认值 has bandwidth_package_id。",
						},
						"cam_role_name": {
							Type:        schema.TypeString,
							Optional:    true,
							ForceNew:    true,
							Description: "被授权访问的 CAM 角色名称",
						},
						"count": {
							Type:        schema.TypeInt,
							Optional:    true,
							ForceNew:    true,
							Default:     1,
							Description: "数量 cvm。",
						},
						"data_disk": {
							Type:        schema.TypeList,
							Optional:    true,
							ForceNew:    true,
							MaxItems:    11,
							Description: "CVM 数据盘配置",
							Elem: &schema.Resource{
								Schema: map[string]*schema.Schema{
									"auto_format_and_mount": {
										Type:        schema.TypeBool,
										Optional:    true,
										ForceNew:    true,
										Default:     false,
										Description: "Indicate 是否auto 格式 和 mount 或 不. 默认为 `false`。",
										Deprecated:  "This argument was deprecated, use `data_disk` instead.",
									},
									"disk_partition": {
										Type:        schema.TypeString,
										Optional:    true,
										ForceNew:    true,
										Description: "名称 device 或 分区 到 mount。",
										Deprecated:  "This argument was deprecated, use `data_disk` instead.",
									},
									"disk_size": {
										Type:        schema.TypeInt,
										Optional:    true,
										ForceNew:    true,
										Default:     0,
										Description: "Volume 的 磁盘 （GB）。 默认为 `0`。",
									},
									"disk_type": {
										Type:        schema.TypeString,
										Optional:    true,
										ForceNew:    true,
										Default:     "CLOUD_PREMIUM",
										Description: "Types 的 磁盘，可用值：`CLOUD_PREMIUM` 和 `CLOUD_SSD` 和 `CLOUD_HSSD` 和 `CLOUD_TSSD`。",
									},
									"encrypt": {
										Type:        schema.TypeBool,
										Optional:    true,
										Description: "表示是否encrypt 数据 磁盘，默认值 `false`。",
									},
									"file_system": {
										Type:        schema.TypeString,
										Optional:    true,
										ForceNew:    true,
										Description: "File 系统，e.g. `ext3/ext4/xfs`。",
										Deprecated:  "This argument was deprecated, use `data_disk` instead.",
									},
									"kms_key_id": {
										Type:        schema.TypeString,
										Optional:    true,
										Description: "ID 自定义 CMK 在 格式 的 UUID 或 `kms-abcd1234`. 此 参数 是 用于encrypt 云 disks。",
									},
									"mount_target": {
										Type:        schema.TypeString,
										Optional:    true,
										ForceNew:    true,
										Description: "挂载目标",
										Deprecated:  "This argument was deprecated, use `data_disk` instead.",
									},
									"snapshot_id": {
										Type:        schema.TypeString,
										Optional:    true,
										ForceNew:    true,
										Description: "Data 磁盘 快照 ID。",
									},
								},
							},
						},
						"desired_pod_num": {
							Type:        schema.TypeInt,
							Optional:    true,
							ForceNew:    true,
							Default:     0,
							Description: "Indicate 到 集合 desired pod 数量 在 节点. 有效 当 enable_customized_pod_cidr=true，和 它 override `[globe_]desired_pod_num` 对于 当前 节点. Either all 字段 `desired_pod_num` 或 none。",
						},
						"disaster_recover_group_ids": {
							Type:        schema.TypeList,
							Optional:    true,
							ForceNew:    true,
							Description: "Disaster recover groups 到 其中 CVM 实例 belongs. Only support 最大 1。",
							Elem: &schema.Schema{
								Type: schema.TypeString,
							},
						},
						"enhanced_monitor_service": {
							Type:        schema.TypeBool,
							Optional:    true,
							ForceNew:    true,
							Default:     true,
							Description: "To 指定是否enable 云 监控 服务. 默认为 TRUE。",
						},
						"enhanced_security_service": {
							Type:        schema.TypeBool,
							Optional:    true,
							ForceNew:    true,
							Default:     true,
							Description: "To 指定是否enable 云 安全 服务. 默认为 TRUE。",
						},
						"hostname": {
							Type:        schema.TypeString,
							Optional:    true,
							ForceNew:    true,
							Description: "主机 名称 attached 实例. Dot (.) 和 dash (-) 不能 是 使用 作为 first 和 last 字符 的 HostName 和 不能 是 使用 consecutively. Windows 示例: 长度 的 名称 character 是 [2，15]，letters (capitalization 是 不 restricted)，numbers 和 dashes (-) 是 allowed，dots (.) 是 不 支持，和 不 all numbers 是 allowed. Examples 的 other types (Linux，etc.): character 长度 是 [2，60]，和 多个 dots 是 allowed. There 是 segment between dots. Each segment allows letters (使用 无 limitation 在 capitalization)，numbers 和 dashes (-)。",
						},
						"hpc_cluster_id": {
							Type:        schema.TypeString,
							Optional:    true,
							Description: "ID 的 cvm hpc 集群。",
						},
						"img_id": {
							Type:        schema.TypeString,
							Optional:    true,
							Description: "有效 镜像 ID，格式 的 img-xxx。",
						},
						"instance_charge_type": {
							Type:        schema.TypeString,
							Optional:    true,
							ForceNew:    true,
							Default:     "POSTPAID_BY_HOUR",
							Description: "charge 类型 实例. 有效 值 是 `PREPAID`，`POSTPAID_BY_HOUR`，`SPOTPAID`，`CDCPAID`. 默认为 `POSTPAID_BY_HOUR`. 注意: TencentCloud International 仅 支持 `POSTPAID_BY_HOUR`，`PREPAID` 实例 将 不 terminated after 集群 删除，和 可能 不 allow 到 delete before expired。",
						},
						"instance_charge_type_prepaid_period": {
							Type:        schema.TypeInt,
							Optional:    true,
							ForceNew:    true,
							Default:     1,
							Description: "tenancy (时间 单位 是 month) 的 prepaid 实例. NOTE: 它 仅 works 当 instance_charge_type 是 集合 到 `PREPAID`. 有效 值 是 `1`，`2`，`3`，`4`，`5`，`6`，`7`，`8`，`9`，`10`，`11`，`12`，`24`，`36`。",
						},
						"instance_charge_type_prepaid_renew_flag": {
							Type:        schema.TypeString,
							Optional:    true,
							Computed:    true,
							ForceNew:    true,
							Description: "自动续费标识 有效值：`NOTIFY_AND_AUTO_RENEW`: notify upon expiration 和 renew automatically，`NOTIFY_AND_MANUAL_RENEW`: notify upon expiration 但 do 不 renew automatically，`DISABLE_NOTIFY_AND_MANUAL_RENEW`: neither notify upon expiration nor renew automatically. 默认值：`NOTIFY_AND_MANUAL_RENEW`. 如果 此 参数 是 指定 作为 `NOTIFY_AND_AUTO_RENEW`， 实例 将 是 automatically renewed 在 monthly basis 如果 账号 balance 是 sufficient. NOTE: 它 仅 works 当 instance_charge_type 是 集合 到 `PREPAID`。",
						},
						"instance_name": {
							Type:        schema.TypeString,
							Optional:    true,
							ForceNew:    true,
							Default:     "sub machine of tke",
							Description: "名称 CVMs。",
						},
						"instance_type": {
							Type:        schema.TypeString,
							Required:    true,
							ForceNew:    true,
							Description: "Specified types 的 CVM 实例。",
						},
						"internet_charge_type": {
							Type:        schema.TypeString,
							Optional:    true,
							ForceNew:    true,
							Default:     "TRAFFIC_POSTPAID_BY_HOUR",
							Description: "Charge types 对于 网络 流量. Available 值 include `TRAFFIC_POSTPAID_BY_HOUR`。",
						},
						"internet_max_bandwidth_out": {
							Type:        schema.TypeInt,
							Optional:    true,
							Default:     0,
							Description: "Max 带宽 的 Internet 访问 在 Mbps. 默认为 0。",
						},
						"key_ids": {
							Type:        schema.TypeList,
							Optional:    true,
							ForceNew:    true,
							MaxItems:    1,
							Description: "ID 列表 keys，should 是 集合 如果 `密码` 不 集合。",
							Elem: &schema.Schema{
								Type: schema.TypeString,
							},
						},
						"password": {
							Type:        schema.TypeString,
							Optional:    true,
							ForceNew:    true,
							Sensitive:   true,
							Description: "密码 到 访问，should 是 集合 如果 `key_ids` 不 集合。",
						},
						"public_ip_assigned": {
							Type:        schema.TypeBool,
							Optional:    true,
							ForceNew:    true,
							Description: "指定是否assign 公网 IP 地址",
						},
						"security_group_ids": {
							Type:        schema.TypeList,
							Optional:    true,
							ForceNew:    true,
							Description: "Security groups 到 其中 CVM 实例 belongs。",
							Elem: &schema.Schema{
								Type: schema.TypeString,
							},
						},
						"subnet_id": {
							Type:        schema.TypeString,
							Required:    true,
							ForceNew:    true,
							Description: "Private 网络 ID。",
						},
						"system_disk_size": {
							Type:        schema.TypeInt,
							Optional:    true,
							ForceNew:    true,
							Default:     50,
							Description: "Volume 的 系统 磁盘 （GB）。 默认为 `50`。",
						},
						"system_disk_type": {
							Type:        schema.TypeString,
							Optional:    true,
							ForceNew:    true,
							Default:     "CLOUD_PREMIUM",
							Description: "System 磁盘 类型 For more 信息 在 limits 的 系统 磁盘 types，see [Storage Overview](https://intl.云.tencent.com/document/product/213/4952). 有效值：`LOCAL_BASIC`: 本地 磁盘，`LOCAL_SSD`: 本地 SSD 磁盘，`CLOUD_SSD`: SSD，`CLOUD_PREMIUM`: Premium Cloud Storage. NOTE: `CLOUD_BASIC`，`LOCAL_BASIC` 和 `LOCAL_SSD` 是 已弃用",
						},
						"user_data": {
							Type:        schema.TypeString,
							Optional:    true,
							ForceNew:    true,
							Description: "用户 数据 提供 到 实例，needs 到 是 encoded 在 base64，和 最大 支持 数据 大小 是 16KB。",
						},
						"tags": {
							Type:        schema.TypeList,
							Optional:    true,
							ForceNew:    true,
							Computed:    true,
							Description: "标签 pairs。",
							Elem: &schema.Resource{
								Schema: map[string]*schema.Schema{
									"key": {
										Type:        schema.TypeString,
										Required:    true,
										ForceNew:    true,
										Description: "标签键",
									},
									"value": {
										Type:        schema.TypeString,
										Required:    true,
										ForceNew:    true,
										Description: "标签值",
									},
								},
							},
						},
						"cdc_id": {
							Type:        schema.TypeString,
							Optional:    true,
							ForceNew:    true,
							Description: "CDC ID。",
						},
					},
				},
			},

			"pre_start_user_script": {
				Type:        schema.TypeString,
				Optional:    true,
				ForceNew:    true,
				Description: "Base64-encoded 用户 脚本，executed before initializing 节点，currently 仅 effective 对于 adding existing nodes。",
			},

			"taints": {
				Type:        schema.TypeList,
				Optional:    true,
				ForceNew:    true,
				Description: "Node taint。",
				Elem: &schema.Resource{
					Schema: map[string]*schema.Schema{
						"key": {
							Type:        schema.TypeString,
							Optional:    true,
							ForceNew:    true,
							Description: "键 的 taint。",
						},
						"value": {
							Type:        schema.TypeString,
							Optional:    true,
							ForceNew:    true,
							Description: "值 的 taint。",
						},
						"effect": {
							Type:        schema.TypeString,
							Optional:    true,
							ForceNew:    true,
							Description: "Effect 的 taint。",
						},
					},
				},
			},

			"user_script": {
				Type:        schema.TypeString,
				Optional:    true,
				ForceNew:    true,
				Description: "Base64 encoded 用户 脚本，此 脚本 将 是 executed after k8s 组件 是 run. 用户 needs 到 ensure 该 脚本 是 reentrant 和 retry logic. 脚本 和 its generated 日志 files 可以 是 viewed 在 /数据/ccs_userscript/ 路径 的 节点，如果 必填 节点 needs 到 是 initialized before 它 可以 是 added 到 调度. It 可以 是 使用 使用 unschedulable 参数. After final initialization 的 userScript 是 completed，add kubectl uncordon nodename --kubeconfig=/root/.kube/配置 command 到 add 节点 到 调度。",
			},

			"worker_instances_list": {
				Type:        schema.TypeList,
				Computed:    true,
				Description: "An 信息 列表 kubernetes 集群 'WORKER'. Each element 包含following attributes:",
				Elem: &schema.Resource{
					Schema: map[string]*schema.Schema{
						"failed_reason": {
							Type:        schema.TypeString,
							Computed:    true,
							Description: "Information 的 cvm 当 它 是 failed。",
						},
						"instance_id": {
							Type:        schema.TypeString,
							Computed:    true,
							Description: "ID cvm。",
						},
						"instance_role": {
							Type:        schema.TypeString,
							Computed:    true,
							Description: "角色 的 cvm。",
						},
						"instance_state": {
							Type:        schema.TypeString,
							Computed:    true,
							Description: "State 的 cvm。",
						},
						"lan_ip": {
							Type:        schema.TypeString,
							Computed:    true,
							Description: "LAN IP 的 cvm。",
						},
					},
				},
			},

			"create_result_output_file": {
				Type:        schema.TypeString,
				Optional:    true,
				ForceNew:    true,
				Description: "用于保存结果 的 CVMs creation 错误 messages。",
			},
		},
	}
}

func resourceTencentCloudKubernetesScaleWorkerCreate(d *schema.ResourceData, meta interface{}) error {
	defer tccommon.LogElapsed("resource.tencentcloud_kubernetes_scale_worker.create")()
	defer tccommon.InconsistentCheck(d, meta)()

	logId := tccommon.GetLogId(tccommon.ContextNil)

	ctx := tccommon.NewResourceLifeCycleHandleFuncContext(context.Background(), logId, d, meta)

	if err := resourceTencentCloudKubernetesScaleWorkerCreateOnStart(ctx); err != nil {
		return err
	}

	_ = ctx
	return resourceTencentCloudKubernetesScaleWorkerRead(d, meta)
}

func resourceTencentCloudKubernetesScaleWorkerRead(d *schema.ResourceData, meta interface{}) error {
	defer tccommon.LogElapsed("resource.tencentcloud_kubernetes_scale_worker.read")()
	defer tccommon.InconsistentCheck(d, meta)()

	logId := tccommon.GetLogId(tccommon.ContextNil)

	ctx := tccommon.NewResourceLifeCycleHandleFuncContext(context.Background(), logId, d, meta)

	service := TkeService{client: meta.(tccommon.ProviderMeta).GetAPIV3Conn()}

	idSplit := strings.Split(d.Id(), tccommon.FILED_SP)
	if len(idSplit) != 2 {
		return fmt.Errorf("id is broken,%s", d.Id())
	}
	clusterId := idSplit[0]
	instanceIdSet := idSplit[1]

	_ = d.Set("cluster_id", clusterId)

	respData, err := service.DescribeKubernetesScaleWorkerById(ctx, clusterId)
	if err != nil {
		return err
	}

	if respData == nil {
		d.SetId("")
		log.Printf("[WARN]%s resource `kubernetes_scale_worker` [%s] not found, please check if it has been deleted.\n", logId, d.Id())
		return nil
	}
	if err := resourceTencentCloudKubernetesScaleWorkerReadPostHandleResponse0(ctx, respData); err != nil {
		return err
	}

	_ = instanceIdSet
	return nil
}

func resourceTencentCloudKubernetesScaleWorkerDelete(d *schema.ResourceData, meta interface{}) error {
	defer tccommon.LogElapsed("resource.tencentcloud_kubernetes_scale_worker.delete")()
	defer tccommon.InconsistentCheck(d, meta)()

	logId := tccommon.GetLogId(tccommon.ContextNil)
	ctx := tccommon.NewResourceLifeCycleHandleFuncContext(context.Background(), logId, d, meta)

	idSplit := strings.Split(d.Id(), tccommon.FILED_SP)
	if len(idSplit) != 2 {
		return fmt.Errorf("id is broken,%s", d.Id())
	}
	clusterId := idSplit[0]
	instanceIdSet := idSplit[1]

	var (
		request  = tkev20180525.NewDescribeClustersRequest()
		response = tkev20180525.NewDescribeClustersResponse()
	)

	request.ClusterIds = []*string{helper.String(clusterId)}

	err := resource.Retry(tccommon.WriteRetryTimeout, func() *resource.RetryError {
		result, e := meta.(tccommon.ProviderMeta).GetAPIV3Conn().UseTkeV20180525Client().DescribeClustersWithContext(ctx, request)
		if e != nil {
			return tccommon.RetryError(e)
		} else {
			log.Printf("[DEBUG]%s api[%s] success, request body [%s], response body [%s]\n", logId, request.GetAction(), request.ToJsonString(), result.ToJsonString())
		}
		if err := resourceTencentCloudKubernetesScaleWorkerDeletePostRequest0(ctx, request, result); err != nil {
			return err
		}

		response = result
		return nil
	})
	if err != nil {
		log.Printf("[CRITAL]%s delete kubernetes scale worker failed, reason:%+v", logId, err)
		return err
	}

	_ = response
	if err := resourceTencentCloudKubernetesScaleWorkerDeleteOnExit(ctx); err != nil {
		return err
	}

	_ = instanceIdSet
	return nil
}
